### ISSUE TITLE
default netconf connection to Nokia (Alcatel-Lucent) routers failes

### ISSUE THREAD

**Issue by hellt** [ncclient/ncclient#117]
When I try to connect to Nokia (former Alcatel-lucent) router **without** specifying  `device_params` option I got this traceback after timeout expiration

```
Traceback (most recent call last):
  File "/Users/romandodin/PyProjects/nokia_netconf/app.py", line 17, in <module>
    c = m.get(('subtree', req))
  File "/Users/romandodin/src/ncclient/ncclient/manager.py", line 158, in wrapper
    return self.execute(op_cls, *args, **kwds)
  File "/Users/romandodin/src/ncclient/ncclient/manager.py", line 228, in execute
    raise_mode=self._raise_mode).request(*args, **kwds)
  File "/Users/romandodin/src/ncclient/ncclient/operations/retrieve.py", line 66, in request
    return self._request(node)
  File "/Users/romandodin/src/ncclient/ncclient/operations/rpc.py", line 326, in _request
    raise self._error
  File "/Users/romandodin/src/ncclient/ncclient/transport/ssh.py", line 528, in run
    self._parse11()
  File "/Users/romandodin/src/ncclient/ncclient/transport/ssh.py", line 186, in _parse11
    raise Exception
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/romandodin/PyProjects/nokia_netconf/app.py", line 18, in <module>
    print(c)
  File "/Users/romandodin/src/ncclient/ncclient/manager.py", line 210, in __exit__
    self.close_session()
  File "/Users/romandodin/src/ncclient/ncclient/manager.py", line 158, in wrapper
    return self.execute(op_cls, *args, **kwds)
  File "/Users/romandodin/src/ncclient/ncclient/manager.py", line 228, in execute
    raise_mode=self._raise_mode).request(*args, **kwds)
  File "/Users/romandodin/src/ncclient/ncclient/operations/session.py", line 28, in request
    return self._request(new_ele("close-session"))
  File "/Users/romandodin/src/ncclient/ncclient/operations/rpc.py", line 343, in _request
    raise TimeoutExpiredError('ncclient timed out while waiting for an rpc reply.')
ncclient.operations.errors.TimeoutExpiredError: ncclient timed out while waiting for an rpc reply.
```

Then I enabled logging and saw this error:
```
DEBUG:ncclient.transport.ssh:Selecting netconf:base:1.1 for encoding
DEBUG:ncclient.transport.ssh:parsing netconf v1.1
DEBUG:ncclient.transport.ssh:x: b'\n'
DEBUG:ncclient.transport.ssh:invalid base:1:1 frame (0: expect newline)
DEBUG:ncclient.transport.ssh:Broke out of main loop, error=Exception()
DEBUG:ncclient.transport.session:dispatching error to <ncclient.operations.rpc.RPCReplyListener object at 0x10494b240>
DEBUG:ncclient.transport.ssh:EOF in transport thread
INFO:ncclient.operations.rpc:Requesting 'CloseSession'
Traceback (most recent call last):
  File "/Users/romandodin/PyProjects/nokia_netconf/app.py", line 16, in <module>
    c = m.get(('subtree', req))
  File "/Users/romandodin/src/ncclient/ncclient/manager.py", line 158, in wrapper
    return self.execute(op_cls, *args, **kwds)
  File "/Users/romandodin/src/ncclient/ncclient/manager.py", line 228, in execute
    raise_mode=self._raise_mode).request(*args, **kwds)
  File "/Users/romandodin/src/ncclient/ncclient/operations/retrieve.py", line 66, in request
    return self._request(node)
  File "/Users/romandodin/src/ncclient/ncclient/operations/rpc.py", line 326, in _request
    raise self._error
  File "/Users/romandodin/src/ncclient/ncclient/transport/ssh.py", line 528, in run
    self._parse11()
  File "/Users/romandodin/src/ncclient/ncclient/transport/ssh.py", line 186, in _parse11
    raise Exception
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/romandodin/PyProjects/nokia_netconf/app.py", line 17, in <module>
    print(c)
  File "/Users/romandodin/src/ncclient/ncclient/manager.py", line 210, in __exit__
    self.close_session()
  File "/Users/romandodin/src/ncclient/ncclient/manager.py", line 158, in wrapper
    return self.execute(op_cls, *args, **kwds)
  File "/Users/romandodin/src/ncclient/ncclient/manager.py", line 228, in execute
    raise_mode=self._raise_mode).request(*args, **kwds)
  File "/Users/romandodin/src/ncclient/ncclient/operations/session.py", line 28, in request
    return self._request(new_ele("close-session"))
  File "/Users/romandodin/src/ncclient/ncclient/operations/rpc.py", line 316, in _request
    self._session.send(req)
  File "/Users/romandodin/src/ncclient/ncclient/transport/session.py", line 150, in send
    raise TransportError('Not connected to NETCONF server')
ncclient.transport.errors.TransportError: Not connected to NETCONF server
```

For some reason ncclient (or paramiko?) cant handle response from the netconf server properly. That is why the only thing `device_params={'name': 'alu'}` does is restricting client to advertise only `base:1.0` capability. 
But if the actual reason for this error? How to tell if this a bug in ncclient/paramiko?

**Comment by leopoul** [comment]
Could you try this: https://github.com/ncclient/ncclient/wiki/Debug#test-netconf-subsystem-response and provide the output? Commands may vary depending on your device.

Best,
L.

**Comment by hellt** [comment]
I will try to investigate this locally, seems this was a bug on ALU netconf server side, it should have been fixed. Will see if newer releases behave similarly
