### ISSUE TITLE
manager.connect to Alcatel/Nokia doen't include RPC method

### ISSUE THREAD

**Issue by jbotello7381** [ncclient/ncclient#129]
>>> router = manager.connect(host="10.1.1.1", port=830, username="netconf", password="password!", hostkey_verify=False, device_params={'name':'alu'})

>>>
>>> dir(router)
['_Manager__set_async_mode', '_Manager__set_raise_mode', '_Manager__set_timeout', '__class__', '__delattr__', '__dict__', '__doc__', '__enter__', '__exit__', '__format__', '__getattr__', '__getattribute__', '__hash__', '__init__', '__metaclass__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_async_mode', '_device_handler', '_raise_mode', '_session', '_timeout', 'async_mode', 'channel_id', 'channel_name', 'client_capabilities', 'close_session', 'commit', 'connected', 'copy_config', 'delete_config', 'discard_changes', 'dispatch', 'edit_config', 'execute', 'get', 'get_config', 'get_schema', 'kill_session', 'lock', 'locked', 'poweroff_machine', 'raise_mode', 'reboot_machine', 'scp', 'server_capabilities', 'session', 'session_id', 'timeout', 'unlock', 'validate']
>>>
>>> rpc = """
... <cli-action>
...     <admin>rollback save</admin>
... </cli-action>"""
>>>
>>> result = router.rpc(rpc)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ncclient/manager.py", line 260, in _missing
    sub_ele(root, arg)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ncclient/xml_.py", line 190, in <lambda>
    sub_ele = lambda parent, tag, attrs={}, **extra: etree.SubElement(parent, qualify(tag), attrs, **extra)
  File "src/lxml/lxml.etree.pyx", line 3112, in lxml.etree.SubElement (src/lxml/lxml.etree.c:76595)
  File "src/lxml/apihelpers.pxi", line 183, in lxml.etree._makeSubElement (src/lxml/lxml.etree.c:16951)
  File "src/lxml/apihelpers.pxi", line 1626, in lxml.etree._tagValidOrRaise (src/lxml/lxml.etree.c:32662)
ValueError: Invalid tag name u'\n<cli-action>\n    <admin>rollback save</admin>\n</cli-action>'

If i create a connection to a juniper, the RPC is available for both router and juniper object.

>>> juniper = manager.connect(host="10.2.2.2t", port=22, username="netconf", password="password", hostkey_verify=False, device_params={'name':'junos'})
>>>
>>>
>>> dir(router)
['_Manager__set_async_mode', '_Manager__set_raise_mode', '_Manager__set_timeout', '__class__', '__delattr__', '__dict__', '__doc__', '__enter__', '__exit__', '__format__', '__getattr__', '__getattribute__', '__hash__', '__init__', '__metaclass__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_async_mode', '_device_handler', '_raise_mode', '_session', '_timeout', 'async_mode', 'channel_id', 'channel_name', 'client_capabilities', 'close_session', 'command', 'commit', 'compare_configuration', 'connected', 'copy_config', 'delete_config', 'discard_changes', 'dispatch', 'edit_config', 'execute', 'get', 'get_config', 'get_configuration', 'get_schema', 'halt', 'kill_session', 'load_configuration', 'lock', 'locked', 'poweroff_machine', 'raise_mode', 'reboot', 'reboot_machine', '**rpc**', 'scp', 'server_capabilities', 'session', 'session_id', 'timeout', 'unlock', 'validate']
>>>

>>> result = router.rpc(rpc)
>>> print result
<?xml version="1.0" encoding="UTF-8"?>
<rpc-reply message-id="urn:uuid:feff16b5-1886-11e6-a59b-24a074f035de" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
    <data xmlns="urn:alcatel-lucent.com:sros:ns:yang:cli-content-layer-r13">
        <cli-action>
            <item>
                <admin>rollback save</admin>
                <response>
OK
                </response>
            </item>
        </cli-action>
    </data>
</rpc-reply>

**Comment by leopoul** [comment]
Could you provide the input and output when running the RPC from cli? You would need to login to netconf subsystem. You could check: https://github.com/ncclient/ncclient/wiki/Debug#test-netconf-subsystem-response for details. Commands may vary depending on your device.

Best,
L.

**Comment by jbotello7381** [comment]
Hi Leonidas,

I will run the test during this week.   However, this is how i modify
ncclient in my github repository to add rpc call when using alu.py device
handler

https://github.com/jbotello7381/ncclient/blob/master/ncclient/devices/alu.py

After that, i was able to use rpc with alcatel.

This is the command I'm sending using ncclient

<cli-action>
    <admin>rollback save</admin>
</cli-action>


def config_push(self):
# For Nokia RPC support I have to hack
/library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/
# site-packages/ncclient/devices/alu.py
if self.vendor == "juniper":
config = Config(self.router)
config.load(self.config, format="xml", merge=True)
print "\nLoading configuration to %s !!!" % self.hostname
print(config.pdiff())
config.rollback(rb_id=0)
elif self.vendor == "nokia":
print "\nCreating Rollback Checkpoint..."
xmlstr = etree.tostring(etree.parse("templates/rollback_command.xml"),
encoding="utf8", method="xml")
print self.router.rpc(xmlstr)
self.router.edit_config(target="running", config=self.config)
print "\nLoading configuration to %s !!!" % self.hostname

**Comment by leopoul** [comment]
Have you tried to build your xml configuration and then use dispatch? https://github.com/ncclient/ncclient/blob/master/ncclient/operations/retrieve.py#L152

Would that work for you?

Best,
L.
