### ISSUE TITLE
v0.4.7 is not python3 ready

### ISSUE THREAD

**Issue by dgjnpr** [ncclient/ncclient#141]
Hi,

I just tried to install junos-eznc - and this installed ncclient as a dependency. During the pip3 install ncclient fails with a SyntaxError. The irony is that the error happens when reporting that Python 3 is not supported.

Here's the output of the error:

```bash
$ sudo -H pip3 install --upgrade junos-eznc       
Collecting junos-eznc
  Downloading junos-eznc-1.3.1.tar.gz (64kB)
    100% |████████████████████████████████| 71kB 29kB/s 
Collecting lxml>=3.2.4 (from junos-eznc)
  Downloading lxml-3.6.0.tar.gz (3.7MB)
    100% |████████████████████████████████| 3.7MB 56kB/s 
Collecting ncclient>=0.4.6 (from junos-eznc)
  Downloading ncclient-0.4.7.tar.gz (60kB)
    100% |████████████████████████████████| 61kB 13kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-xut6xbwv/ncclient/setup.py", line 24
        print "Sorry, Python 3 is not supported (yet)"
                                                     ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-xut6xbwv/ncclient/
```

By the looks of things v0.5.0 resolves this. However pip3 only has access to v0.4.7.

**Comment by vnitinv** [comment]
@dgjnpr For now do install ncclient too from github. It will be released in PyPI in few days.
