### ISSUE TITLE
Install on windows 

### ISSUE THREAD

**Issue by kyzma84** [ncclient/ncclient#149]
Hi
I got this error  when tried  install package on windows 7 , python 3.5. 

`Collecting ncclient
  Using cached ncclient-0.5.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Skuzniec\AppData\Local\Temp\pip-build-mpfw4qcu\ncclient\set
up.py", line 32, in <module>
        long_description = file.read()
      File "C:\Users\Skuzniec\AppData\Local\Programs\Python\Python35\lib\encodin
gs\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 4336:
 character maps to <undefined>
`

**Comment by christung16** [comment]
I have the same issue when installing ncclient in windows 10

**Comment by corhoade** [comment]
Same here.  Both Python 2.7 and 3.5.

**Comment by christung16** [comment]
The problem is that in the file README.rst, some characters are not recognized in cp1252 encoding.

Here's the way to workaround it:
1. download and unzip the ncclient-0.5.2.tar.gz
2. Use MSWord to open READ.rst
3. Save as another coding. I choose windows (default). It will warn you some characters will be missing.
4. python setup.py install <<<< to install the ncclient module

DONE!

**Comment by answanso** [comment]
I get the following error when i try to install ncclient on ubuntu and centos:

Collecting ncclient
  Using cached ncclient-0.5.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-g5js2iie/ncclient/setup.py", line 32, in <module>
        long_description = file.read()
      File "/usr/local/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 4335: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-g5js2iie/ncclient/

I tried this with python 3.4.5 and 3.5.2. I am able to get it to work on OSX.

**Comment by cspeidel** [comment]
@kyzma84 @christung16 @corhoade 
The file looks UTF-8 to me.  
`[cspeidel@net01 ncclient]$ file -i README.rst 
README.rst: text/x-python; charset=utf-8
`
I also double-checked with iconv and verified the UTF-8 output was the same. 

Are you still having this issue with 0.3.5?
