### ISSUE TITLE
huawei close session error

### ISSUE THREAD

**Issue by gothack329** [ncclient/ncclient#156]
```
 <?xml version="1.0" encoding="UTF-8"?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:4a6e6bf6-acdf-4860-b6e9-c58ddb5e4c9b">
<close-session type="subtree"/>
</rpc>

```

this xml got a wrong format on huawei device. close-session has no type value...
it should be like this:
```
<?xml version="1.0" encoding="UTF-8"?>
<rpc message-id="101" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <close-session/>
</rpc>
```

**Comment by leopoul** [comment]
Could you paste the Python code you use to close session?

Thanks!
L.

**Comment by gothack329** [comment]
The Python code is 
```
with manager.connect("host") as m:
    result = m.get(('subtree', xml_template))
    print result
```
I got the debug info below:
```
Mon, 05 Sep 2016 10:13:10 rpc.py[line:314] INFO Requesting 'CloseSession'
Mon, 05 Sep 2016 10:13:10 session.py[line:153] DEBUG queueing <?xml version="1.0" encoding="UTF-8"?><rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:dce40930-c808-4032-a3d4-9b1102798a66"><close-session type="subtree"/></rpc>
Mon, 05 Sep 2016 10:13:10 rpc.py[line:321] DEBUG Sync request, will wait for timeout=30
Mon, 05 Sep 2016 10:13:11 ssh.py[line:520] DEBUG Sending message
Mon, 05 Sep 2016 10:13:11 ssh.py[line:546] DEBUG Sending: <?xml version="1.0" encoding="UTF-8"?><rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:dce40930-c808-4032-a3d4-9b1102798a66"><close-session type="subtree"/></rpc>]]>]]>
Mon, 05 Sep 2016 10:13:11 ssh.py[line:512] DEBUG Selecting netconf:base:1.0 for encoding
Mon, 05 Sep 2016 10:13:11 ssh.py[line:115] DEBUG parsing netconf v1.0
Mon, 05 Sep 2016 10:13:11 session.py[line:67] DEBUG dispatching message to <ncclient.operations.rpc.RPCReplyListener object at 0x103718590>: <?xml version="1.0" encoding="UTF-8"?>
<rpc-reply message-id="urn:uuid:dce40930-c808-4032-a3d4-9b1102798a66" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <rpc-error>
    <error-type>protocol</error-type>
    <error-tag>unknown-attribute</error-tag>
    <error-severity>error</error-severity>
    <error-app-tag>314</error-app-tag>
    <error-message>Unexpected attribute: type.&#13;
</error-message>
    <error-info>
      <bad-attribute>type</bad-attribute>
      <bad-element>close-session</bad-element>
      <error-paras>
        <error-para>type</error-para>
      </error-paras>
    </error-info>
  </rpc-error>
</rpc-reply>
Mon, 05 Sep 2016 10:13:11 rpc.py[line:217] DEBUG Delivering to <ncclient.operations.session.CloseSession object at 0x1035a3510>
Mon, 05 Sep 2016 10:13:11 transport.py[line:1406] DEBUG EOF in transport thread
Mon, 05 Sep 2016 10:13:11 ssh.py[line:553] DEBUG Broke out of main loop, error=SessionCloseError('Unexpected session close',)
Mon, 05 Sep 2016 10:13:11 session.py[line:74] DEBUG dispatching error to <ncclient.operations.rpc.RPCReplyListener object at 0x103718590>
Unexpected attribute: type.

```

**Comment by gothack329** [comment]
Thanks :)

**Comment by gothack329** [comment]
@leopoul ...

**Comment by leopoul** [comment]
If I am not mistaken, I think that your command is invalid. I assume you are trying to get part of the running or candidate config, right? I would go for something like (in Junipers at least for bgp for example - I don't have access to huawei devices atm):
```
with manager.connect("host") as m:
    filter = '<filter><configuration><protocols><bgp/></protocols></configuration></filter>' 
    c = m.get_config(source='running', filter=filter)
```

Could you provide more debug info? I'm curious to see what's the rpc that you send to the device with "m.get(('subtree', xml_template))".

You can raise debug level:
```
import logging

logging.basicConfig(
    level=logging.DEBUG,
)
```

Thanks,
L.

**Comment by gothack329** [comment]
python code is 
```
    template = """
       <vlan xmlns="http://www.huawei.com/netconf/vrp" content-version="1.0" format-version="1.0">
      <vlans>
        <vlan>
          <vlanId/>
          <vlanName/>
        </vlan>
      </vlans>
    </vlan>
    """
    with manager.connect_ssh(host='12.12.12.12',
             port=22,
             username='username',
             password='password',
             hostkey_verify=False,
             device_params={'name': 'huawei'},
             allow_agent=False,
             look_for_keys=False
             ) as m:
        xmldata = m.get(('subtree', template))
```
debug info is:
```
Fri, 09 Sep 2016 13:41:53 session.py[line:48] DEBUG <SSHSession(session, initial daemon)> created: client_capabilities=<dictionary-keyiterator object at 0x103583418>
Fri, 09 Sep 2016 13:41:53 transport.py[line:1406] DEBUG starting thread (client mode): 0x3580c10L
Fri, 09 Sep 2016 13:41:53 transport.py[line:1406] INFO Connected (version 2.0, client -)
Fri, 09 Sep 2016 13:41:53 transport.py[line:1406] DEBUG kex algos:['diffie-hellman-group-exchange-sha256', 'diffie-hellman-group1-sha1', 'ecdh-sha2-nistp521', 'ecdh-sha2-nistp384', 'ecdh-sha2-nistp256', 'diffie-hellman-group-exchange-sha1', 'sm2kep-sha2-nistp256'] server key:['ssh-dss', 'ssh-rsa', 'ecdsa-sha2-nistp521'] client encrypt:['aes256-ctr', 'aes128-ctr', 'aes256-cbc', 'aes128-cbc', 'blowfish-cbc', '3des-cbc'] server encrypt:['aes256-ctr', 'aes128-ctr', 'aes256-cbc', 'aes128-cbc', 'blowfish-cbc', '3des-cbc'] client mac:['hmac-sha2-256', 'hmac-sha2-256-96', 'hmac-sha1', 'hmac-sha1-96'] server mac:['hmac-sha2-256', 'hmac-sha2-256-96', 'hmac-sha1', 'hmac-sha1-96'] client compress:['none', 'zlib'] server compress:['none', 'zlib'] client lang:[''] server lang:[''] kex follows?False
Fri, 09 Sep 2016 13:41:53 transport.py[line:1406] DEBUG Ciphers agreed: local=aes128-ctr, remote=aes128-ctr
Fri, 09 Sep 2016 13:41:53 transport.py[line:1406] DEBUG using kex diffie-hellman-group1-sha1; server key type ssh-rsa; cipher: local aes128-ctr, remote aes128-ctr; mac: local hmac-sha1, remote hmac-sha1; compression: local none, remote none
Fri, 09 Sep 2016 13:41:53 transport.py[line:1406] DEBUG Switch to new keys ...
Fri, 09 Sep 2016 13:41:53 transport.py[line:1406] DEBUG userauth is OK
Fri, 09 Sep 2016 13:41:54 transport.py[line:1406] INFO Authentication (password) successful!
Fri, 09 Sep 2016 13:41:54 channel.py[line:1115] DEBUG [chan 1] Max packet in: 34816 bytes
Fri, 09 Sep 2016 13:41:54 channel.py[line:1115] DEBUG [chan 1] Max packet out: 32768 bytes
Fri, 09 Sep 2016 13:41:54 transport.py[line:1406] INFO Secsh channel 1 opened.
Fri, 09 Sep 2016 13:41:54 channel.py[line:1115] DEBUG [chan netconf-subsystem-1] Sesch channel 1 request ok
Fri, 09 Sep 2016 13:41:54 session.py[line:116] DEBUG installing listener <ncclient.transport.session.HelloHandler object at 0x103587350>
Fri, 09 Sep 2016 13:41:54 session.py[line:153] DEBUG queueing <?xml version="1.0" encoding="UTF-8"?><hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><capabilities><capability>urn:ietf:params:netconf:capability:writable-running:1.0</capability><capability>http://www.huawei.com/netconf/capability/execute-cli/1.0</capability><capability>urn:ietf:params:netconf:capability:rollback-on-error:1.0</capability><capability>urn:liberouter:params:netconf:capability:power-control:1.0</capability><capability>urn:ietf:params:netconf:capability:validate:1.0</capability><capability>urn:ietf:params:netconf:capability:confirmed-commit:1.0</capability><capability>http://www.huawei.com/netconf/capability/active/1.0</capability><capability>urn:ietf:params:netconf:capability:url:1.0?scheme=http,ftp,file,https,sftp</capability><capability>urn:ietf:params:netconf:base:1.0</capability><capability>urn:ietf:params:netconf:base:1.1</capability><capability>http://www.huawei.com/netconf/capability/discard-commit/1.0</capability><capability>urn:ietf:params:netconf:capability:candidate:1.0</capability><capability>urn:ietf:params:netconf:capability:notification:1.0</capability><capability>urn:ietf:params:netconf:capability:xpath:1.0</capability><capability>urn:ietf:params:netconf:capability:startup:1.0</capability><capability>http://www.huawei.com/netconf/capability/action/1.0</capability><capability>urn:ietf:params:netconf:capability:interleave:1.0</capability></capabilities></hello>
Fri, 09 Sep 2016 13:41:54 session.py[line:95] DEBUG starting main loop
Fri, 09 Sep 2016 13:41:54 ssh.py[line:115] DEBUG parsing netconf v1.0
Fri, 09 Sep 2016 13:41:54 session.py[line:67] DEBUG dispatching message to <ncclient.transport.session.HelloHandler object at 0x103587350>: <?xml version="1.0" encoding="UTF-8"?>
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <capabilities>
    <capability>urn:ietf:params:netconf:base:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:writable-running:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:candidate:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:confirmed-commit:1.0</capability>
    <capability>http://www.huawei.com/netconf/capability/discard-commit/1.0</capability>
    <capability>urn:ietf:params:netconf:capability:startup:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:rollback-on-error:1.0</capability>
    <capability>http://www.huawei.com/netconf/capability/sync/1.2</capability>
    <capability>http://www.huawei.com/netconf/capability/sync/1.1</capability>
    <capability>http://www.huawei.com/netconf/capability/sync/1.0</capability>
    <capability>http://www.huawei.com/netconf/capability/exchange/1.0</capability>
    <capability>http://www.huawei.com/netconf/capability/exchange/1.1</capability>
    <capability>http://www.huawei.com/netconf/capability/active/1.0</capability>
    <capability>http://www.huawei.com/netconf/capability/action/1.0</capability>
    <capability>http://www.huawei.com/netconf/capability/execute-cli/1.0</capability>
    <capability>http://www.huawei.com/netconf/capability/update/1.0</capability>
    <capability>http://www.huawei.com/netconf/capability/commit-description/1.0</capability>
    <capability>urn:ietf:params:netconf:capability:notification:1.0</capability>
    <capability>urn:ietf:params:netconf:capability:interleave:1.0</capability>
    <capability>http://www.huawei.com/netconf/vrp/huawei-l3vpn-rm-map?module=huawei-l3vpn-rm-map&amp;revision=2013-01-01</capability>
    <capability>http://www.huawei.com/netconf/vrp/huawei-l3vpn-mpls-map?module=huawei-l3vpn-mpls-map&amp;revision=2013-01-01</capability>
    <capability>http://www.huawei.com/netconf/vrp/huawei-l3vpn-l3vpncomm?module=huawei-l3vpn-l3vpncomm&amp;revision=2013-01-01</capability>
    <capability>http://www.huawei.com/netconf/vrp/huawei-l3vpn-bgpvpnv4?module=huawei-l3vpn-bgpvpnv4&amp;revision=2013-01-01</capability>
    <capability>http://www.huawei.com/netconf/vrp/huawei-l3vpn-bgpvpnbase?module=huawei-l3vpn-bgpvpnbase&amp;revision=2013-01-01</capability>
    <capability>http://www.huawei.com/netconf/vrp/huawei-l3vpn?module=huawei-l3vpn&amp;revision=2013-01-01</capability>
    <capability>http://www.huawei.com/netconf/vrp/huawei-l2vpn-mpls-map?module=huawei-l2vpn-mpls-map&amp;revision=2013-01-01</capability>
    <capability>http://www.huawei.com/netconf/vrp/huawei-l2vpn-l2vpncommon?module=huawei-l2vpn-l2vpncommon&amp;revision=2013-01-01</capability>
    <capability>http://www.huawei.com/netconf/vrp/huawei-l2vpn-l2vpncomm?module=huawei-l2vpn-l2vpncomm&amp;revision=2013-01-01</capability>
    <capability>http://www.huawei.com/netconf/vrp/huawei-l2vpn?module=huawei-l2vpn&amp;revision=2013-01-01</capability>
    <capability>http://www.huawei.com/netconf/vrp/huawei-pub-types?module=huawei-pub-types&amp;revision=2013-01-01</capability>
  </capabilities>
  <session-id>3875</session-id>
</hello>
Fri, 09 Sep 2016 13:41:54 ssh.py[line:520] DEBUG Sending message
Fri, 09 Sep 2016 13:41:54 ssh.py[line:546] DEBUG Sending: <?xml version="1.0" encoding="UTF-8"?><hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><capabilities><capability>urn:ietf:params:netconf:capability:writable-running:1.0</capability><capability>http://www.huawei.com/netconf/capability/execute-cli/1.0</capability><capability>urn:ietf:params:netconf:capability:rollback-on-error:1.0</capability><capability>urn:liberouter:params:netconf:capability:power-control:1.0</capability><capability>urn:ietf:params:netconf:capability:validate:1.0</capability><capability>urn:ietf:params:netconf:capability:confirmed-commit:1.0</capability><capability>http://www.huawei.com/netconf/capability/active/1.0</capability><capability>urn:ietf:params:netconf:capability:url:1.0?scheme=http,ftp,file,https,sftp</capability><capability>urn:ietf:params:netconf:base:1.0</capability><capability>urn:ietf:params:netconf:base:1.1</capability><capability>http://www.huawei.com/netconf/capability/discard-commit/1.0</capability><capability>urn:ietf:params:netconf:capability:candidate:1.0</capability><capability>urn:ietf:params:netconf:capability:notification:1.0</capability><capability>urn:ietf:params:netconf:capability:xpath:1.0</capability><capability>urn:ietf:params:netconf:capability:startup:1.0</capability><capability>http://www.huawei.com/netconf/capability/action/1.0</capability><capability>urn:ietf:params:netconf:capability:interleave:1.0</capability></capabilities></hello>]]>]]>
Fri, 09 Sep 2016 13:41:54 session.py[line:128] DEBUG discarding listener <ncclient.transport.session.HelloHandler object at 0x103587350>
Fri, 09 Sep 2016 13:41:54 session.py[line:108] INFO initialized: session-id=3875 | server_capabilities=<dictionary-keyiterator object at 0x103583730>
Fri, 09 Sep 2016 13:41:54 session.py[line:116] DEBUG installing listener <ncclient.operations.rpc.RPCReplyListener object at 0x103587350>
Fri, 09 Sep 2016 13:41:54 rpc.py[line:314] INFO Requesting 'Get'
Fri, 09 Sep 2016 13:41:54 session.py[line:153] DEBUG queueing <?xml version="1.0" encoding="UTF-8"?><rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:d21984dd-b398-4409-b046-41f8c555b0e9"><get><filter type="subtree"><vlan xmlns="http://www.huawei.com/netconf/vrp" content-version="1.0" format-version="1.0">
      <vlans>
        <vlan>
          <vlanId/>
          <vlanName/>
        </vlan>
      </vlans>
    </vlan></filter></get></rpc>
Fri, 09 Sep 2016 13:41:54 rpc.py[line:321] DEBUG Sync request, will wait for timeout=30
Fri, 09 Sep 2016 13:41:54 ssh.py[line:520] DEBUG Sending message
Fri, 09 Sep 2016 13:41:54 ssh.py[line:546] DEBUG Sending: <?xml version="1.0" encoding="UTF-8"?><rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:d21984dd-b398-4409-b046-41f8c555b0e9"><get><filter type="subtree"><vlan xmlns="http://www.huawei.com/netconf/vrp" content-version="1.0" format-version="1.0">
      <vlans>
        <vlan>
          <vlanId/>
          <vlanName/>
        </vlan>
      </vlans>
    </vlan></filter></get></rpc>]]>]]>
Fri, 09 Sep 2016 13:41:54 ssh.py[line:512] DEBUG Selecting netconf:base:1.0 for encoding
Fri, 09 Sep 2016 13:41:54 ssh.py[line:115] DEBUG parsing netconf v1.0
Fri, 09 Sep 2016 13:41:54 session.py[line:67] DEBUG dispatching message to <ncclient.operations.rpc.RPCReplyListener object at 0x103587350>: <?xml version="1.0" encoding="UTF-8"?>
<rpc-reply message-id="urn:uuid:d21984dd-b398-4409-b046-41f8c555b0e9" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <data>
    <vlan xmlns="http://www.huawei.com/netconf/vrp" format-version="1.0" content-version="1.0">
      <vlans>
        <vlan>
          <vlanId>1</vlanId>
          <vlanName></vlanName>
        </vlan>
        <vlan>
          <vlanId>10</vlanId>
          <vlanName></vlanName>
        </vlan>
        <vlan>
          <vlanId>20</vlanId>
          <vlanName></vlanName>
        </vlan>
        <vlan>
          <vlanId>100</vlanId>
          <vlanName></vlanName>
        </vlan>
        <vlan>
          <vlanId>200</vlanId>
          <vlanName></vlanName>
        </vlan>
      </vlans>
    </vlan>
  </data>
</rpc-reply>
Fri, 09 Sep 2016 13:41:54 rpc.py[line:217] DEBUG Delivering to <ncclient.operations.retrieve.Get object at 0x10314a090>
Fri, 09 Sep 2016 13:41:54 rpc.py[line:314] INFO Requesting 'CloseSession'
Fri, 09 Sep 2016 13:41:54 session.py[line:153] DEBUG queueing <?xml version="1.0" encoding="UTF-8"?><rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:f5c72e9d-51ff-4299-b2f7-8b74af44ca37"><close-session type="subtree"/></rpc>
Fri, 09 Sep 2016 13:41:54 rpc.py[line:321] DEBUG Sync request, will wait for timeout=30
Fri, 09 Sep 2016 13:41:54 ssh.py[line:520] DEBUG Sending message
Fri, 09 Sep 2016 13:41:54 ssh.py[line:546] DEBUG Sending: <?xml version="1.0" encoding="UTF-8"?><rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:f5c72e9d-51ff-4299-b2f7-8b74af44ca37"><close-session type="subtree"/></rpc>]]>]]>
Fri, 09 Sep 2016 13:41:54 ssh.py[line:512] DEBUG Selecting netconf:base:1.0 for encoding
Fri, 09 Sep 2016 13:41:54 ssh.py[line:115] DEBUG parsing netconf v1.0
Fri, 09 Sep 2016 13:41:54 session.py[line:67] DEBUG dispatching message to <ncclient.operations.rpc.RPCReplyListener object at 0x103587350>: <?xml version="1.0" encoding="UTF-8"?>
<rpc-reply message-id="urn:uuid:f5c72e9d-51ff-4299-b2f7-8b74af44ca37" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <rpc-error>
    <error-type>protocol</error-type>
    <error-tag>unknown-attribute</error-tag>
    <error-severity>error</error-severity>
    <error-app-tag>314</error-app-tag>
    <error-message>Unexpected attribute: type.&#13;
</error-message>
    <error-info>
      <bad-attribute>type</bad-attribute>
      <bad-element>close-session</bad-element>
      <error-paras>
        <error-para>type</error-para>
      </error-paras>
    </error-info>
  </rpc-error>
</rpc-reply>
Fri, 09 Sep 2016 13:41:54 rpc.py[line:217] DEBUG Delivering to <ncclient.operations.session.CloseSession object at 0x10314a090>
Fri, 09 Sep 2016 13:41:55 transport.py[line:1406] DEBUG EOF in transport thread
Fri, 09 Sep 2016 13:41:55 ssh.py[line:553] DEBUG Broke out of main loop, error=SessionCloseError('Unexpected session close',)
Fri, 09 Sep 2016 13:41:55 session.py[line:74] DEBUG dispatching error to <ncclient.operations.rpc.RPCReplyListener object at 0x103587350>
Traceback (most recent call last):
  File "netconf.py", line 95, in <module>
    test()
  File "netconf.py", line 92, in test
    xmldata = m.get(('subtree', template))
  File "/anaconda/lib/python2.7/site-packages/ncclient/manager.py", line 213, in __exit__
    self.close_session()
  File "/anaconda/lib/python2.7/site-packages/ncclient/manager.py", line 161, in wrapper
    return self.execute(op_cls, *args, **kwds)
  File "/anaconda/lib/python2.7/site-packages/ncclient/manager.py", line 231, in execute
    raise_mode=self._raise_mode).request(*args, **kwds)
  File "/anaconda/lib/python2.7/site-packages/ncclient/operations/session.py", line 28, in request
    return self._request(new_ele("close-session"))
  File "/anaconda/lib/python2.7/site-packages/ncclient/operations/rpc.py", line 337, in _request
    raise self._reply.error
ncclient.operations.rpc.RPCError: Unexpected attribute: type.


```

Thanks
