### ISSUE TITLE
Unexpected connection closure 

### ISSUE THREAD

**Issue by fanttazio** [ncclient/ncclient#175]
Hi, I'm having issue working with the package. I'm trying to connect to below device on Cisco VIRL:

`Cisco IOS Software [Denali], CSR1000V Software (X86_64_LINUX_IOSD-UNIVERSALK9-M), Version 16.3.2, RELEASE SOFTWARE (fc4)`

I'm running basic Python code to get NetConf capabilities:

```
import logging
from ncclient import manager
import sys


# the variables below assume the user is requesting access to a
# device running in VIRL 
# use the IP address or hostname of your device
HOST = '10.131.129.238'
# use the NETCONF port for your Nexus device
PORT = 22
# use the user credentials for your Nexus device
USER = 'cisco'
PASS = 'cisco'


# create a main() method
def main():
    logging.basicConfig(level=logging.DEBUG)
    """Main method that prints NETCONF capabilities of remote device."""
    with manager.connect(host=HOST, port=PORT, username=USER, password=PASS,
                         hostkey_verify=False, device_params={'name': 'csr'},
                         look_for_keys=False, allow_agent=False) as m:

        # print all NETCONF capabilities
        print('***Here are the Remote Devices Capabilities***')
        for capability in m.server_capabilities:
            print(capability)

if __name__ == '__main__':
    sys.exit(main())

```

But connection gets closed unexpected:

```
bash-3.2$ python3 /Users/fanttazio/CiscoDevNet/NetConf.py
DEBUG:ncclient.transport.session:<SSHSession(session, initial daemon)> created: client_capabilities=<dict_keyiterator object at 0x10d43e728>
DEBUG:ncclient.transport.ssh:starting thread (client mode): 0xd443c50
DEBUG:ncclient.transport.ssh:Local version/idstring: SSH-2.0-paramiko_2.1.1
DEBUG:ncclient.transport.ssh:Remote version/idstring: SSH-2.0-Cisco-1.25
INFO:ncclient.transport.ssh:Connected (version 2.0, client Cisco-1.25)
DEBUG:ncclient.transport.ssh:kex algos:['diffie-hellman-group-exchange-sha1', 'diffie-hellman-group14-sha1'] server key:['ssh-rsa'] client encrypt:['aes128-ctr'
, 'aes192-ctr', 'aes256-ctr', 'aes128-cbc', '3des-cbc', 'aes192-cbc', 'aes256-cbc'] server encrypt:['aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-cbc', '3de
s-cbc', 'aes192-cbc', 'aes256-cbc'] client mac:['hmac-sha1', 'hmac-sha1-96'] server mac:['hmac-sha1', 'hmac-sha1-96'] client compress:['none'] server compress:[
'none'] client lang:[''] server lang:[''] kex follows?False
DEBUG:ncclient.transport.ssh:Kex agreed: diffie-hellman-group14-sha1
DEBUG:ncclient.transport.ssh:Cipher agreed: aes128-ctr
DEBUG:ncclient.transport.ssh:MAC agreed: hmac-sha1-96
DEBUG:ncclient.transport.ssh:Compression agreed: none
DEBUG:ncclient.transport.ssh:kex engine KexGroup14 specified hash_algo <built-in function openssl_sha1>
DEBUG:ncclient.transport.ssh:Switch to new keys ...
DEBUG:ncclient.transport.ssh:userauth is OK
INFO:ncclient.transport.ssh:Authentication (password) successful!
DEBUG:ncclient.transport.ssh:[chan 0] Max packet in: 32768 bytes
DEBUG:ncclient.transport.ssh:[chan 0] Max packet out: 4096 bytes
DEBUG:ncclient.transport.ssh:Secsh channel 0 opened.
DEBUG:ncclient.transport.ssh:[chan netconf-subsystem-0] Sesch channel 0 request ok
DEBUG:ncclient.transport.session:installing listener <ncclient.transport.session.NotificationHandler object at 0x10dad2cf8>
DEBUG:ncclient.transport.session:installing listener <ncclient.transport.session.HelloHandler object at 0x10dad2c50>
DEBUG:ncclient.transport.session:queueing <?xml version="1.0" encoding="UTF-8"?><nc:hello xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0"><nc:capabilities><n
c:capability>urn:ietf:params:netconf:base:1.0</nc:capability><nc:capability>urn:ietf:params:netconf:base:1.1</nc:capability><nc:capability>urn:ietf:params:netco
nf:capability:writable-running:1.0</nc:capability><nc:capability>urn:ietf:params:netconf:capability:candidate:1.0</nc:capability><nc:capability>urn:ietf:params:
netconf:capability:confirmed-commit:1.0</nc:capability><nc:capability>urn:ietf:params:netconf:capability:rollback-on-error:1.0</nc:capability><nc:capability>urn
:ietf:params:netconf:capability:startup:1.0</nc:capability><nc:capability>urn:ietf:params:netconf:capability:url:1.0?scheme=http,ftp,file,https,sftp</nc:capabil
ity><nc:capability>urn:ietf:params:netconf:capability:validate:1.0</nc:capability><nc:capability>urn:ietf:params:netconf:capability:xpath:1.0</nc:capability><nc
:capability>urn:ietf:params:netconf:capability:notification:1.0</nc:capability><nc:capability>urn:liberouter:params:netconf:capability:power-control:1.0</nc:cap
ability><nc:capability>urn:ietf:params:netconf:capability:interleave:1.0</nc:capability></nc:capabilities></nc:hello>
DEBUG:ncclient.transport.session:starting main loop
DEBUG:ncclient.transport.ssh:Sending message
DEBUG:ncclient.transport.ssh:Sending: <?xml version="1.0" encoding="UTF-8"?><nc:hello xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0"><nc:capabilities><nc:ca
pability>urn:ietf:params:netconf:base:1.0</nc:capability><nc:capability>urn:ietf:params:netconf:base:1.1</nc:capability><nc:capability>urn:ietf:params:netconf:c
apability:writable-running:1.0</nc:capability><nc:capability>urn:ietf:params:netconf:capability:candidate:1.0</nc:capability><nc:capability>urn:ietf:params:netc
onf:capability:confirmed-commit:1.0</nc:capability><nc:capability>urn:ietf:params:netconf:capability:rollback-on-error:1.0</nc:capability><nc:capability>urn:iet
f:params:netconf:capability:startup:1.0</nc:capability><nc:capability>urn:ietf:params:netconf:capability:url:1.0?scheme=http,ftp,file,https,sftp</nc:capability>
<nc:capability>urn:ietf:params:netconf:capability:validate:1.0</nc:capability><nc:capability>urn:ietf:params:netconf:capability:xpath:1.0</nc:capability><nc:cap
ability>urn:ietf:params:netconf:capability:notification:1.0</nc:capability><nc:capability>urn:liberouter:params:netconf:capability:power-control:1.0</nc:capabil
ity><nc:capability>urn:ietf:params:netconf:capability:interleave:1.0</nc:capability></nc:capabilities></nc:hello>]]>]]>
ERROR:ncclient.transport.ssh:Socket exception: Connection reset by peer (54)
DEBUG:ncclient.transport.ssh:Broke out of main loop, error=SessionCloseError('Unexpected session close',)
DEBUG:ncclient.transport.session:dispatching error to <ncclient.transport.session.HelloHandler object at 0x10dad2c50>
DEBUG:ncclient.transport.session:dispatching error to <ncclient.transport.session.NotificationHandler object at 0x10dad2cf8>
DEBUG:ncclient.transport.session:discarding listener <ncclient.transport.session.HelloHandler object at 0x10dad2c50>
Traceback (most recent call last):
  File "/Users/fanttazio/CiscoDevNet/NetConf.py", line 31, in <module>
    sys.exit(main())
  File "/Users/fanttazio/CiscoDevNet/NetConf.py", line 23, in main
    look_for_keys=False, allow_agent=False) as m:
  File "/usr/local/lib/python3.6/site-packages/ncclient/manager.py", line 154, in connect
    return connect_ssh(*args, **kwds)
  File "/usr/local/lib/python3.6/site-packages/ncclient/manager.py", line 119, in connect_ssh
    session.connect(*args, **kwds)
  File "/usr/local/lib/python3.6/site-packages/ncclient/transport/ssh.py", line 433, in connect
    self._post_connect()
  File "/usr/local/lib/python3.6/site-packages/ncclient/transport/session.py", line 107, in _post_connect
    raise error[0]
  File "/usr/local/lib/python3.6/site-packages/ncclient/transport/ssh.py", line 538, in run
    raise SessionCloseError(self._buffer.getvalue())
ncclient.transport.errors.SessionCloseError: Unexpected session close
```

Any idea what's the issue here?

I'm running Pyhton3.6 and ncclient (0.5.3)

**Comment by einarnn** [comment]
Assuming you have configured the new netconf-yang agent, try port 830 instead of 22.

Cheers,

Einar

**Comment by fanttazio** [comment]
Thank you Einar. Looks like you have to specifically enable NetConf over SSH on Cisco IOS-XE:

#netconf ssh

That solved the problem. I could still use port 22.

**Comment by einarnn** [comment]
Please be aware that with that config you are enabling the netconf 1.0 agent that does not support YANG. To enable netconf/yang on 16.3.1 and later you need to configure:

netconf-yang

Cheers,

Einar

**Comment by einarnn** [comment]
See:

http://www.cisco.com/c/en/us/td/docs/switches/lan/catalyst3850/software/release/16-3/configuration_guide/b_163_consolidated_3850_cg/b_163_consolidated_3850_cg_chapter_010100000.html#d476609e173a1635

...for enabling netconf/yang.

Cheers,

Einar

**Comment by fanttazio** [comment]
Awesome. I thought I was missing something as I wasn't getting YANG
replies. It's working now. Cheers!

**Comment by rajvijay68** [comment]
In my case,
Just using port 830 helped fix this issue.
