### ISSUE TITLE
copy_config does not work

### ISSUE THREAD

**Issue by manoj-nair** [ncclient/ncclient#180]
Hi,

I tried the first example mentioned in the ncclient documentation and got the following error:

**Example tried:**

#! /usr/bin/python

import sys, os, warnings
warnings.simplefilter("ignore", DeprecationWarning)
from ncclient import manager

def get_running_config(host, user, pwd):
    with manager.connect(host=host, port=830, username=user, password=pwd, hostkey_verify=False,allow_agent=False,look_for_keys=False) as m:
        #assert(":url" in m.server_capabilities)
        with m.locked("running"):
            m.copy_config(source="running", target="file:///tmp/new_checkpoint.conf")

if __name__ == '__main__':
    get_running_config('localhost', 'jack','xxxxxxx');

**Error seen at client side:**
Traceback (most recent call last):
  File "./my_get.py", line 14, in <module>
    get_running_config('localhost', 'jack','xxxxxxx');
  File "./my_get.py", line 11, in get_running_config
    m.copy_config(source="running", target="file:///tmp/new_checkpoint.conf") 
  File "build/bdist.linux-x86_64/egg/ncclient/manager.py", line 162, in wrapper
  File "build/bdist.linux-x86_64/egg/ncclient/manager.py", line 232, in execute
  File "build/bdist.linux-x86_64/egg/ncclient/operations/edit.py", line 99, in request
  File "build/bdist.linux-x86_64/egg/ncclient/operations/rpc.py", line 337, in _request
ncclient.operations.rpc.RPCError: NULL pointer

**Error seen at NETCONF server:**

[rpc-error]
  [error-type]protocol[/error-type]
  [error-tag]operation-failed[/error-tag]
  [error-severity]error[/error-severity]
  [error-app-tag]internal-error[/error-app-tag]
  [error-path]/nc:rpc/nc:copy-config/nc:target/nc:url[/error-path]
  [error-message xml:lang="en"]NULL pointer[/error-message]
  [error-info]
   [bad-value]file:///tmp/new_checkpoint.conf[/bad-value]
   [error-number]2[/error-number]
  [/error-info]
 [/rpc-error]

**Environment:**
Ubuntu 14.04
ncclient version 0.5.3
Netconf server has URL capabilities
The nc01, nc02 and nc03 examples work fine

**Expected behavior:**
The running configuration should be fetched from server and saved to local file-system at /tmp/new_checkpoint.conf

Please let me know how to make this work.

Thanks,
Manoj

**Comment by manoj-nair** [comment]
**Found the problem:**
The file gets stored at the Netconf server's data directory, which did not have a 'tmp' subdirectory.
Changing the copy_config target to "file:///new_checkpoint.conf" worked.
