### ISSUE TITLE
Exception on terminating a session

### ISSUE THREAD

**Issue by michaelsiuda** [ncclient/ncclient#214]
Hi,

I'm hitting the following exception quite regularly, with hit rate around 10%.
```
Exception in thread session (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/local/lib/python2.7/dist-packages/ncclient/transport/ssh.py", line 575, in run
  File "/usr/local/lib/python2.7/dist-packages/ncclient/transport/ssh.py", line 312, in close
  File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 699, in close
  File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 1662, in stop_thread
  File "/usr/lib/python2.7/threading.py", line 951, in join
  File "/usr/lib/python2.7/threading.py", line 364, in wait
<type 'exceptions.ValueError'>: list.remove(x): x not in list
```

Here's my code:
```
def main():
    try:
        with manager.connect(
            host="localhost",
            port=2022,
            username=XXX
            password=XXX
            timeout=5,
            hostkey_verify=False,
            look_for_keys=False,
            allow_agent=False,
        ) as connection:
           # do stuff
    except ncclient.NCClientError:
        print("Error")
```

I'm using ncclient version 0.5.3 on Ubuntu 16.04.

AFAICS, the problem is that ncclient is maintaining its own transport thread in addition to the transport thread used by paramiko. 

While paramiko is well behaved and has logic to ensure that it closes all its threads before it exits, ncclient has no such logic and relies on a transport failure to signal the close of the thread and to tidy up synchronously.  What I believe needs to happen is that ncclient should wait for the thread to close.  For example, inside SSHSession.close():
```
       while self.is_alive() and (self is not threading.current_thread()):
            self.join(10)
```

I've tested that with this code change I'm not able to hit the exception anymore.

Are you happy with the fix?  Would you like me to submit a pull request?

Thanks,
Michael

**Comment by einarnn** [comment]
Addressed in #268.
