### ISSUE TITLE
support hua get method？

### ISSUE THREAD

**Issue by holinhot** [ncclient/ncclient#219]
Hi,

I want to use get method to get prefix list

```
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
  <get>
    <filter type="subtree">
      <rtp xmlns="http://www.huawei.com/netconf/vrp" content-version="1.0" format-version="1.0">
        <prefixFilters>
          <prefixFilter>
            <name/>
            <permitCnt/>
            <denyCnt/>
          </prefixFilter>
        </prefixFilters>
      </rtp>
    </filter>
  </get>
</rpc>
```

xml = """<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
  <get>
    <filter type="subtree">
      <rtp xmlns="http://www.huawei.com/netconf/vrp" content-version="1.0" format-version="1.0">
        <prefixFilters>
          <prefixFilter>
            <name/>
            <permitCnt/>
            <denyCnt/>
          </prefixFilter>
        </prefixFilters>
      </rtp>
    </filter>
  </get>
</rpc>"""

```
def get_config_huawei(host, user, password):
    with manager.connect(host=host, port=22, username=user, password=password, hostkey_verify=False,
                         device_params={'name': 'huawei'}) as m:
        c = m.get(config=xml).data_xml
        print(c)

        with open("%s.xml" % host, 'w') as f:
            f.write(c)


get_config_huawei(host,user,password)
```

Traceback (most recent call last):
  File "/Users/louis/PycharmProjects/py_netconf/app.py", line 79, in <module>
    get_config_huawei(host,user,password)
  File "/Users/louis/PycharmProjects/py_netconf/app.py", line 72, in get_config_huawei
    c = m.get(config=xml).data_xml
  File "/usr/local/lib/python3.6/site-packages/ncclient/manager.py", line 162, in wrapper
    return self.execute(op_cls, *args, **kwds)
  File "/usr/local/lib/python3.6/site-packages/ncclient/manager.py", line 232, in execute
    raise_mode=self._raise_mode).request(*args, **kwds)
TypeError: request() got an unexpected keyword argument 'config'

thanks

**Comment by holinhot** [comment]
I test
xml = """<get>
    <filter type="subtree">
      <rtp xmlns="http://www.huawei.com/netconf/vrp" content-version="1.0" format-version="1.0">
        <prefixFilters>
          <prefixFilter>
            <name/>
            <permitCnt/>
            <denyCnt/>
          </prefixFilter>
        </prefixFilters>
      </rtp>
    </filter>
  </get>
"""


def connect(host, port, user, password):
    conn = manager.connect(host=host,
            port=port,
            username=user,
            password=password,
            timeout=10,
            device_params = {'name':'junos'},
            hostkey_verify=False)

    rpc = """
    <get-chassis-inventory>
        <detail/>
    </get-chassis-inventory>"""

    result = conn.rpc(xml)
    print(result)


Traceback (most recent call last):
  File "/Users/louis/PycharmProjects/py_netconf/app.py", line 51, in <module>
    connect(host=host,port=22, user=user,password=password)
  File "/Users/louis/PycharmProjects/py_netconf/app.py", line 44, in connect
    result = conn.rpc(xml)
  File "/usr/local/lib/python3.6/site-packages/ncclient/manager.py", line 172, in wrapper
    return self.execute(op_cls, *args, **kwds)
  File "/usr/local/lib/python3.6/site-packages/ncclient/manager.py", line 232, in execute
    raise_mode=self._raise_mode).request(*args, **kwds)
  File "/usr/local/lib/python3.6/site-packages/ncclient/operations/third_party/juniper/rpc.py", line 44, in request
    return self._request(rpc)
  File "/usr/local/lib/python3.6/site-packages/ncclient/operations/rpc.py", line 339, in _request
    return NCElement(self._reply, self._device_handler.transform_reply())
  File "/usr/local/lib/python3.6/site-packages/ncclient/xml_.py", line 153, in __init__
    self.__doc = self.remove_namespaces(self.__result)
  File "/usr/local/lib/python3.6/site-packages/ncclient/xml_.py", line 201, in remove_namespaces
    self.__root = etree.fromstring(str(self.__transform(etree.parse(StringIO(str(rpc_reply))))))
  File "src/lxml/etree.pyx", line 3444, in lxml.etree.parse (src/lxml/etree.c:83185)
  File "src/lxml/parser.pxi", line 1851, in lxml.etree._parseDocument (src/lxml/etree.c:120981)
  File "src/lxml/parser.pxi", line 1866, in lxml.etree._parseMemoryDocument (src/lxml/etree.c:121191)
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.

**Comment by einarnn** [comment]
Please take a look at the docs for ncclient:

http://ncclient.readthedocs.io/en/latest/

Cheers,

Einar
