### ISSUE TITLE
import bcrypt errors out when trying " import ncclient from manager"

### ISSUE THREAD

**Issue by umeshshetty** [ncclient/ncclient#235]
Team,
New to ncclient and not sure if this has been answered before(did not find matches). Need some advice on how I could solve this. Thanks in advance.

>>> from ncclient import manager

Traceback (most recent call last):
  File "<pyshell#91>", line 1, in <module>
    from ncclient import manager
  File "C:\Python27\lib\site-packages\ncclient\manager.py", line 22, in <module>
    from ncclient import operations
  File "C:\Python27\lib\site-packages\ncclient\operations\__init__.py", line 16, in <module>
    from ncclient.operations.rpc import RPC, RPCReply, RPCError, RaiseMode
  File "C:\Python27\lib\site-packages\ncclient\operations\rpc.py", line 20, in <module>
    from ncclient.transport import SessionListener
  File "C:\Python27\lib\site-packages\ncclient\transport\__init__.py", line 18, in <module>
    from ncclient.transport.ssh import SSHSession
  File "C:\Python27\lib\site-packages\ncclient\transport\ssh.py", line 26, in <module>
    import paramiko
  File "C:\Python27\lib\site-packages\paramiko\__init__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "C:\Python27\lib\site-packages\paramiko\transport.py", line 57, in <module>
    from paramiko.ed25519key import Ed25519Key
  File "C:\Python27\lib\site-packages\paramiko\ed25519key.py", line 17, in <module>
    **import bcrypt**
  File "C:\Python27\lib\site-packages\bcrypt\__init__.py", line 25, in <module>
    from bcrypt import _bcrypt
ImportError: DLL load failed: %1 is not a valid Win32 application.
>>>

**Comment by einarnn** [comment]
Most ncclient users are currently on macOS or Linux. This issue has not been reported before.

Have you found a workaround?

**Comment by einarnn** [comment]
@umeshshetty, since there has been no further information on this thread I am assuming it is no longer an active issue. Please feel free to reopen if there is still a problem.
