### ISSUE TITLE
<config> tag shall use nc prefix?

### ISSUE THREAD

**Issue by ctrl-l** [ncclient/ncclient#251]
Hello.
### Brief
I guess  `<config>` tag shall use nc prefix, because "nc:edit-config" "nc:target" all have "nc" prefix, but "config" doesn't. You had an issue(https://github.com/ncclient/ncclient/issues/56) about it, but there wasn't any logs attached.

### Details
I try to send edit-config message to sysrepo(latest version) using ncclient(0.6).
<details><summary>Client code</summary>
<p>

```python
#! /usr/bin/env python

import sys, os, warnings
warnings.simplefilter("ignore", DeprecationWarning)
from ncclient import manager

def nc_edit_config(con):
    xml = '''
        <config>
            <interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
                <interface>
                    <name>eth0</name>
                    <enabled>false</enabled>
                </interface>
            </interfaces>
        </config>
        '''
    ret = con.edit_config(target='candidate', config=xml)
    print("Success? {}". format(ret.ok))


def main():
    with manager.connect(host='localhost', port=830, username='netconf',
                         password='netconf', hostkey_verify=False) as nc_con:
        nc_edit_config(nc_con)

if __name__== "__main__":
    main()
```

</p>
</details>

<details><summary>Client output</summary>
<p>

```
> python ncclient_err_example.py
Traceback (most recent call last):
  File "ncclient_err_example.py", line 27, in <module>
    main()
  File "ncclient_err_example.py", line 24, in main
    nc_edit_config(nc_con)
  File "ncclient_err_example.py", line 18, in nc_edit_config
    ret = con.edit_config(target='candidate', config=xml)
  File "/home/user/.local/lib/python3.6/site-packages/ncclient/manager.py", line 170, in wrapper
    return self.execute(op_cls, *args, **kwds)
  File "/home/user/.local/lib/python3.6/site-packages/ncclient/manager.py", line 240, in execute
    raise_mode=self._raise_mode).request(*args, **kwds)
  File "/home/user/.local/lib/python3.6/site-packages/ncclient/operations/edit.py", line 67, in request
    return self._request(node)
  File "/home/user/.local/lib/python3.6/site-packages/ncclient/operations/rpc.py", line 336, in _request
    raise self._reply.error
ncclient.operations.rpc.RPCError: Missing element's "namespace".
```

</p>
</details>

#### Message from client

```xml
<?xml version="1.0" encoding="UTF-8"?>
<nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:6c90a1b4-5917-4904-8f6d-e69ddd48dd38">
	<nc:edit-config>
		<nc:target><nc:candidate/></nc:target>
		<config>
			<interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
				<interface>
					<name>eth0</name>
					<enabled>false</enabled>
				</interface>
			</interfaces>
		</config>
	</nc:edit-config>
</nc:rpc>
```

#### Server error
```
ERROR: Missing element's "namespace". (/nc:rpc/nc:edit-config/config)
```

I am new to NETCONF, at first i've sent bugreport to sysrepo https://github.com/CESNET/libyang/issues/535. The answer was that it's ncclient issue, i think they are right. Quote from their answer:

>  The error says that /nc:rpc/nc:edit-config/config element does not have a namespace. Looking at the received message, you see that the config element really does not have a namespace, it would need to be nc:config to work. Without the prefix it uses the parent's namespace which is none in your case.

**Comment by jwwilcox** [comment]
You need to put `<config>` in the NETCONF namespace. The easiest way to do this is to set it as the default namespace on that node, like this:

```
def nc_edit_config(con):
    xml = '''
        <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
            <interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
...
```

**Comment by ctrl-l** [comment]
Yes, it works with.
```
<config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
```
Thank you. I'll close this issue.
