### ISSUE TITLE
Edit-config on Huawei CE8850 failes

### ISSUE THREAD

**Issue by horseinthesky** [ncclient/ncclient#289]
Hello.

**UPDATE**
Here is a simple script to edit l2 interface on Huawei CE8850 DC switch
```
from ncclient import manager
from getpass import getuser
# import logging
# import sys
# logging.basicConfig(level=logging.DEBUG,
#                     format='%(asctime)s %(levelname)s: %(message)s',
#                     stream=sys.stdout)

conn = manager.connect(
    host='cloud-netlab-myt-6s253.yndx.net',
    port=22,
    timeout=5,
    username=getuser(),
    device_params={'name': 'huawei'},
    hostkey_verify=False
)

payload = '''
    <config xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
      <ethernet xmlns="http://www.huawei.com/netconf/vrp/huawei-ethernet">
        <ethernetIfs>
          <ethernetIf>
            <ifName>100GE1/0/1:4</ifName>
            <l2Enable>enable</l2Enable>
            <l2Attribute>
              <linkType>trunk</linkType>
              <pvid>106</pvid>
              <trunkVlans>4,5,6,104,106</trunkVlans>
              <taggedPacketDiscard>false</taggedPacketDiscard>
              <portBridgEnable>false</portBridgEnable>
            </l2Attribute>
          </ethernetIf>
        </ethernetIfs>
      </ethernet>
    </config>
'''

conn.edit_config(config=payload, target='running')
```

And it failes with:
```
Traceback (most recent call last):
  File "test.py", line 41, in <module>
    conn.edit_config(config=payload, target='running')
  File "/usr/local/lib/python3.6/dist-packages/ncclient/manager.py", line 216, in execute
    raise_mode=self._raise_mode).request(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/ncclient/operations/edit.py", line 67, in request
    return self._request(node)
  File "/usr/local/lib/python3.6/dist-packages/ncclient/operations/rpc.py", line 341, in _request
    raise self._reply.error
ncclient.operations.rpc.RPCError: ethernet has invalid namespace: http://www.huawei.com/netconf/vrp/huawei-ethernet.
```

If i turn on the logging it's clear that it is CE who can't understand RPC
```
2018-10-11 15:33:45,944 DEBUG: [host cloud-netlab-myt-6s253.yndx.net session-id 43037] Sending message
2018-10-11 15:33:45,944 INFO: [host cloud-netlab-myt-6s253.yndx.net session-id 43037] Sending:

#795
<?xml version="1.0" encoding="UTF-8"?><rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:cfc85403-0c0e-43a7-8975-1e4933168794"><edit-config><target><running/></target><config>
      <ethernet xmlns="http://www.huawei.com/netconf/vrp/huawei-ethernet">
        <ethernetIfs>
          <ethernetIf>
            <ifName>100GE1/0/1:4</ifName>
            <l2Enable>enable</l2Enable>
            <l2Attribute>
              <linkType>trunk</linkType>
              <pvid>106</pvid>
              <trunkVlans>4,5,6,104,106</trunkVlans>
              <taggedPacketDiscard>false</taggedPacketDiscard>
              <portBridgEnable>false</portBridgEnable>
            </l2Attribute>
          </ethernetIf>
        </ethernetIfs>
      </ethernet>
    </config></edit-config></rpc>
##

2018-10-11 15:33:45,953 DEBUG: [host cloud-netlab-myt-6s253.yndx.net session-id 43037] _parse11: starting
2018-10-11 15:33:45,953 DEBUG: [host cloud-netlab-myt-6s253.yndx.net session-id 43037] _parse11: working with buffer of 829 bytes
2018-10-11 15:33:45,953 DEBUG: [host cloud-netlab-myt-6s253.yndx.net session-id 43037] _parse11: matching from 0 bytes from start of buffer
2018-10-11 15:33:45,953 DEBUG: [host cloud-netlab-myt-6s253.yndx.net session-id 43037] _parse11: regular expression start=0, end=6
2018-10-11 15:33:45,953 DEBUG: [host cloud-netlab-myt-6s253.yndx.net session-id 43037] _parse11: found chunk delimiter
2018-10-11 15:33:45,953 DEBUG: [host cloud-netlab-myt-6s253.yndx.net session-id 43037] _parse11: chunk size 819 bytes
2018-10-11 15:33:45,954 DEBUG: [host cloud-netlab-myt-6s253.yndx.net session-id 43037] _parse11: appending 819 bytes
2018-10-11 15:33:45,954 DEBUG: [host cloud-netlab-myt-6s253.yndx.net session-id 43037] _parse11: fragment = "<?xml version="1.0" encoding="UTF-8"?>
<rpc-reply message-id="urn:uuid:cfc85403-0c0e-43a7-8975-1e4933168794" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <rpc-error>
    <error-type>protocol</error-type>
    <error-tag>unknown-namespace</error-tag>
    <error-severity>error</error-severity>
    <error-app-tag>319</error-app-tag>
    <error-message>ethernet has invalid namespace: http://www.huawei.com/netconf/vrp/huawei-ethernet.&#13;
</error-message>
    <error-info>
      <bad-element>ethernet</bad-element>
      <bad-namespace>http://www.huawei.com/netconf/vrp/huawei-ethernet</bad-namespace>
      <error-paras>
        <error-para>ethernet</error-para>
        <error-para>http://www.huawei.com/netconf/vrp/huawei-ethernet</error-para>
      </error-paras>
    </error-info>
  </rpc-error>
</rpc-reply>
"
```

##### SOLUTION
Th problem is CE is sending 
`<capability>urn:ietf:params:netconf:base:1.1</capability>`
capability but in reality it doesn't work with 1.1 chunk framing.

The solution is to use `huaweiyang` option in `device_params`:
```
conn = manager.connect(
    host='cloud-netlab-myt-6s253.yndx.net',
    port=22,
    timeout=5,
    username=getuser(),
    device_params={'name': 'huaweiyang'},
    hostkey_verify=False
)
```
whith tell `ncclient` to use version 1.0 with the device even it tells it can use 1.1

Now we can see `ncclient` is using 1.0 chunk framing `]]>]]>` for communication
```
2018-10-11 14:37:28,282 DEBUG: [host cloud-netlab-myt-6s253.yndx.net session-id 42987] Sending message
2018-10-11 14:37:28,282 INFO: [host cloud-netlab-myt-6s253.yndx.net session-id 42987] Sending:
<?xml version="1.0" encoding="UTF-8"?><rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:1eedca9d-8b55-4b65-b0b9-4e7b3304bf3e"><edit-config><target><running/></target><config>
      <ethernet xmlns="http://www.huawei.com/netconf/vrp/huawei-ethernet">
        <ethernetIfs>
          <ethernetIf>
            <ifName>100GE1/0/1:4</ifName>
            <l2Enable>enable</l2Enable>
            <l2Attribute>
              <linkType>trunk</linkType>
              <pvid>106</pvid>
              <trunkVlans>4,5,6,104,106</trunkVlans>
              <taggedPacketDiscard>false</taggedPacketDiscard>
              <portBridgEnable>false</portBridgEnable>
            </l2Attribute>
          </ethernetIf>
        </ethernetIfs>
      </ethernet>
    </config></edit-config></rpc>]]>]]>
2018-10-11 14:37:28,336 DEBUG: [host cloud-netlab-myt-6s253.yndx.net session-id 42987] parsing netconf v1.0
2018-10-11 14:37:28,336 INFO: [host cloud-netlab-myt-6s253.yndx.net session-id 42987] Received:
<?xml version="1.0" encoding="UTF-8"?>
<rpc-reply message-id="urn:uuid:1eedca9d-8b55-4b65-b0b9-4e7b3304bf3e" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <ok/>
</rpc-reply>
```

And everything works.

**Comment by horseinthesky** [comment]
I enabled logging:
```
In [3]: dev.switch_intf()
2018-10-05 16:37:33,825 DEBUG: [host cloud-netlab-myt-6s253.yndx.net session-id 36771] installing listener <ncclient.operations.rpc.RPCReplyListener object at 0x7fbc742ed7b8>
2018-10-05 16:37:33,826 INFO: [host cloud-netlab-myt-6s253.yndx.net session-id 36771] Requesting 'EditConfig'
2018-10-05 16:37:33,826 DEBUG: [host cloud-netlab-myt-6s253.yndx.net session-id 36771] queueing <?xml version="1.0" encoding="UTF-8"?><rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:828936b6-0501-4e80-9beb-21e8e9c5a885"><edit-config><target><running/></target><config>
  <ethernet xmlns="http://www.huawei.com/netconf/vrp/huawei-ethernet">
    <ethernetIfs>
       <ethernetIf>
         <ifName>100ge1/0/1:4</ifName>
         <l2Enable>enable</l2Enable>
         <l2Attribute>
           <linkType>trunk</linkType>
           <pvid>106</pvid>
           <trunkVlans>4,6,106</trunkVlans>
           <taggedPacketDiscard>false</taggedPacketDiscard>
           <portBridgEnable>false</portBridgEnable>
         </l2Attribute>
       </ethernetIf>
    </ethernetIfs>
  </ethernet>
</config></edit-config></rpc>
2018-10-05 16:37:33,826 DEBUG: [host cloud-netlab-myt-6s253.yndx.net session-id 36771] Sync request, will wait for timeout=30
2018-10-05 16:37:33,842 DEBUG: [host cloud-netlab-myt-6s253.yndx.net session-id 36771] Sending message
2018-10-05 16:37:33,842 INFO: [host cloud-netlab-myt-6s253.yndx.net session-id 36771] Sending:

#736
<?xml version="1.0" encoding="UTF-8"?><rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:828936b6-0501-4e80-9beb-21e8e9c5a885"><edit-config><target><running/></target><config>
  <ethernet xmlns="http://www.huawei.com/netconf/vrp/huawei-ethernet">
    <ethernetIfs>
       <ethernetIf>
         <ifName>100ge1/0/1:4</ifName>
         <l2Enable>enable</l2Enable>
         <l2Attribute>
           <linkType>trunk</linkType>
           <pvid>106</pvid>
           <trunkVlans>4,6,106</trunkVlans>
           <taggedPacketDiscard>false</taggedPacketDiscard>
           <portBridgEnable>false</portBridgEnable>
         </l2Attribute>
       </ethernetIf>
    </ethernetIfs>
  </ethernet>
</config></edit-config></rpc>
##

2018-10-05 16:37:33,852 DEBUG: [host cloud-netlab-myt-6s253.yndx.net session-id 36771] _parse11: starting
2018-10-05 16:37:33,852 DEBUG: [host cloud-netlab-myt-6s253.yndx.net session-id 36771] _parse11: working with buffer of 829 bytes
2018-10-05 16:37:33,852 DEBUG: [host cloud-netlab-myt-6s253.yndx.net session-id 36771] _parse11: matching from 0 bytes from start of buffer
2018-10-05 16:37:33,852 DEBUG: [host cloud-netlab-myt-6s253.yndx.net session-id 36771] _parse11: regular expression start=0, end=6
2018-10-05 16:37:33,852 DEBUG: [host cloud-netlab-myt-6s253.yndx.net session-id 36771] _parse11: found chunk delimiter
2018-10-05 16:37:33,852 DEBUG: [host cloud-netlab-myt-6s253.yndx.net session-id 36771] _parse11: chunk size 819 bytes
2018-10-05 16:37:33,852 DEBUG: [host cloud-netlab-myt-6s253.yndx.net session-id 36771] _parse11: appending 819 bytes
2018-10-05 16:37:33,852 DEBUG: [host cloud-netlab-myt-6s253.yndx.net session-id 36771] _parse11: fragment = "<?xml version="1.0" encoding="UTF-8"?>
<rpc-reply message-id="urn:uuid:828936b6-0501-4e80-9beb-21e8e9c5a885" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <rpc-error>
    <error-type>protocol</error-type>
    <error-tag>unknown-namespace</error-tag>
    <error-severity>error</error-severity>
    <error-app-tag>319</error-app-tag>
    <error-message>ethernet has invalid namespace: http://www.huawei.com/netconf/vrp/huawei-ethernet.&#13;
</error-message>
    <error-info>
      <bad-element>ethernet</bad-element>
      <bad-namespace>http://www.huawei.com/netconf/vrp/huawei-ethernet</bad-namespace>
      <error-paras>
        <error-para>ethernet</error-para>
        <error-para>http://www.huawei.com/netconf/vrp/huawei-ethernet</error-para>
      </error-paras>
    </error-info>
  </rpc-error>
</rpc-reply>
"
2018-10-05 16:37:33,852 DEBUG: [host cloud-netlab-myt-6s253.yndx.net session-id 36771] _parse11: matching from 825 bytes from start of buffer
2018-10-05 16:37:33,852 DEBUG: [host cloud-netlab-myt-6s253.yndx.net session-id 36771] _parse11: regular expression start=0, end=4
2018-10-05 16:37:33,852 DEBUG: [host cloud-netlab-myt-6s253.yndx.net session-id 36771] _parse11: found end of message delimiter
2018-10-05 16:37:33,852 INFO: [host cloud-netlab-myt-6s253.yndx.net session-id 36771] Received:
<?xml version="1.0" encoding="UTF-8"?>
<rpc-reply message-id="urn:uuid:828936b6-0501-4e80-9beb-21e8e9c5a885" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <rpc-error>
    <error-type>protocol</error-type>
    <error-tag>unknown-namespace</error-tag>
    <error-severity>error</error-severity>
    <error-app-tag>319</error-app-tag>
    <error-message>ethernet has invalid namespace: http://www.huawei.com/netconf/vrp/huawei-ethernet.&#13;
</error-message>
    <error-info>
      <bad-element>ethernet</bad-element>
      <bad-namespace>http://www.huawei.com/netconf/vrp/huawei-ethernet</bad-namespace>
      <error-paras>
        <error-para>ethernet</error-para>
        <error-para>http://www.huawei.com/netconf/vrp/huawei-ethernet</error-para>
      </error-paras>
    </error-info>
  </rpc-error>
</rpc-reply>

2018-10-05 16:37:33,852 DEBUG: [host cloud-netlab-myt-6s253.yndx.net session-id 36771] dispatching message to <ncclient.operations.rpc.RPCReplyListener object at 0x7fbc742ed7b8>: <?xml version="1.0" encoding="UTF-8"?>
<rpc-reply message-id="urn:uuid:828936b6-0501-4e80-9beb-21e8e9c5a885" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <rpc-error>
    <error-type>protocol</error-type>
    <error-tag>unknown-namespace</error-tag>
    <error-severity>error</error-severity>
    <error-app-tag>319</error-app-tag>
    <error-message>ethernet has invalid namespace: http://www.huawei.com/netconf/vrp/huawei-ethernet.&#13;
</error-message>
    <error-info>
      <bad-element>ethernet</bad-element>
      <bad-namespace>http://www.huawei.com/netconf/vrp/huawei-ethernet</bad-namespace>
      <error-paras>
        <error-para>ethernet</error-para>
        <error-para>http://www.huawei.com/netconf/vrp/huawei-ethernet</error-para>
      </error-paras>
    </error-info>
  </rpc-error>
</rpc-reply>

2018-10-05 16:37:33,853 DEBUG: [host cloud-netlab-myt-6s253.yndx.net session-id 36771] Delivering to <ncclient.operations.edit.EditConfig object at 0x7fbc742ed400>
2018-10-05 16:37:33,853 DEBUG: [host cloud-netlab-myt-6s253.yndx.net session-id 36771] dispatching message to <ncclient.transport.session.NotificationHandler object at 0x7fbc742ed240>: <?xml version="1.0" encoding="UTF-8"?>
<rpc-reply message-id="urn:uuid:828936b6-0501-4e80-9beb-21e8e9c5a885" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <rpc-error>
    <error-type>protocol</error-type>
    <error-tag>unknown-namespace</error-tag>
    <error-severity>error</error-severity>
    <error-app-tag>319</error-app-tag>
    <error-message>ethernet has invalid namespace: http://www.huawei.com/netconf/vrp/huawei-ethernet.&#13;
</error-message>
    <error-info>
      <bad-element>ethernet</bad-element>
      <bad-namespace>http://www.huawei.com/netconf/vrp/huawei-ethernet</bad-namespace>
      <error-paras>
        <error-para>ethernet</error-para>
        <error-para>http://www.huawei.com/netconf/vrp/huawei-ethernet</error-para>
      </error-paras>
    </error-info>
  </rpc-error>
</rpc-reply>

2018-10-05 16:37:33,853 DEBUG: [host cloud-netlab-myt-6s253.yndx.net session-id 36771] _parse11: saving back rest of message after 829 bytes, original size 829
2018-10-05 16:37:33,853 DEBUG: [host cloud-netlab-myt-6s253.yndx.net session-id 36771] _parse11: ending
---------------------------------------------------------------------------
RPCError                                  Traceback (most recent call last)
<ipython-input-3-b881a05389ad> in <module>()
----> 1 dev.switch_intf()

~/vlantoggler/app/vl2.py in switch_intf(self)
     55             with open('test.txt', 'w') as f:
     56                 f.write(payload)
---> 57             netconf_reply = self.conn.edit_config(payload, target='running')
     58             with open('test.txt', 'a') as f:
     59                 f.write(netconf_reply)

/usr/local/lib/python3.6/dist-packages/ncclient/manager.py in execute(self, cls, *args, **kwds)
    214                    async_mode=self._async_mode,
    215                    timeout=self._timeout,
--> 216                    raise_mode=self._raise_mode).request(*args, **kwds)
    217 
    218     def locked(self, target):

/usr/local/lib/python3.6/dist-packages/ncclient/operations/edit.py in request(self, config, format, target, default_operation, test_option, error_option)
     65             sub_ele(config_text, "configuration-text").text = config
     66 # >>>>>>> juniper
---> 67         return self._request(node)
     68 
     69 

/usr/local/lib/python3.6/dist-packages/ncclient/operations/rpc.py in _request(self, op)
    339                             raise RPCError(to_ele(self._reply._raw), errs=errors)
    340                         else:
--> 341                             raise self._reply.error
    342                 if self._device_handler.transform_reply():
    343                     return NCElement(self._reply, self._device_handler.transform_reply())

RPCError: ethernet has invalid namespace: http://www.huawei.com/netconf/vrp/huawei-ethernet.
```

**Comment by horseinthesky** [comment]
Actually, I was able to configure the device by setting version 1.1 to config namespace:
`<config xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.1">`

By still getting the timeout exception:
```
In [6]: dev.switch_intf()
2018-10-05 17:20:26,164 DEBUG: [host cloud-netlab-myt-6s253.yndx.net session-id 36813] installing listener <ncclient.operations.rpc.RPCReplyListener object at 0x7fdeddbbffd0>
2018-10-05 17:20:26,164 INFO: [host cloud-netlab-myt-6s253.yndx.net session-id 36813] Requesting 'EditConfig'
2018-10-05 17:20:26,164 DEBUG: [host cloud-netlab-myt-6s253.yndx.net session-id 36813] queueing <?xml version="1.0" encoding="UTF-8"?><nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:ed3e5d52-a4bd-46ef-94e1-3091906873d4"><nc:edit-config><nc:target><nc:running/></nc:target><config xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.1">
  <ethernet xmlns="http://www.huawei.com/netconf/vrp/huawei-ethernet">
    <ethernetIfs>
       <ethernetIf>
         <ifName>100ge1/0/1:4</ifName>
         <l2Enable>enable</l2Enable>
         <l2Attribute>
           <linkType>access</linkType>
           <pvid>126</pvid>
           <taggedPacketDiscard>false</taggedPacketDiscard>
           <portBridgEnable>false</portBridgEnable>
         </l2Attribute>
       </ethernetIf>
    </ethernetIfs>
  </ethernet>
</config></nc:edit-config></nc:rpc>
2018-10-05 17:20:26,164 DEBUG: [host cloud-netlab-myt-6s253.yndx.net session-id 36813] Sync request, will wait for timeout=30
2018-10-05 17:20:26,241 DEBUG: [host cloud-netlab-myt-6s253.yndx.net session-id 36813] Sending message
2018-10-05 17:20:26,241 INFO: [host cloud-netlab-myt-6s253.yndx.net session-id 36813] Sending:

#768
<?xml version="1.0" encoding="UTF-8"?><nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:ed3e5d52-a4bd-46ef-94e1-3091906873d4"><nc:edit-config><nc:target><nc:running/></nc:target><config xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.1">
  <ethernet xmlns="http://www.huawei.com/netconf/vrp/huawei-ethernet">
    <ethernetIfs>
       <ethernetIf>
         <ifName>100ge1/0/1:4</ifName>
         <l2Enable>enable</l2Enable>
         <l2Attribute>
           <linkType>access</linkType>
           <pvid>126</pvid>
           <taggedPacketDiscard>false</taggedPacketDiscard>
           <portBridgEnable>false</portBridgEnable>
         </l2Attribute>
       </ethernetIf>
    </ethernetIfs>
  </ethernet>
</config></nc:edit-config></nc:rpc>
##

2018-10-05 17:20:26,416 DEBUG: [host cloud-netlab-myt-6s253.yndx.net session-id 36813] _parse11: starting
2018-10-05 17:20:26,416 DEBUG: [host cloud-netlab-myt-6s253.yndx.net session-id 36813] _parse11: working with buffer of 192 bytes
2018-10-05 17:20:26,416 DEBUG: [host cloud-netlab-myt-6s253.yndx.net session-id 36813] _parse11: matching from 0 bytes from start of buffer
2018-10-05 17:20:26,417 DEBUG: [host cloud-netlab-myt-6s253.yndx.net session-id 36813] _parse11: regular expression start=0, end=6
2018-10-05 17:20:26,417 DEBUG: [host cloud-netlab-myt-6s253.yndx.net session-id 36813] _parse11: found chunk delimiter
2018-10-05 17:20:26,417 DEBUG: [host cloud-netlab-myt-6s253.yndx.net session-id 36813] _parse11: chunk size 182 bytes
2018-10-05 17:20:26,417 DEBUG: [host cloud-netlab-myt-6s253.yndx.net session-id 36813] _parse11: appending 182 bytes
2018-10-05 17:20:26,417 DEBUG: [host cloud-netlab-myt-6s253.yndx.net session-id 36813] _parse11: fragment = "<?xml version="1.0" encoding="UTF-8"?>
<rpc-reply message-id="urn:uuid:ed3e5d52-a4bd-46ef-94e1-3091906873d4" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
  <ok/>
</rpc-reply>
"
2018-10-05 17:20:26,417 DEBUG: [host cloud-netlab-myt-6s253.yndx.net session-id 36813] _parse11: matching from 188 bytes from start of buffer
2018-10-05 17:20:26,417 DEBUG: [host cloud-netlab-myt-6s253.yndx.net session-id 36813] _parse11: regular expression start=0, end=4
2018-10-05 17:20:26,417 DEBUG: [host cloud-netlab-myt-6s253.yndx.net session-id 36813] _parse11: found end of message delimiter
2018-10-05 17:20:26,418 INFO: [host cloud-netlab-myt-6s253.yndx.net session-id 36813] Received:
<?xml version="1.0" encoding="UTF-8"?>
<rpc-reply message-id="urn:uuid:ed3e5d52-a4bd-46ef-94e1-3091906873d4" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
  <ok/>
</rpc-reply>

2018-10-05 17:20:26,418 DEBUG: [host cloud-netlab-myt-6s253.yndx.net session-id 36813] dispatching message to <ncclient.operations.rpc.RPCReplyListener object at 0x7fdeddbbffd0>: <?xml version="1.0" encoding="UTF-8"?>
<rpc-reply message-id="urn:uuid:ed3e5d52-a4bd-46ef-94e1-3091906873d4" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
  <ok/>
</rpc-reply>

2018-10-05 17:20:26,418 DEBUG: [host cloud-netlab-myt-6s253.yndx.net session-id 36813] dispatching message to <ncclient.transport.session.NotificationHandler object at 0x7fdeddbbf550>: <?xml version="1.0" encoding="UTF-8"?>
<rpc-reply message-id="urn:uuid:ed3e5d52-a4bd-46ef-94e1-3091906873d4" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
  <ok/>
</rpc-reply>

2018-10-05 17:20:26,418 DEBUG: [host cloud-netlab-myt-6s253.yndx.net session-id 36813] _parse11: saving back rest of message after 192 bytes, original size 192
2018-10-05 17:20:26,418 DEBUG: [host cloud-netlab-myt-6s253.yndx.net session-id 36813] _parse11: ending
---------------------------------------------------------------------------
TimeoutExpiredError                       Traceback (most recent call last)
<ipython-input-6-b881a05389ad> in <module>()
----> 1 dev.switch_intf()

~/vlantoggler/app/vl2.py in switch_intf(self)
     54             with open('test.txt', 'w') as f:
     55                 f.write(payload)
---> 56             netconf_reply = self.conn.edit_config(payload, target='running')
     57             with open('test.txt', 'a') as f:
     58                 f.write(netconf_reply)

/usr/local/lib/python3.6/dist-packages/ncclient/manager.py in execute(self, cls, *args, **kwds)
    214                    async_mode=self._async_mode,
    215                    timeout=self._timeout,
--> 216                    raise_mode=self._raise_mode).request(*args, **kwds)
    217 
    218     def locked(self, target):

/usr/local/lib/python3.6/dist-packages/ncclient/operations/edit.py in request(self, config, format, target, default_operation, test_option, error_option)
     65             sub_ele(config_text, "configuration-text").text = config
     66 # >>>>>>> juniper
---> 67         return self._request(node)
     68 
     69 

/usr/local/lib/python3.6/dist-packages/ncclient/operations/rpc.py in _request(self, op)
    345                     return self._reply
    346             else:
--> 347                 raise TimeoutExpiredError('ncclient timed out while waiting for an rpc reply.')
    348 
    349     def request(self):

TimeoutExpiredError: ncclient timed out while waiting for an rpc reply.
```

**Comment by einarnn** [comment]
@horseinthesky , your code looks ok as far as I can see. The reply seems to be being received by the ncclient library:

```
2018-10-05 17:20:26,418 INFO: [host cloud-netlab-myt-6s253.yndx.net session-id 36813] Received:
<?xml version="1.0" encoding="UTF-8"?>
<rpc-reply message-id="urn:uuid:ed3e5d52-a4bd-46ef-94e1-3091906873d4" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
  <ok/>
</rpc-reply>
```

And it is being dispatched to the RPC reply listener:

```
2018-10-05 17:20:26,418 DEBUG: [host cloud-netlab-myt-6s253.yndx.net session-id 36813] dispatching message to <ncclient.operations.rpc.RPCReplyListener object at 0x7fdeddbbffd0>: <?xml version="1.0" encoding="UTF-8"?>
<rpc-reply message-id="urn:uuid:ed3e5d52-a4bd-46ef-94e1-3091906873d4" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
  <ok/>
</rpc-reply>
```

This **should** result in your code that made the edit_config request being woken up and given the reply, but, without being able to replicate this issue locally, I cannot make any suggestions other than you attempt to debug what is happening in the RPC reply listener code.

**Comment by horseinthesky** [comment]
I'm not that good in Python to understand what is going on https://github.com/ncclient/ncclient/blob/master/ncclient/operations/rpc.py

I'm able to give any test results, log etc. Just tell me what to do.
