### ISSUE TITLE
ImportError: cannot import name 'etree' when using manager

### ISSUE THREAD

**Issue by DocDriven** [ncclient/ncclient#293]
Hello there,

I installed ncclient successfully using the setup.py script. In my interpreter session, when I try to import the manager via `from ncclient import manager`, I get the following error trace:

> Traceback (most recent call last):
>   File "/home/serving/inference/ncclient_test.py", line 3, in <module>
>     from ncclient import operations
>   File "/usr/local/lib/python3.6/dist-packages/ncclient-0.6.3+2.gde873d8-py3.6.egg/ncclient/operations/__init__.py", line 16, in <module>
>     from ncclient.operations.rpc import RPC, RPCReply, RPCError, RaiseMode
>   File "/usr/local/lib/python3.6/dist-packages/ncclient-0.6.3+2.gde873d8-py3.6.egg/ncclient/operations/rpc.py", line 19, in <module>
>     from ncclient.xml_ import *
>   File "/usr/local/lib/python3.6/dist-packages/ncclient-0.6.3+2.gde873d8-py3.6.egg/ncclient/xml_.py", line 25, in <module>
>     from lxml import etree
> ImportError: cannot import name 'etree'

However, it is possible for me to execute `import ncclient` or even `from ncclient import capabilities`. Can you help me with this issue?

I'm on Ubuntu 16.04 LTS and using Python 3.6.

**Comment by einarnn** [comment]
It's not really possible to tell from the above if your installation of `lxml` is somehow corrupt. can you create a virtualenv and tree installing lxml on its own and see if an import statement like `from lxml import etree` works correctly?
