### ISSUE TITLE
Fail to login device

### ISSUE THREAD

**Issue by helijia21** [ncclient/ncclient#331]
Here is a problem while login device

Traceback (most recent call last):
  File "test.py", line 10, in <module>
    device_params={'name':'default'}) as m:
  File "/usr/python/lib/python3.7/site-packages/ncclient/manager.py", line 177, in connect
    return connect_ssh(*args, **kwds)
  File "/usr/python/lib/python3.7/site-packages/ncclient/manager.py", line 143, in connect_ssh
    session.connect(*args, **kwds)
  File "/usr/python/lib/python3.7/site-packages/ncclient/transport/ssh.py", line 491, in connect
    self._auth(username, password, key_filenames, allow_agent, look_for_keys)
  File "/usr/python/lib/python3.7/site-packages/ncclient/transport/ssh.py", line 590, in _auth
    raise AuthenticationError(repr(saved_exception))
ncclient.transport.errors.AuthenticationError: BadAuthenticationType('Bad authentication type', ['publickey', 'keyboard-interactive'])

**Comment by helijia21** [comment]
device : NOKIA PSS with OpenAgent, and its supported / used YANG data models.

**Comment by einarnn** [comment]
Can you please enable debug for your connection attempt? And can you also demonstrate a successful authentication using a command like `ssh -p 830 router.ip.address -s netconf`, and paste appropriately anonymized examnple here, as well as the logs?

Cheers,

Einar

**Comment by einarnn** [comment]
No further feedback. Closing issue for now. Please feel free to re-open with more data.
