### ISSUE TITLE
IOError: close() called during concurrent operation on the same file object.

### ISSUE THREAD

**Issue by samta** [ncclient/ncclient#371]
Hitting this issue when trying to close the session.
Please find the script:

from ncclient import manager
import logging, time
logging.getLogger().setLevel(logging.WARN)

if __name__ == '__main__':
    LOG_FILENAME = '/var/log/nc.log'
    LOG_FORMAT = '%(asctime)s %(levelname)s %(filename)s:%(lineno)d %(message)s'
    logging.basicConfig(filename=LOG_FILENAME, level=logging.DEBUG, format=LOG_FORMAT)
    conn = None
    while True:
        try:
            conn = manager.connect(host='localhost',
                                   hostkey_verify=False,
                                   device_params={'name': 'junos', 'local': True},
                                   allow_agent=False,
                                   look_for_keys=True,
                                   timeout=60
                                   )
            # while True:
            #    try:
            rpc = "<get-interface-information><detail/></get-interface-information>"
            response = conn.rpc(rpc)
            logging.info('RESPONSE:%s' % response)

        except Exception as e:
            logging.exception(e)

        try:
            logging.info('conn state %s ' % conn.connected)
            if conn.connected:
                logging.info('conn is connected %s' % conn.connected)
                conn.close_session()
            else:
                logging.info('conn close !')
        except Exception as e:
            logging.exception(e)

Here when command execution has failed with the following error:
===================================================
2020-02-14 11:00:13,985 DEBUG __init__.py:1433 [host None session-id 66035] Trying another round of parsing since there is still data
2020-02-14 11:00:13,986 DEBUG __init__.py:1433 [host None session-id 66035] parsing netconf v1.0
2020-02-14 11:00:13,990 DEBUG __init__.py:1433 [host None session-id 66035] discarding listener <ncclient.transport.session.HelloHandler object at 0xdbe489ec>
2020-02-14 11:00:13,993 INFO __init__.py:1441 [host None session-id 66035] initialized: session-id=66035 | server_capabilities=<dictionary-keyiterator object at 0xe6a37914>
2020-02-14 11:00:13,998 DEBUG __init__.py:1433 [host None session-id 66035] installing listener <ncclient.operations.rpc.RPCReplyListener object at 0xdbe489ec>
2020-02-14 11:00:14,003 INFO __init__.py:1441 [host None session-id 66035] Requesting 'ExecuteRpc'
2020-02-14 11:00:14,010 DEBUG __init__.py:1433 [host None session-id 66035] queueing <?xml version="1.0" encoding="UTF-8"?><nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:37753a7d-ed90-42af-a4c9-a786da10b4a2"><get-interface-information><detail/></get-interface-information></nc:rpc>
2020-02-14 11:00:14,016 DEBUG __init__.py:1433 [host None session-id 66035] Sync request, will wait for timeout=60

2020-02-14 11:01:14,029 ERROR __init__.py:1596 ncclient timed out while waiting for an rpc reply.
Traceback (most recent call last):
  File "/var/db/scripts/op/nc_test.py", line 26, in <module>
    response = conn.rpc(rpc)
  File "../../../../../../../../src/dist/python-add-ons/ncclient/ncclient/manager.py", line 215, in execute
  File "../../../../../../../../src/dist/python-add-ons/ncclient/ncclient/operations/third_party/juniper/rpc.py", line 46, in request
  File "../../../../../../../../src/dist/python-add-ons/ncclient/ncclient/operations/rpc.py", line 347, in _request
TimeoutExpiredError: ncclient timed out while waiting for an rpc reply.
=====================================================

After this we try to close the session and then observed the following stack trace:

=========================================================
2020-02-14 11:01:14,047 INFO __init__.py:1441 [host None session-id 66035] Requesting 'CloseSession'
2020-02-14 11:01:14,049 DEBUG __init__.py:1433 [host None session-id 66035] queueing <?xml version="1.0" encoding="UTF-8"?><nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:0402fbc2-8ed3-4ffd-a396-0668aa0d68a0"><nc:close-session/></nc:rpc>
2020-02-14 11:01:14,053 DEBUG __init__.py:1433 [host None session-id 66035] Sync request, will wait for timeout=60
2020-02-14 11:02:09,404 DEBUG __init__.py:1433 [host None session-id 64867] dispatching error to <ncclient.operations.rpc.RPCReplyListener object at 0xcaff3a0c>
2020-02-14 11:02:09,418 DEBUG __init__.py:1433 [host None session-id 64867] dispatching error to <ncclient.transport.session.NotificationHandler object at 0xcaff3a2c>
2020-02-14 11:02:20,928 ERROR __init__.py:1596 close() called during concurrent operation on the same file object.
Traceback (most recent call last):
  File "/var/db/scripts/op/nc_test.py", line 36, in <module>
    conn.close_session()
  File "../../../../../../../../src/dist/python-add-ons/ncclient/ncclient/manager.py", line 215, in execute
  File "../../../../../../../../src/dist/python-add-ons/ncclient/ncclient/operations/session.py", line 30, in request
  File "../../../../../../../../src/dist/python-add-ons/ncclient/ncclient/transport/third_party/junos/ioproc.py", line 41, in close
  File "../../../../../../../src/dist/python/Lib/subprocess.py", line 799, in communicate
  File "../../../../../../../src/dist/python/Lib/subprocess.py", line 1401, in _communicate
  File "../../../../../../../src/dist/python/Lib/subprocess.py", line 1477, in _communicate_with_poll
  File "../../../../../../../src/dist/python/Lib/subprocess.py", line 1438, in close_unregister_and_remove
IOError: close() called during concurrent operation on the same file object.
2020-02-14 11:02:20,935 DEBUG __init__.py:1433 [host None session 0xd0a3b04c] <IOProc(session, initial daemon)> created: client_capabilities=<dictionary-keyiterator object at 0xe6a37914>

===============================================================

Since there is a while loop running, we open the session again and this causes the number of threads to count associated with this process keeps increasing. The memory size is also increasing.

**Comment by vnitinv** [comment]
I will look into this.

**Comment by einarnn** [comment]
Any progress on this?
