### ISSUE TITLE
config and target are not working as positional parameters in Manager.edit_config

### ISSUE THREAD

**Issue by 991jo** [ncclient/ncclient#374]
Hello

when I am using the edit_config method of the manager class with `config` and `target` as positional arguments the call fails. If I use it with the same options as keyword arguments the command fails.
The parameters are documented as positional parameters in the docs.

python version: 3.8.1
ncclient version: 0.6.7

Example Code

working:
```
from ncclient import manager

with manager.connect(host="100.71.40.21", port=22, username="jo", password="derpderp", hostkey_verify=False, allow_agent=False) as m:
    c = m.edit_config(target="running", config="""<config>
         <cli-config-data>
<cmd>hostname test</cmd>
</cli-config-data>
      </config>""")
    print(c)
```
Output:
```
<?xml version="1.0" encoding="UTF-8"?><rpc-reply message-id="urn:uuid:1e1822c3-29a5-45f9-aa94-d38786a08a07" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><ok /></rpc-reply>
```

not working:
```
from ncclient import manager

with manager.connect(host="100.71.40.21", port=22, username="jo", password="derpderp", hostkey_verify=False, allow_agent=False) as m:
    c = m.edit_config("running", """<config>
         <cli-config-data>
<cmd>hostname test</cmd>
</cli-config-data>
      </config>""")
    print(c)
```
Output:
```
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    c = m.edit_config("running", """<config>
  File "/home/jo/projects/netconf-tests/lib/python3.8/site-packages/ncclient/manager.py", line 231, in execute
    return cls(self._session,
  File "/home/jo/projects/netconf-tests/lib/python3.8/site-packages/ncclient/operations/edit.py", line 69, in request
    return self._request(node)
  File "/home/jo/projects/netconf-tests/lib/python3.8/site-packages/ncclient/operations/rpc.py", line 337, in _request
    raise self._error
  File "/home/jo/projects/netconf-tests/lib/python3.8/site-packages/ncclient/transport/ssh.py", line 488, in run
    self.parser.parse(data)
  File "/home/jo/projects/netconf-tests/lib/python3.8/site-packages/ncclient/transport/parser.py", line 118, in parse
    self._parse10()
  File "/home/jo/projects/netconf-tests/lib/python3.8/site-packages/ncclient/transport/parser.py", line 137, in _parse10
    self._session._dispatch_message(msg)
  File "/home/jo/projects/netconf-tests/lib/python3.8/site-packages/ncclient/transport/ssh.py", line 128, in _dispatch_message
    return super(SSHSession, self)._dispatch_message(raw)
  File "/home/jo/projects/netconf-tests/lib/python3.8/site-packages/ncclient/transport/session.py", line 79, in _dispatch_message
    l.callback(root, raw) # no try-except; fail loudly if you must!
  File "/home/jo/projects/netconf-tests/lib/python3.8/site-packages/ncclient/operations/rpc.py", line 222, in callback
    raise OperationError("Could not find 'message-id' attribute in <rpc-reply>")
ncclient.operations.errors.OperationError: Could not find 'message-id' attribute in <rpc-reply>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 9, in <module>
    print(c)
  File "/home/jo/projects/netconf-tests/lib/python3.8/site-packages/ncclient/manager.py", line 217, in __exit__
    self.close_session()
  File "/home/jo/projects/netconf-tests/lib/python3.8/site-packages/ncclient/manager.py", line 231, in execute
    return cls(self._session,
  File "/home/jo/projects/netconf-tests/lib/python3.8/site-packages/ncclient/operations/session.py", line 28, in request
    return self._request(new_ele("close-session"))
  File "/home/jo/projects/netconf-tests/lib/python3.8/site-packages/ncclient/operations/rpc.py", line 354, in _request
    raise TimeoutExpiredError('ncclient timed out while waiting for an rpc reply.')
ncclient.operations.errors.TimeoutExpiredError: ncclient timed out while waiting for an rpc reply.
```

My router is a Cisco 886 running IOS version 15.7(3)M4a.

The logfiles of the router contain:
```
*Feb 26 18:55:10.783: GSI: netconf app _s_ssh.[0x8B3AE898]: <?xml version="1.0" encoding="UTF-8"?><nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:2ba1e94f-531b-4372-a14c-d2149eb1c0fe"><nc:edit-config><nc:target><nc:candidate/></nc:target></nc:edit-config></nc:rpc>
*Feb 26 18:55:10.783: NETCONF: _namn.77.mlc.don=87B95898
*Feb 26 18:55:10.783: NETCONF: _narc.77.rcv.ok=8B319F88
*Feb 26 18:55:10.783: NETCONF: netconf_xml_interpret.77.msg_len=236 bytes
*Feb 26 18:55:10.783: NETCONF: netconf_xml_interpret.77.failure<?xml version="1.0" encoding="UTF-8"?><nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0"message-id="urn:uuid:2ba1e94f-531b-4372-a14c-d2149eb1c0fe"><nc:edit-config><nc:target><nc:candidate/></nc:target></nc:edit-configg></nc:rpc>
*Feb 26 18:55:10.783: NETCONF: _nssd.77.snd.now<?xml version="1.0" encoding="UTF-8"?><rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><rpc-error><error-type>rpc</error-type><error-tag>missing-element</error-tag><error-severity>error</error-severity><error-info><bad-element>config</bad-element></error-info></rpc-error></rpc-reply>
```
-> the command which is send to the router uses the candidate config which is not supported by this device.

**Comment by einarnn** [comment]
@991jo, the `edit_config` function can only accept one positional argument, which is the config to be applied. The target is a named parameter, which defaults to `candidate`. Thus your non-working code above is not intended to work (this behavior has not changed recently). You will need to instead use something like:

```
from ncclient import manager

config_to_apply = """<config>
  <cli-config-data>
    <cmd>hostname test</cmd>
  </cli-config-data>
</config>"""

with manager.connect(host="100.71.40.21", port=22, username="jo", password="derpderp", hostkey_verify=False, allow_agent=False) as m:
   c = m.edit_config(config_to_apply, target='running')
   print(c)
```

**Comment by einarnn** [comment]
Closing this issue as the API is behaving as it always has.

**Comment by 991jo** [comment]
Okay, thank you for your response.
If it is intended to have only the config as a positional argument then your Docs at https://ncclient.readthedocs.io/en/latest/manager.html#ncclient.manager.Manager.edit_config
do not show this.
The docs have 2 positional arguments.

**Comment by einarnn** [comment]
Apologies! The online docs are potentially out of date as the current maintainers don’t have access to updating the docs.
