### ISSUE TITLE
ncclient.operations.rpc.RPCError: Operation not supported

### ISSUE THREAD

**Issue by mrmerumaru** [ncclient/ncclient#391]
Hi,

I am running Python 3.8.2, and ncclient 0.6.7
Connecting from Ubuntu 20.04 to NX-OSv 7.2(0)D1(1) running on GNS3. 
Getting error with the `get_config` method.

My script:
```
from ncclient import manager

host = "192.168.198.131"
port = "22"
user = "admin"
password = "admin"
filename = "NXOS1.txt"

with manager.connect(host=host, port=port, username=user, password=password, hostkey_verify=False, allow_agent=False, look_for_keys=False, device_params={'name':'nexus'}) as m:
    c = m.get_config(source='running').data_xml
    with open("/home/meru/Documents/NETCONF/%s" % filename, 'w') as f:
        f.write(c)
```

when I run this, I got this error:
```
root@ubuntu:/home/meru/Documents/NETCONF# python3 script3.py
Traceback (most recent call last):
  File "script3.py", line 10, in <module>
    c = m.get_config(source='running')
  File "/root/.local/lib/python3.8/site-packages/ncclient/manager.py", line 231, in execute
    return cls(self._session,
  File "/root/.local/lib/python3.8/site-packages/ncclient/operations/retrieve.py", line 166, in request
    return self._request(node)
  File "/root/.local/lib/python3.8/site-packages/ncclient/operations/rpc.py", line 348, in _request
    raise self._reply.error
ncclient.operations.rpc.RPCError: Operation not supported
root@ubuntu:/home/meru/Documents/NETCONF#
```

Am I missing anything here? what am I doing wrong?

**Comment by mrmerumaru** [comment]
Never mind. turns out the NXOS version I am using, which is version 7.2(0)D1(1) is buggy. Came across a few people having the same problem as mine.

upgraded the NXOS to this version: _titanium-d1-kickstart.7.3.0.D1.1.bin_

works perfectly now.
