### ISSUE TITLE
[xlm_.py:124] AttributeError: 'list' object has no attribute 'encode'

### ISSUE THREAD

**Issue by ubzmrh** [ncclient/ncclient#393]
Sometimes x ist not a str but a subtree, in fact a list
`
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    vlan.get_config()
  File "/home/ADMB0002059/.local/lib/python3.6/site-packages/pyhpecw7/features/vlan.py", line 78, in get_config
    nc_get_reply = self.device.get(('subtree', top))
  File "/home/ADMB0002059/.local/lib/python3.6/site-packages/pyhpecw7/comware.py", line 325, in get
    rsp = self.execute(self.connection.get, [get_tuple])
  File "/home/ADMB0002059/.local/lib/python3.6/site-packages/pyhpecw7/comware.py", line 213, in execute
    rsp = run_cmd_func(*args, **kwargs)
  File "/home/ADMB0002059/.local/lib/python3.6/site-packages/ncclient/manager.py", line 236, in execute
    huge_tree=self._huge_tree).request(*args, **kwds)
  File "~/.local/lib/python3.6/site-packages/ncclient/operations/retrieve.py", line 83, in request
    node.append(util.build_filter(filter))
  File "~/.local/lib/python3.6/site-packages/ncclient/operations/util.py", line 62, in build_filter
    qualify("filter", ns=NETCONF_NOTIFICATION_NS)))
  File "~/.local/lib/python3.6/site-packages/ncclient/xml_.py", line 145, in validated_element
    ele = to_ele(x)
  File "~/.local/lib/python3.6/site-packages/ncclient/xml_.py", line 124, in to_ele
    return x if etree.iselement(x) else etree.fromstring(x.encode('UTF-8'), parser=_get_parser(huge_tree))
AttributeError: 'list' object has no attribute 'encode'
`

I added 
`print(f"type(x) is {type(x)}, x={x}")`
to know why and I get
`type(x) is <class 'list'>, x=[('subtree', <Element {http://www.hp.com/netconf/data:1.0}top at 0x7f7644f962c8>)]`

**Comment by einarnn** [comment]
Can you expand on the problem you are encountering with a sample script perhaps?

**Comment by ubzmrh** [comment]
I'm testing the https://github.com/HPENetworking/pyhpecw7 library to administer our HPE devices.
I used the script as an example in "Getting Started".
`
from pyhpecw7.comware import HPCOM7
from pyhpecw7.features.vlan import Vlan

args = dict(host='100.119.180.145', username='svcpimc03', password='*****', port=830)
device = HPCOM7(**args)
device.open()
vlan = Vlan(device, '301')
vlan.get_config()
device.close()
exit(0)
`
The problem occurs at the "vlan.get_config()" instruction.
The result should be {'name': '[MAQ-HP]-ADMIN', 'vlanid': '301', 'descr': '[MAQ-HP]-ADMIN'}

**Comment by ubzmrh** [comment]
Eurêka ! I found the error.
when the author of the library I use (pyhpecw7) use your function get, he pass as filter a list containing None instead of just pass None.
Sorry  for the inconvenience.
