### ISSUE TITLE
ncclient doesn't connect to netconf server due to incompatible ssh peer

### ISSUE THREAD

**Issue by tharunprabhu** [ncclient/ncclient#401]
This is the error I get when i try to run a simple get_config script:

```
o handlers could be found for logger "ncclient.transport.ssh"
Traceback (most recent call last):
  File "eg4.py", line 15, in <module>
    hostkey_verify=False,
  File "/usr/local/lib/python2.7/dist-packages/ncclient/manager.py", line 176, in connect
    return connect_ssh(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/ncclient/manager.py", line 141, in connect_ssh
    session.connect(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/ncclient/transport/ssh.py", line 331, in connect
    raise SSHError('Negotiation failed: %s' % e)
ncclient.transport.errors.SSHError: Negotiation failed: Incompatible ssh peer (no acceptable host key)
```

This is what I see in the netconf server (netopeer2) logs:
```
[INF]: LN: Accepted a connection on 0.0.0.0:830.
[INF]: SR: Session 27 (user "root") created.
[2020/06/30 22:16:07.385349, 2] ssh_pki_import_privkey_base64:  Trying to decode privkey passphrase=false
[2020/06/30 22:16:07.387853, 2] ssh_server_connection_callback:  SSH client banner: SSH-2.0-paramiko_2.7.1
[2020/06/30 22:16:07.387905, 2] ssh_analyze_banner:  Analyzing banner: SSH-2.0-paramiko_2.7.1
[2020/06/30 22:16:07.390215, 1] ssh_kex_select_methods:  kex error : no match for method server host key algo: server [rsa-sha2-512,rsa-sha2-256], client [ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-rsa,ssh-dss]
[ERR]: LN: SSH key exchange error (kex error : no match for method server host key algo: server [rsa-sha2-512,rsa-sha2-256], client [ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-rsa,ssh-dss]).
```

Looks like a no key match error. Is this a problem with the server or the client?
How do i resolve this? Any help would be much appreciated. Thanks!

**Comment by einarnn** [comment]
It's a problem with both client & server potentially. The list supported by the netopeer server looks very restricted, and ncclient uses Paramiko for SSH, which doesn't yet support those algorithms (there is a pull request [here](https://github.com/paramiko/paramiko/pull/1520/files)).

**Comment by einarnn** [comment]
Not an ncclient issue, sorry!

**Comment by tharunprabhu** [comment]
Thanks for your help @einarnn !

**Comment by fredgan** [comment]
Hi @tharunprabhu @einarnn  Since it's not an ncclient issue, this issue can be closed.
