### ISSUE TITLE
Cannot parse received xml. Invalid tag name.

### ISSUE THREAD

**Issue by HalfInner** [ncclient/ncclient#423]
Hi!

During conducting test on the Cisco environment I receive error that the tag is invalid. 

Could you verify if this behaviour is correct?

Thanks in advance,
HalfInner

```bash
Connected to pydev debugger (build 192.7142.79)
Traceback (most recent call last):
  File "<ProjecPath>/basics/netconf.py", line 22, in <module>
    replay = m.get_confg(source='running', filter=netconf_filter)
  File "<ProjecPath\venv>\lib\site-packages\ncclient\manager.py", line 269, in _missing
    r = self.rpc(root)
  File "<ProjecPath\venv>\lib\site-packages\ncclient\manager.py", line 268, in _missing
    sub_ele(root, arg)
  File "<ProjecPath\venv>\lib\site-packages\ncclient\xml_.py", line 237, in <lambda>
    sub_ele = lambda parent, tag, attrs={}, **extra: etree.SubElement(parent, qualify(tag, parent_ns(parent)), attrs, **extra)
  File "src\lxml\etree.pyx", line 3136, in lxml.etree.SubElement
  File "src\lxml\apihelpers.pxi", line 179, in lxml.etree._makeSubElement
  File "src\lxml\apihelpers.pxi", line 1734, in lxml.etree._tagValidOrRaise
ValueError: Invalid tag name '<Element {urn:ietf:params:xml:ns:netconf:base:1.0}get-confg at 0x20c4ee64e08>'
```

**Comment by fredgan** [comment]
Hi,
Which version do you use? and provide your simplified testcases if you can :-)

**Comment by fredgan** [comment]
you should use `get_config` instead of `get_confg` :-)

**Comment by HalfInner** [comment]
Ugh... So disappointment. Thanks!
