### ISSUE TITLE
etree Element object fails as a subtree filter

### ISSUE THREAD

**Issue by davidspindola** [ncclient/ncclient#427]
The documentation says that an Element object is a valid filter criteria:
> For “subtree” the criteria should be an XML string or an Element object containing the criteria.

But when its used it throws an error:
```
Traceback (most recent call last):
  File "filters.py", line 34, in <module>
    st = m.get(filter=('subtree', NATIVE))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ncclient/manager.py", line 231, in execute
    huge_tree=self._huge_tree).request(*args, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ncclient/operations/retrieve.py", line 83, in request
    node.append(util.build_filter(filter))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ncclient/operations/util.py", line 62, in build_filter
    rep.append(to_ele(criteria))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ncclient/xml_.py", line 125, in to_ele
    return x if etree.iselement(x) else etree.fromstring(x.encode('UTF-8'), parser=_get_parser(huge_tree))
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'encode'
```

This is the code that I use to test in IOS-XE devices:
```
from ncclient import manager
import xml.etree.ElementTree as ET


### Connection Variables ###
HOST = ''
PORT = ''
USERNAME = ''
PASSWORD = ''
PARAMS = {'name': 'iosxe'}

### XPATH Variables ###
NAMESPACE = {'xmlns': 'http://cisco.com/ns/yang/Cisco-IOS-XE-native'}
XPATH = '/native/version'

### SUBTREE Variables ###
STF_XML = """
<native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native" xmlns:ios="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
    <version />
</native>
"""
NATIVE = ET.Element('native', attrib={'xmlns': 'http://cisco.com/ns/yang/Cisco-IOS-XE-native', 'xmlns:ios':'http://cisco.com/ns/yang/Cisco-IOS-XE-native'})
VERSION = ET.SubElement(NATIVE, 'version')


with manager.connect(host=HOST, port=PORT, username=USERNAME, password=PASSWORD, hostkey_verify=False, device_params=PARAMS) as m:
    xp = m.get_config(source='running', filter=('xpath', XPATH))
    print(f'---\nXPATH1:\n\n{xp}\n\n...')
    xp = m.get_config(source='running', filter=('xpath', (NAMESPACE, XPATH)))
    print(f'---\nXPATH2:\n\n{xp}\n\n...')
    st = m.get(filter=('subtree', STF_XML))
    print(f'---\nSUBTREE1:\n\n{st}\n\n...')
    if ET.iselement(NATIVE):
        st = m.get(filter=('subtree', NATIVE))
        print(f'---\nSUBTREE2:\n\n{st}\n\n...')

**Comment by davidspindola** [comment]
I was trying with xml library, lxml works fine:
```
from ncclient import manager
import lxml.etree as ET


### Connection Variables ###
HOST = ''
PORT = ''
USERNAME = ''
PASSWORD = ''
PARAMS = {'name': 'iosxe'}

### XPATH Variables ###
NAMESPACE = {'xmlns': 'http://cisco.com/ns/yang/Cisco-IOS-XE-native'}
XPATH = '/native/version'

### SUBTREE Variables ###
STF_XML = """
<native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
    <version />
</native>
"""
NATIVE = ET.Element('native', attrib={'xmlns': 'http://cisco.com/ns/yang/Cisco-IOS-XE-native'})
VERSION = ET.SubElement(NATIVE, 'version')


with manager.connect(host=HOST, port=PORT, username=USERNAME, password=PASSWORD, hostkey_verify=False, device_params=PARAMS) as m:
    # Simple text XPATH
    xp = m.get_config(source='running', filter=('xpath', XPATH))
    print(f'---\nXPATH1:\n\n{xp}\n\n...')

    # Tuple of XML namespace and XPATH
    xp = m.get_config(source='running', filter=('xpath', (NAMESPACE, XPATH)))
    print(f'---\nXPATH2:\n\n{xp}\n\n...')

    # Subtree of simple text XML
    st = m.get(filter=('subtree', STF_XML))
    print(f'---\nSUBTREE1:\n\n{st}\n\n...')

    # Subtree with lxml.etree.Element object
    if ET.iselement(NATIVE):
        st = m.get(filter=('subtree', NATIVE))
        print(f'---\nSUBTREE2:\n\n{st}\n\n...')
