### ISSUE TITLE
lxml.etree.XMLSyntaxError: python3.6

### ISSUE THREAD

**Issue by lmcanco** [ncclient/ncclient#438]
Having an issue in ansible when using module netconf_rpc,  the following error occurs, however when I change interpreter_python = /usr/bin/python2.7 error is not present 

Any reason what can be causing this issue

Setup:

ansible 2.9.13
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Dec  5 2019, 15:45:45) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

installed lxml-4.5.2 ncclient-0.6.9

thanks..

rpc payload:

<?xml version=\"1.0\" encoding=\"UTF-8\"?><data xmlns:fabrics=\"urn:kaloom:faas:fabrics\" xmlns=\"urn:ietf:params:xml:ns:netconf:base:1.0\" xmlns:nc=\"urn:ietf:params:xml:ns:netconf:base:1.0\"><fabrics:Fabric><fabrics:FabricID>212</fabrics:FabricID><fabrics:Node><fabrics:NodeID>31f454f1-5172-493b-8848-d8b43123c7eb</fabrics:NodeID><fabrics:Name>aj08025933-upf-31u</fabrics:Name></fabrics:Node><fabrics:Node><fabrics:NodeID>99058603-dae0-4259-9897-6ae17129b73e</fabrics:NodeID><fabrics:Name>ak18000735-leaf-29u</fabrics:Name></fabrics:Node><fabrics:Node><fabrics:NodeID>9ce42f1e-02e4-4816-8a66-22fafae92e51</fabrics:NodeID><fabrics:Name>controller-1</fabrics:Name></fabrics:Node></fabrics:Fabric></data>"

<10.10.10.10> EXEC /bin/sh -c '/usr/bin/python3.6 /root/.ansible/tmp/ansible-local-9652MobtmE/ansible-tmp-1601554935.02-9754-119778420816035/AnsiballZ_netconf_rpc.py && sleep 0'
<10.10.10.10> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-local-9652MobtmE/ansible-tmp-1601554935.02-9754-119778420816035/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-local-9652MobtmE/ansible-tmp-1601554935.02-9754-119778420816035/AnsiballZ_netconf_rpc.py", line 102, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-local-9652MobtmE/ansible-tmp-1601554935.02-9754-119778420816035/AnsiballZ_netconf_rpc.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-local-9652MobtmE/ansible-tmp-1601554935.02-9754-119778420816035/AnsiballZ_netconf_rpc.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.network.netconf.netconf_rpc', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_netconf_rpc_payload_t8kmcb46/ansible_netconf_rpc_payload.zip/ansible/modules/network/netconf/netconf_rpc.py", line 264, in <module>
  File "/tmp/ansible_netconf_rpc_payload_t8kmcb46/ansible_netconf_rpc_payload.zip/ansible/modules/network/netconf/netconf_rpc.py", line 246, in main
  File "/tmp/ansible_netconf_rpc_payload_t8kmcb46/ansible_netconf_rpc_payload.zip/ansible/module_utils/network/common/netconf.py", line 141, in remove_namespaces
  File "/usr/local/lib/python3.6/site-packages/ncclient/xml_.py", line 174, in __init__
    self.__doc = self.remove_namespaces(self.__result)
  File "/usr/local/lib/python3.6/site-packages/ncclient/xml_.py", line 222, in remove_namespaces
    parser=self.__parser))),
  File "src/lxml/etree.pyx", line 3521, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1876, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1896, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1777, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1082, in lxml.etree._BaseParser._parseUnicodeDoc
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1

**Comment by einarnn** [comment]
Without more debugs enabled it is not possible to debug this. Please provide more info by enabling more ncclient debugs.

**Comment by lmcanco** [comment]
A solution exists and works see link below
Thanks

https://github.com/ansible-collections/ansible.netcommon/pull/152

**Comment by einarnn** [comment]
Ok, closing this issue. Thanks!
