### ISSUE TITLE
edit_config giving issue

### ISSUE THREAD

**Issue by harshad1692** [ncclient/ncclient#439]
with help of edit_config, am trying to create user & am facing some issue 
here is my code

**#xml format to create user**

```
snippet = '''<config 
                 ncx:last-modified="2020-10-06T05:32:13Z" ncx:etag="1453">
                     <users>
                        <user>
                           <name>rakesh</name>
                        </user>
                    </users>
                </config>'''

```
**code** 

def test_edit_config():
  with manager.connect(host=HOST, port=PORT, username=USER, password=PASS,hostkey_verify=False, device_params={'name': 'default'},look_for_keys=False, allow_agent=False) as m:
    assert(":candidate" in m.server_capabilities)
    assert(":validate"  in m.server_capabilities)
    with m.locked(target='candidate'):
      d = m.discard_changes()
      print(d, "discard_changes message")
      c = m.edit_config(config=snippet)
      print(c, "edit_config message")
      v = m.validate()
      m.commit(confirmed=True, timeout="10", persist=pid)
      print ("Running the tests")
      time.sleep(5)
      print ("Committing")
      res = m.commit(confirmed=True)
      print (res)   

**output**

<?xml version="1.0" encoding="UTF-8"?>
<rpc-reply xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0"
 message-id="urn:uuid:0ad3fea5-ac91-4e93-8130-401e3e62b2ce"
 xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
 <ok/>
</rpc-reply> discard_changes message
Traceback (most recent call last):
  File "user_mgmt_1.py", line 52, in <module>
    test_edit_config()
  File "user_mgmt_1.py", line 38, in test_edit_config
    c = m.edit_config(config=snippet)
  File "/usr/local/lib/python3.5/dist-packages/ncclient-0.6.7+31.g69565ad-py3.5.egg/ncclient/manager.py", line 231, in execute
    huge_tree=self._huge_tree).request(*args, **kwds)
  File "/usr/local/lib/python3.5/dist-packages/ncclient-0.6.7+31.g69565ad-py3.5.egg/ncclient/operations/edit.py", line 61, in request
    node.append(validated_element(config, ("config", qualify("config"))))
  File "/usr/local/lib/python3.5/dist-packages/ncclient-0.6.7+31.g69565ad-py3.5.egg/ncclient/xml_.py", line 145, in validated_element
    ele = to_ele(x)
  File "/usr/local/lib/python3.5/dist-packages/ncclient-0.6.7+31.g69565ad-py3.5.egg/ncclient/xml_.py", line 124, in to_ele
    return x if etree.iselement(x) else etree.fromstring(x.encode('UTF-8'), parser=_get_parser(huge_tree))
  File "src/lxml/lxml.etree.pyx", line 3213, in lxml.etree.fromstring (src/lxml/lxml.etree.c:82934)
  File "src/lxml/parser.pxi", line 1819, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:124533)
  File "src/lxml/parser.pxi", line 1707, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:123074)
  File "src/lxml/parser.pxi", line 1079, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:117114)
  File "src/lxml/parser.pxi", line 573, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:110510)
  File "src/lxml/parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:112276)
  File "src/lxml/parser.pxi", line 613, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:111124)
lxml.etree.XMLSyntaxError: Namespace prefix ncx for last-modified on config is not defined, line 2, column 71

**Comment by einarnn** [comment]
@harshad1692, you need to define a namespace for the prefix `ncx`. For example:

```
snippet = '''<config ncx:xmlns="URI-FOR-NCX"
                 ncx:last-modified="2020-10-06T05:32:13Z" ncx:etag="1453">
                     <users>
                        <user>
                           <name>rakesh</name>
                        </user>
                    </users>
                </config>'''
```

As it is defined in your query, the XML parser in ncclient can tell that your XML is invalid, hence the exception thrown.

**Comment by einarnn** [comment]
@harshad1692, closing this issue.

**Comment by harshad1692** [comment]
sorry problem remains the same, after changing the snippet of xml as you suggested.

```
snippet = '''<config ncx:xmlns="URI-FOR-NCX"
                 ncx:last-modified="2020-10-06T05:32:13Z" ncx:etag="1453">
                     <users>
                        <user>
                           <name>rakesh</name>
                        </user>
                    </users>
                </config>'''
```

**error message**

<?xml version="1.0" encoding="UTF-8"?><rpc-reply xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:acd79e5a-edf2-4711-8f33-9d806a5a78f6" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><ok/></rpc-reply> discard_changes message
Traceback (most recent call last):
  File "user_mgmt_1.py", line 51, in <module>
    test_edit_config()
  File "user_mgmt_1.py", line 40, in test_edit_config
    c = m.edit_config(config=snippet)
  File "/usr/local/lib/python3.5/dist-packages/ncclient-0.6.7+31.g69565ad-py3.5.egg/ncclient/manager.py", line 231, in execute
    huge_tree=self._huge_tree).request(*args, **kwds)
  File "/usr/local/lib/python3.5/dist-packages/ncclient-0.6.7+31.g69565ad-py3.5.egg/ncclient/operations/edit.py", line 61, in request
    node.append(validated_element(config, ("config", qualify("config"))))
  File "/usr/local/lib/python3.5/dist-packages/ncclient-0.6.7+31.g69565ad-py3.5.egg/ncclient/xml_.py", line 145, in validated_element
    ele = to_ele(x)
  File "/usr/local/lib/python3.5/dist-packages/ncclient-0.6.7+31.g69565ad-py3.5.egg/ncclient/xml_.py", line 124, in to_ele
    return x if etree.iselement(x) else etree.fromstring(x.encode('UTF-8'), parser=_get_parser(huge_tree))
  File "src/lxml/lxml.etree.pyx", line 3213, in lxml.etree.fromstring (src/lxml/lxml.etree.c:82934)
  File "src/lxml/parser.pxi", line 1819, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:124533)
  File "src/lxml/parser.pxi", line 1707, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:123074)
  File "src/lxml/parser.pxi", line 1079, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:117114)
  File "src/lxml/parser.pxi", line 573, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:110510)
  File "src/lxml/parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:112276)
  File "src/lxml/parser.pxi", line 613, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:111124)
lxml.etree.XMLSyntaxError: Namespace prefix ncx for xmlns on config is not defined, line 2, column 74

**Comment by harshad1692** [comment]
as you suggested I changed snippet, but too am facing RPCError:unknown object
```

snippet = '''<config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
                <users>
                  <user>
                    <name>rakesh</name>
                  </user>
                </users>
            </config>'''
```

**code**```

with manager.connect(host=HOST, port=PORT, username=USER, password=PASS,hostkey_verify=False, device_params={'name': 'default'},look_for_keys=False, allow_agent=False) as m:
    pid = "IQ,d4668"
    assert(":candidate" in m.server_capabilities)
    assert(":validate"  in m.server_capabilities)
    with m.locked(target='candidate'):
      d = m.discard_changes()
      c = m.edit_config(config=snippet)
      v = m.validate()
      m.commit(confirmed=True, timeout="10", persist=pid)
      print ("Running the tests")
      time.sleep(5)
      print ("Committing")
      res = m.commit(confirmed=True)
      m.commit()
```

why is it coming am clueless
