### ISSUE TITLE
edit_config not working after variable assignment

### ISSUE THREAD

**Issue by rahularadhe** [ncclient/ncclient#448]
I am trying to create a user through the edit_config of ncclient. The issue I am facing is that when I do some variable assignment eg.
netconfuser = 'xyz'
password = 'xyz@123'
create_user(netconfuser,password) => This throws the following error:

```
Traceback (most recent call last):
  File "/home/saankhyalabs/venv_ru/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/saankhyalabs/venv_ru/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/saankhyalabs/venv_ru/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/saankhyalabs/venv_ru/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/saankhyalabs/venv_ru/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/saankhyalabs/venv_ru/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/saankhyalabs/venv_ru/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/saankhyalabs/venv_ru/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/saankhyalabs/venv_ru/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/saankhyalabs/venv_ru/lib/python3.8/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/home/saankhyalabs/nms_poc/users/views.py", line 122, in create_netconf_user
    UM.create_user(netconfuser, password)
  File "/home/saankhyalabs/nms_poc/du_lib.py", line 124, in create_user
    c = self.link.edit_config(config=self.xml_string())
  File "/home/saankhyalabs/venv_ru/lib/python3.8/site-packages/ncclient/manager.py", line 226, in execute
    return cls(self._session,
  File "/home/saankhyalabs/venv_ru/lib/python3.8/site-packages/ncclient/operations/edit.py", line 69, in request
    return self._request(node)
  File "/home/saankhyalabs/venv_ru/lib/python3.8/site-packages/ncclient/operations/rpc.py", line 360, in _request
    raise self._reply.error
ncclient.operations.rpc.RPCError: value not in range
```

However, when I hardcode the values eg.
create_user('xyz','xyz@123') => seems to work fine

Following is the xml string and the function I am using to perform this operation. Any help would be appreciated.

```
xml_string = ''' <?xml version="1.0" ?><config ncx:etag="1554" ncx:last-modified="2020-10-15T05:42:17Z" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:ncx="http://netconfcentral.org/ns/yuma-ncx">
                <users xmlns="urn:o-ran:user-mgmt:1.0">
                  <user>
                    <name>pro_manager112</name>
                    <account-type>PASSWORD</account-type>
                    <password>saankhya123</password>
                    <enabled>true</enabled>
                  </user>
                </users>
            </config>'''
```

```
def create_user(name, pw):
  assert(":candidate" in self.link.server_capabilities)
  assert(":validate"  in self.link.server_capabilities)
  with self.link.locked(target='candidate'):
	d = self.link.discard_changes()
	value = self.write_xml(name, pw)
	c = self.link.edit_config(config=xml_string)
	print("Running the tests")
	print("Committing")
	self.link.commit()
```

**Comment by einarnn** [comment]
Sorry, this seems like a generic coding issue, not something specific to ncclient.

**Comment by einarnn** [comment]
This isn't an ncclient issue. And also assuming that this issue is no longer live; closing.
