### ISSUE TITLE
ACX on JunOS 17.4R2

### ISSUE THREAD

**Issue by klausps** [ncclient/ncclient#459]
> show version 
fpc0:
--------------------------------------------------------------------------
Hostname: AC1.mro1
Model: acx5048
Junos: 17.4R2-S10
JUNOS Base OS Software Suite [17.4R2-S10]
JUNOS Base OS boot [17.4R2-S10]
JUNOS Crypto Software Suite [17.4R2-S10]
JUNOS Crypto Software Suite [17.4R2-S10]
JUNOS Online Documentation [17.4R2-S10]
JUNOS Kernel Software Suite [17.4R2-S10]
JUNOS Packet Forwarding Engine Support (acx5k) [17.4R2-S10]
JUNOS Routing Software Suite [17.4R2-S10]
JUNOS Enterprise Software Suite [17.4R2-S10]
JUNOS py-base-i386 [17.4R2-S10]

conn = manager.connect(host='xxxxxx', port=xxx, username='xxxxx', password='xxxxxx', device_params={'name': 'junos'}, hostkey_verify=False)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\yyy\junos\lib\site-packages\ncclient\manager.py", line 168, in connect
    return connect_ssh(*args, **kwds)
  File "C:\Users\yyy\junos\lib\site-packages\ncclient\manager.py", line 135, in connect_ssh
    session.connect(*args, **kwds)
  File "C:\Users\yyy\junos\lib\site-packages\ncclient\transport\ssh.py", line 385, in connect
    self._post_connect()
  File "C:\Users\yyy\junos\lib\site-packages\ncclient\transport\session.py", line 116, in _post_connect
    raise error[0]
  File "C:\Users\yyy\junos\lib\site-packages\ncclient\transport\ssh.py", line 498, in run
    raise SessionCloseError(self._buffer.getvalue())
ncclient.transport.errors.SessionCloseError: Unexpected session close

**Comment by klausps** [comment]
Same issue with PTX1000 with JunOS 18.2R3.4.

PTX1000 with JunOS 17.4R2-S2.3 is working fine.

**Comment by einarnn** [comment]
> Same issue with PTX1000 with JunOS 18.2R3.4.
> 
> 
> 
> PTX1000 with JunOS 17.4R2-S2.3 is working fine.

Please try enabling more detailed debugs on the ncclient SSH module.

**Comment by klausps** [comment]
> > Same issue with PTX1000 with JunOS 18.2R3.4.
> > PTX1000 with JunOS 17.4R2-S2.3 is working fine.
> 
> Please try enabling more detailed debugs on the ncclient SSH module.

2021-01-04 17:02:20,821 - ncclient.transport.session - DEBUG - [host None session 0x298d3029b20] <SSHSession(session, initial daemon)> created: client_capabilities=<dict_keyiterator object at 0x00000298D3329A40>
2021-01-04 17:02:20,864 - ncclient.transport.ssh - DEBUG - starting thread (client mode): 0xd3330100
2021-01-04 17:02:20,866 - ncclient.transport.ssh - DEBUG - Local version/idstring: SSH-2.0-paramiko_2.7.2
2021-01-04 17:02:20,903 - ncclient.transport.ssh - DEBUG - Remote version/idstring: SSH-2.0-OpenSSH_7.4
2021-01-04 17:02:20,903 - ncclient.transport.ssh - INFO - Connected (version 2.0, client OpenSSH_7.4)
2021-01-04 17:02:20,938 - ncclient.transport.ssh - DEBUG - kex algos:['curve25519-sha256', 'curve25519-sha256@libssh.org', 'ecdh-sha2-nistp256', 'ecdh-sha2-nistp384', 'ecdh-sha2-nistp521', 'diffie-hellman-group-exchange-sha256', 'diffie-hellman-group16-sha512', 'diffie-hellman-group18-sha512', 'diffie-hellman-group14-sha256', 'diffie-hellman-group14-sha1'] server key:['ssh-rsa', 'rsa-sha2-512', 'rsa-sha2-256', 'ssh-dss', 'ecdsa-sha2-nistp256', 'ssh-ed25519'] client encrypt:['chacha20-poly1305@openssh.com', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com'] server encrypt:['chacha20-poly1305@openssh.com', 'aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'aes128-gcm@openssh.com', 'aes256-gcm@openssh.com'] client mac:['umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] server mac:['umac-64-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'hmac-sha2-512-etm@openssh.com', 'hmac-sha1-etm@openssh.com', 'umac-64@openssh.com', 'umac-128@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-sha1'] client compress:['none', 'zlib@openssh.com'] server compress:['none', 'zlib@openssh.com'] client lang:[''] server lang:[''] kex follows?False
2021-01-04 17:02:20,951 - ncclient.transport.ssh - DEBUG - Kex agreed: curve25519-sha256@libssh.org
2021-01-04 17:02:20,952 - ncclient.transport.ssh - DEBUG - HostKey agreed: ssh-ed25519
2021-01-04 17:02:20,953 - ncclient.transport.ssh - DEBUG - Cipher agreed: aes128-ctr
2021-01-04 17:02:20,953 - ncclient.transport.ssh - DEBUG - MAC agreed: hmac-sha2-256
2021-01-04 17:02:20,954 - ncclient.transport.ssh - DEBUG - Compression agreed: none
2021-01-04 17:02:20,997 - ncclient.transport.ssh - DEBUG - kex engine KexCurve25519 specified hash_algo <built-in function openssl_sha256>
2021-01-04 17:02:20,997 - ncclient.transport.ssh - DEBUG - Switch to new keys ...
2021-01-04 17:02:21,009 - ncclient.transport.ssh - DEBUG - [host X.X.X.X session 0x298d3029b20] Could not deserialize key data.
2021-01-04 17:02:21,151 - ncclient.transport.ssh - DEBUG - userauth is OK
2021-01-04 17:02:21,208 - ncclient.transport.ssh - INFO - Authentication (password) successful!
2021-01-04 17:02:21,208 - ncclient.transport.ssh - DEBUG - [chan 0] Max packet in: 32768 bytes
2021-01-04 17:02:21,239 - ncclient.transport.ssh - DEBUG - Received global request "hostkeys-00@openssh.com"
2021-01-04 17:02:21,239 - ncclient.transport.ssh - DEBUG - Rejecting "hostkeys-00@openssh.com" global request from server.
2021-01-04 17:02:21,320 - ncclient.transport.ssh - DEBUG - [chan 0] Max packet out: 32768 bytes
2021-01-04 17:02:21,321 - ncclient.transport.ssh - DEBUG - Secsh channel 0 opened.
2021-01-04 17:02:21,357 - ncclient.transport.ssh - DEBUG - [chan netconf-subsystem-0] Sesch channel 0 request ok
2021-01-04 17:02:21,361 - ncclient.transport.ssh - DEBUG - [host X.X.X.X session 0x298d3029b20] installing listener <ncclient.transport.session.NotificationHandler object at 0x00000298D3352430>
2021-01-04 17:02:21,362 - ncclient.transport.ssh - DEBUG - [chan netconf-subsystem-0] EOF received (netconf-subsystem-0)
2021-01-04 17:02:21,362 - ncclient.transport.ssh - DEBUG - [host X.X.X.X session 0x298d3029b20] installing listener <ncclient.transport.session.HelloHandler object at 0x00000298D3352460>
2021-01-04 17:02:21,363 - ncclient.transport.ssh - DEBUG - [chan netconf-subsystem-0] EOF sent (netconf-subsystem-0)
2021-01-04 17:02:21,367 - ncclient.transport.ssh - DEBUG - [host X.X.X.X session 0x298d3029b20] queueing <?xml version="1.0" encoding="UTF-8"?><nc:hello xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0"><nc:capabilities><nc:capability>urn:ietf:params:netconf:base:1.0</nc:capability><nc:capability>urn:ietf:params:netconf:base:1.1</nc:capability><nc:capability>urn:ietf:params:netconf:capability:writable-running:1.0</nc:capability><nc:capability>urn:ietf:params:netconf:capability:candidate:1.0</nc:capability><nc:capability>urn:ietf:params:netconf:capability:confirmed-commit:1.0</nc:capability><nc:capability>urn:ietf:params:netconf:capability:rollback-on-error:1.0</nc:capability><nc:capability>urn:ietf:params:netconf:capability:startup:1.0</nc:capability><nc:capability>urn:ietf:params:netconf:capability:url:1.0?scheme=http,ftp,file,https,sftp</nc:capability><nc:capability>urn:ietf:params:netconf:capability:validate:1.0</nc:capability><nc:capability>urn:ietf:params:netconf:capability:xpath:1.0</nc:capability><nc:capability>urn:ietf:params:netconf:capability:notification:1.0</nc:capability><nc:capability>urn:liberouter:params:netconf:capability:power-control:1.0</nc:capability><nc:capability>urn:ietf:params:netconf:capability:interleave:1.0</nc:capability><nc:capability>urn:ietf:params:netconf:capability:with-defaults:1.0</nc:capability></nc:capabilities></nc:hello>
2021-01-04 17:02:21,368 - ncclient.transport.ssh - DEBUG - [host X.X.X.X session 0x298d3029b20] starting main loop
2021-01-04 17:02:21,371 - ncclient.transport.ssh - DEBUG - [host X.X.X.X session 0x298d3029b20] selector type = SelectSelector
2021-01-04 17:02:21,371 - ncclient.transport.ssh - DEBUG - [host X.X.X.X session 0x298d3029b20] Broke out of main loop, error=SessionCloseError('Unexpected session close')
2021-01-04 17:02:21,372 - ncclient.transport.ssh - DEBUG - [host X.X.X.X session 0x298d3029b20] dispatching error to <ncclient.transport.session.NotificationHandler object at 0x00000298D3352430>
2021-01-04 17:02:21,372 - ncclient.transport.ssh - DEBUG - [host X.X.X.X session 0x298d3029b20] dispatching error to <ncclient.transport.session.HelloHandler object at 0x00000298D3352460>
2021-01-04 17:02:21,410 - ncclient.transport.ssh - DEBUG - [host X.X.X.X session 0x298d3029b20] discarding listener <ncclient.transport.session.HelloHandler object at 0x00000298D3352460>
Traceback (most recent call last):
2021-01-04 17:02:21,410 - ncclient.transport.ssh - DEBUG - EOF in transport thread
  File "C:\Users\Klaus\OneDrive\Documentos\venvs\JunosDevice\lib\site-packages\jnpr\junos\device.py", line 1347, in open
    self._conn = netconf_ssh.connect(
  File "C:\Users\Klaus\OneDrive\Documentos\venvs\JunosDevice\lib\site-packages\ncclient\manager.py", line 168, in connect
    return connect_ssh(*args, **kwds)
  File "C:\Users\Klaus\OneDrive\Documentos\venvs\JunosDevice\lib\site-packages\ncclient\manager.py", line 135, in connect_ssh
    session.connect(*args, **kwds)
  File "C:\Users\Klaus\OneDrive\Documentos\venvs\JunosDevice\lib\site-packages\ncclient\transport\ssh.py", line 385, in connect
    self._post_connect()
  File "C:\Users\Klaus\OneDrive\Documentos\venvs\JunosDevice\lib\site-packages\ncclient\transport\session.py", line 116, in _post_connect
    raise error[0]
  File "C:\Users\Klaus\OneDrive\Documentos\venvs\JunosDevice\lib\site-packages\ncclient\transport\ssh.py", line 498, in run
    raise SessionCloseError(self._buffer.getvalue())
ncclient.transport.errors.SessionCloseError: Unexpected session close

**Comment by einarnn** [comment]
@klausps, thanks for that. What the debugs show is that the SSH session is being correctly authenticated, but the target device is closing the SSH connection for some reason. It is not obvious that there is any issue with ncclient, and I suggest that you may wish to enable debugs on the target device to determine what the issue may be. Another approach to debugging may be to try establishing an SSH session manually to the device thus:

```
ssh -p 830 user@X.X.X.X -s netconf
```

Port 830 may differ depending on your device's configuration. I don't have an Alcatel device to test with, but if this is done with a Cisco device you will see something like:

```
$ ssh -p 830 username@192.168.1.254 -s netconf
username@192.168.1.254's password:
<?xml version="1.0" encoding="UTF-8"?>
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
<capabilities>
<capability>urn:ietf:params:netconf:base:1.0</capability>
<capability>urn:ietf:params:netconf:base:1.1</capability>
<capability>urn:ietf:params:netconf:capability:confirmed-commit:1.1</capability>
<capability>urn:ietf:params:netconf:capability:confirmed-commit:1.0</capability>
<capability>urn:ietf:params:netconf:capability:candidate:1.0</capability>
<capability>urn:ietf:params:netconf:capability:rollback-on-error:1.0</capability>
<capability>urn:ietf:params:netconf:capability:validate:1.0</capability>
<capability>urn:ietf:params:netconf:capability:validate:1.1</capability>
<capability>urn:ietf:params:netconf:capability:xpath:1.0</capability>
<capability>urn:ietf:params:netconf:capability:notification:1.0</capability>
<capability>urn:ietf:params:netconf:capability:interleave:1.0</capability>
...etc...
</capabilities>
<session-id>164736</session-id></hello>]]>]]>
```

If there is any SSH issue, it **may** show up here.

Next, you could manually send a hello message to the device by pasting something like what ncclient sends for its hello, which you can see in your logs. Remember to add the terminator `]]>]]>` after the trailing `</hello>`, and ensure that your hello message is properly formatted form an XML namespace perspective.

If upon doing this the client session terminates silently, you will definitely need to debug on the device side.

Cheers,

Einar

**Comment by klausps** [comment]
> @klausps, thanks for that. What the debugs show is that the SSH session is being correctly authenticated, but the target device is closing the SSH connection for some reason. It is not obvious that there is any issue with ncclient, and I suggest that you may wish to enable debugs on the target device to determine what the issue may be. Another approach to debugging may be to try establishing an SSH session manually to the device thus:
> 
> ```
> ssh -p 830 user@X.X.X.X -s netconf
> ```
> 
> Port 830 may differ depending on your device's configuration. I don't have a JunOS device to test with, but if this is done with a Cisco device you will see something like:
> 
> ```
> $ ssh -p 830 username@192.168.1.254 -s netconf
> username@192.168.1.254's password:
> <?xml version="1.0" encoding="UTF-8"?>
> <hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
> <capabilities>
> <capability>urn:ietf:params:netconf:base:1.0</capability>
> <capability>urn:ietf:params:netconf:base:1.1</capability>
> <capability>urn:ietf:params:netconf:capability:confirmed-commit:1.1</capability>
> <capability>urn:ietf:params:netconf:capability:confirmed-commit:1.0</capability>
> <capability>urn:ietf:params:netconf:capability:candidate:1.0</capability>
> <capability>urn:ietf:params:netconf:capability:rollback-on-error:1.0</capability>
> <capability>urn:ietf:params:netconf:capability:validate:1.0</capability>
> <capability>urn:ietf:params:netconf:capability:validate:1.1</capability>
> <capability>urn:ietf:params:netconf:capability:xpath:1.0</capability>
> <capability>urn:ietf:params:netconf:capability:notification:1.0</capability>
> <capability>urn:ietf:params:netconf:capability:interleave:1.0</capability>
> ...etc...
> </capabilities>
> <session-id>164736</session-id></hello>]]>]]>
> ```
> 
> If there is any SSH issue, it **may** show up here.
> 
> Next, you could manually send a hello message to the device by pasting something like what ncclient sends for its hello, which you can see in your logs. Remember to add the terminator `]]>]]>` after the trailing `</hello>`, and ensure that your hello message is properly formatted form an XML namespace perspective.
> 
> If upon doing this the client session terminates silently, you will definitely need to debug on the device side.
> 
> Cheers,
> 
> Einar

Hello Einar!

No, we already use NETCONF but we're not using it with ncclient. I'm trying to move my application to python.

Today, for management, we're using netconf-php but it is very old and got no more updates:
https://github.com/Juniper/netconf-php

ssh -p 830 user@x.x.x.x -s netconf
Bellow follows a get-inventory rpc using the ssh client and it works perfectly fine(I just cut off the serial numbers and other sentive information):
Password:


<nc:hello xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
   <nc:capabilities>
    <nc:capability>urn:ietf:params:netconf:base:1.0</nc:capability>
    <nc:capability>urn:ietf:params:netconf:capability:candidate:1.0</nc:capability>
    <nc:capability>urn:ietf:params:netconf:capability:confirmed-commit:1.0</nc:capability>
    <nc:capability>urn:ietf:params:netconf:capability:validate:1.0</nc:capability>
    <nc:capability>urn:ietf:params:netconf:capability:url:1.0?protocol=http,ftp,file</nc:capability>
    <nc:capability>urn:ietf:params:xml:ns:netconf:base:1.0</nc:capability>
    <nc:capability>urn:ietf:params:xml:ns:netconf:capability:candidate:1.0</nc:capability>
    <nc:capability>urn:ietf:params:xml:ns:netconf:capability:confirmed-commit:1.0</nc:capability>
    <nc:capability>urn:ietf:params:xml:ns:netconf:capability:validate:1.0</nc:capability>
    <nc:capability>urn:ietf:params:xml:ns:netconf:capability:url:1.0?protocol=http,ftp,file</nc:capability>
    <nc:capability>urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring</nc:capability>
    <nc:capability>http://xml.juniper.net/netconf/junos/1.0</nc:capability>
    <nc:capability>http://xml.juniper.net/dmi/system/1.0</nc:capability>
  </nc:capabilities>
  <nc:session-id>45285</nc:session-id>
</nc:hello>
]]>]]>
<rpc>
<get-chassis-inventory>
<nc:rpc-reply xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:junos="http://xml.juniper.net/junos/18.2R3/junos">
</get-chassis-inventory>
</rpc>
<chassis-inventory xmlns="http://xml.juniper.net/junos/18.2R3/junos-chassis">
<chassis junos:style="inventory">
<name>Chassis</name>
<description>PTX1000</description>
...
</chassis-inventory>
</nc:rpc-reply>
]]>]]>


Thank you!

**Comment by klausps** [comment]
> @klausps, thanks for that. What the debugs show is that the SSH session is being correctly authenticated, but the target device is closing the SSH connection for some reason. It is not obvious that there is any issue with ncclient, and I suggest that you may wish to enable debugs on the target device to determine what the issue may be. Another approach to debugging may be to try establishing an SSH session manually to the device thus:
> 
> ```
> ssh -p 830 user@X.X.X.X -s netconf
> ```
> 
> Port 830 may differ depending on your device's configuration. I don't have a JunOS device to test with, but if this is done with a Cisco device you will see something like:
> 
> ```
> $ ssh -p 830 username@192.168.1.254 -s netconf
> username@192.168.1.254's password:
> <?xml version="1.0" encoding="UTF-8"?>
> <hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
> <capabilities>
> <capability>urn:ietf:params:netconf:base:1.0</capability>
> <capability>urn:ietf:params:netconf:base:1.1</capability>
> <capability>urn:ietf:params:netconf:capability:confirmed-commit:1.1</capability>
> <capability>urn:ietf:params:netconf:capability:confirmed-commit:1.0</capability>
> <capability>urn:ietf:params:netconf:capability:candidate:1.0</capability>
> <capability>urn:ietf:params:netconf:capability:rollback-on-error:1.0</capability>
> <capability>urn:ietf:params:netconf:capability:validate:1.0</capability>
> <capability>urn:ietf:params:netconf:capability:validate:1.1</capability>
> <capability>urn:ietf:params:netconf:capability:xpath:1.0</capability>
> <capability>urn:ietf:params:netconf:capability:notification:1.0</capability>
> <capability>urn:ietf:params:netconf:capability:interleave:1.0</capability>
> ...etc...
> </capabilities>
> <session-id>164736</session-id></hello>]]>]]>
> ```
> 
> If there is any SSH issue, it **may** show up here.
> 
> Next, you could manually send a hello message to the device by pasting something like what ncclient sends for its hello, which you can see in your logs. Remember to add the terminator `]]>]]>` after the trailing `</hello>`, and ensure that your hello message is properly formatted form an XML namespace perspective.
> 
> If upon doing this the client session terminates silently, you will definitely need to debug on the device side.
> 
> Cheers,
> 
> Einar

Hello Einar!

Actually, today we're using Junipers netconf-php and it works perfectly fine!
https://github.com/Juniper/netconf-php

Bellow follows the ssh client and the answare from a get-chassis-inventory rpc:
`Password:


<nc:hello xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
   <nc:capabilities>
    <nc:capability>urn:ietf:params:netconf:base:1.0</nc:capability>
    <nc:capability>urn:ietf:params:netconf:capability:candidate:1.0</nc:capability>
    <nc:capability>urn:ietf:params:netconf:capability:confirmed-commit:1.0</nc:capability>
    <nc:capability>urn:ietf:params:netconf:capability:validate:1.0</nc:capability>
    <nc:capability>urn:ietf:params:netconf:capability:url:1.0?protocol=http,ftp,file</nc:capability>
    <nc:capability>urn:ietf:params:xml:ns:netconf:base:1.0</nc:capability>
    <nc:capability>urn:ietf:params:xml:ns:netconf:capability:candidate:1.0</nc:capability>
    <nc:capability>urn:ietf:params:xml:ns:netconf:capability:confirmed-commit:1.0</nc:capability>
    <nc:capability>urn:ietf:params:xml:ns:netconf:capability:validate:1.0</nc:capability>
    <nc:capability>urn:ietf:params:xml:ns:netconf:capability:url:1.0?protocol=http,ftp,file</nc:capability>
    <nc:capability>urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring</nc:capability>
    <nc:capability>http://xml.juniper.net/netconf/junos/1.0</nc:capability>
    <nc:capability>http://xml.juniper.net/dmi/system/1.0</nc:capability>
  </nc:capabilities>
  <nc:session-id>45285</nc:session-id>
</nc:hello>
]]>]]>
<rpc>
<get-chassis-inventory>
<nc:rpc-reply xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:junos="http://xml.juniper.net/junos/18.2R3/junos">
</get-chassis-inventory>
</rpc>
<chassis-inventory xmlns="http://xml.juniper.net/junos/18.2R3/junos-chassis">
<chassis junos:style="inventory">
<name>Chassis</name>
<description>PTX1000</description>
...
</chassis-inventory>
</nc:rpc-reply>
]]>]]>`

Thanks!

**Comment by klausps** [comment]
Hello Einar!

Actually, today we're using Junipers netconf-php and it works perfectly fine!
https://github.com/Juniper/netconf-php

Bellow follows the ssh client and the answare from a get-chassis-inventory rpc:

**Comment by klausps** [comment]
I've pressed the wrong button, sorry.
