### ISSUE TITLE
Issues when connecting to many devices at the same time

### ISSUE THREAD

**Issue by stvnkem** [ncclient/ncclient#461]
Hi Experts,

I am slowly moving from CLI (Netmiko) to NC due to better performance and structured response.
I use `threading `and `queue` to scale. While using Netmiko I can easily manage to get connected to 500 nodes at the same time.
Some errors may occur, but the retry works well.
However, Ncclient returns weird errors. Could you please, help me to understand why these errors happen?

Here are 3 examples:

1. I checked why the device refused the auth: Reason=User public key authentication failed.
`transport.errors.AuthenticationError`

2. No idea why it happens. This is the most often error. The vast majority of the connections die with this ex.
```
CRITICAL :: 2020-12-26 18:54:06,906 :: 65 :: Thread-346 ::  def_log_exceptions :: Unhandled exception: Traceback (most recent call last):
  File "get_cfg.py", line 52, in run
    run_old(*args, **kwargs)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "get_cfg.py", line 244, in netconf_session
    connect(**netconf_params)
  File "get_cfg.py", line 206, in connect
    timeout=10) as conn:
  File "/home/taakeis1/bfd_fix/lib64/python3.6/site-packages/ncclient/manager.py", line 168, in connect
    return connect_ssh(*args, **kwds)
  File "/home/taakeis1/bfd_fix/lib64/python3.6/site-packages/ncclient/manager.py", line 135, in connect_ssh
    session.connect(*args, **kwds)
  File "/home/taakeis1/bfd_fix/lib64/python3.6/site-packages/ncclient/transport/ssh.py", line 385, in connect
    self._post_connect()
  File "/home/taakeis1/bfd_fix/lib64/python3.6/site-packages/ncclient/transport/session.py", line 116, in _post_connect
    raise error[0]
  File "/home/taakeis1/bfd_fix/lib64/python3.6/site-packages/ncclient/transport/ssh.py", line 475, in run
    s = selectors.DefaultSelector()
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/selectors.py", line 399, in __init__
    self._epoll = select.epoll()
OSError: [Errno 24] Too many open files
```
3. No log on the device, probably the attempt did not even reach the node.
`transport.errors.SSHError`

**Comment by stvnkem** [comment]
It helped to increase the max open files.
