### ISSUE TITLE
filter from get() is not working

### ISSUE THREAD

**Issue by harshad1692** [ncclient/ncclient#462]
**code**

`m.get(filter='<filter type = "xpath" select="/users/user/password"/>')`

with this not getting expected output, from netconf server its reading whole xml where with this filter it should read xpath filter 

any lead will be appreciated.

**Comment by tonynii** [comment]
need to add the namespace on XPath

**Comment by harshad1692** [comment]
@tonynii 
tried giving namespace but still am facing issue

m.get(filter=''' <?xml version="1.0" ?>
<port-transceivers xmlns="urn:o-ran:transceiver:1.0">
 <get>
  <filter type="xpath" select="/port-transceivers"/>
 </get>
</port-transceivers> '''

Traceback (most recent call last):
  File "du_lib.py", line 504, in <module>
    print(FM.get_port_transceiver())
  File "du_lib.py", line 498, in get_port_transceiver
    </port-transceivers> ''')
  File "/usr/local/lib/python3.5/dist-packages/ncclient-0.6.7+31.g69565ad-py3.5.egg/ncclient/manager.py", line 231, in execute
    huge_tree=self._huge_tree).request(*args, **kwds)
  File "/usr/local/lib/python3.5/dist-packages/ncclient-0.6.7+31.g69565ad-py3.5.egg/ncclient/operations/retrieve.py", line 83, in request
    node.append(util.build_filter(filter))
  File "/usr/local/lib/python3.5/dist-packages/ncclient-0.6.7+31.g69565ad-py3.5.egg/ncclient/operations/util.py", line 66, in build_filter
    qualify("filter", ns=NETCONF_NOTIFICATION_NS)))
  File "/usr/local/lib/python3.5/dist-packages/ncclient-0.6.7+31.g69565ad-py3.5.egg/ncclient/xml_.py", line 150, in validated_element
    raise XMLError("Element [%s] does not meet requirement" % ele.tag)
**ncclient.xml_.XMLError: Element [{urn:o-ran:transceiver:1.0}port-transceivers] does not meet requirement**

what's wrong in xml am not getting!!

**Comment by tonynii** [comment]
try like follow:
```
import lxml.builder as builder
nsmap = {"t": 'http://example.com/example-sports'}
rpc = etree.Element(
                '{urn:ietf:params:xml:ns:netconf:base:1.0}filter', {
                    'type': 'xpath',
                    'select': "/t:sports/t:person[t:name='Cristiano Ronaldo']"
                },
                nsmap=nsmap)
res = nf_seesion.get_config(source='running', filter=rpc)
```

**Comment by einarnn** [comment]
No further traffic on this issue, assuming @harshad1692 has resolved their problem!
