### ISSUE TITLE
ValueError: Invalid tag name 

### ISSUE THREAD

**Issue by horseinthesky** [ncclient/ncclient#463]
I'm not sure if it is related to [#203](https://github.com/ncclient/ncclient/issues/203) so I'll just describe my case.

I have a Huawei CE (Cloud Edge) box and I want to execute several RPCs on it.
CE uses `huaweiyang` driver.

Usually (I mean regular `get`, `get-config`) everything goes perfectly fine.
But in this case things are a little bit more complex.

This is manual communication via shell to make it work:
```
ssh <myhost> -s netconf
```
then I send the following messages
```
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <capabilities>
    <capability>urn:ietf:params:netconf:base:1.0</capability>
    <capability>http://www.huawei.com/netconf/capability/action/1.0</capability>
  </capabilities>
</hello>]]>]]>

<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="801">
<execute-action xmlns="http://www.huawei.com/netconf/capability/base/1.0">
        <action>
                <dgntl xmlns="http://www.huawei.com/netconf/vrp" content-version="1.0" format-version="1.0">
                        <ipv6>
                                <startIpPing>
                                        <testName>ipv6_ping</testName>
                                        <destAddr>2a02:6b8:b010:e01e::31</destAddr>
                                        <vrfName>CLOUD</vrfName>
                                </startIpPing>
                        </ipv6>
                </dgntl>
        </action>
</execute-action>
</rpc>]]>]]>
<?xml version="1.0" encoding="UTF-8"?>
<rpc-reply message-id="801" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <ok/>
</rpc-reply>
]]>]]>

<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="801">
  <execute-action xmlns="http://www.huawei.com/netconf/capability/base/1.0">
    <action>
      <dgntl xmlns="http://www.huawei.com/netconf/vrp" content-version="1.0" format-version="1.0">
        <ipv6>
          <stopIpPing>
            <testName>ipv6_ping</testName>
          </stopIpPing>
        </ipv6>
      </dgntl>
    </action>
  </execute-action>
</rpc>]]>]]>
<?xml version="1.0" encoding="UTF-8"?>
<rpc-reply message-id="801" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <ok/>
</rpc-reply>
]]>]]>

<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="801">
  <execute-action xmlns="http://www.huawei.com/netconf/capability/base/1.0">
    <action>
      <dgntl xmlns="http://www.huawei.com/netconf/vrp" content-version="1.0" format-version="1.0">
        <ipv6>
          <deleteIpPing>
            <testName>ipv6_ping</testName>
          </deleteIpPing>
        </ipv6>
      </dgntl>
    </action>
  </execute-action>
</rpc>]]>]]>
<?xml version="1.0" encoding="UTF-8"?>
<rpc-reply message-id="801" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <ok/>
</rpc-reply>
]]>]]>
```

My first question is: How to add capability to my `client_capabilities`? I need to add `http://www.huawei.com/netconf/capability/action/1.0` or I'll just get an error from the device.

My second question: Why this code
```
from ncclient import manager
from getpass import getuser
import os
import xmltodict
# import logging
# import sys
# logging.basicConfig(
#     level=logging.DEBUG,
#     format='%(asctime)s %(levelname)s: %(message)s',
#     stream=sys.stdout
# )

start = {
    'execute-action': {
        '@xmlns': 'http://www.huawei.com/netconf/capability/base/1.0',
        'action': {
            'dgntl': {
                '@xmlns': 'http://www.huawei.com/netconf/vrp',
                '@content-version': '1.0',
                '@format-version': '1.0',
                'ipv6': {
                    'startIpPing': {
                        'testName': 'ipv6_ping',
                        'destAddr': '2a02:6b8:b010:e01e::31',
                        'vrfName': 'CLOUD',
                    },
                },
            },
        },
    },
}

stop = {
    'execute-action': {
        '@xmlns': 'http://www.huawei.com/netconf/capability/base/1.0',
        'action': {
            'dgntl': {
                '@xmlns': 'http://www.huawei.com/netconf/vrp',
                '@content-version': '1.0',
                '@format-version': '1.0',
                'ipv6': {
                    'stopIpPing': {
                        'testName': 'ipv6_ping',
                    },
                },
            },
        },
    },
}

delete = {
    'execute-action': {
        '@xmlns': 'http://www.huawei.com/netconf/capability/base/1.0',
        'action': {
            'dgntl': {
                '@xmlns': 'http://www.huawei.com/netconf/vrp',
                '@content-version': '1.0',
                '@format-version': '1.0',
                'ipv6': {
                    'deleteIpPing': {
                        'testName': 'ipv6_ping',
                    },
                },
            },
        },
    },
}

host = 'myhost'

if __name__ == '__main__':
    with manager.connect(
        host=host,
        port=22,
        username=getuser(),
        key_filename='{}/.ssh/id_rsa'.format(os.getenv('HOME')),
        hostkey_verify=False,
        ssh_config=True,
        timeout=5,
        device_params={'name': 'huaweiyang'},
        manager_params={'timeout': 30}
    ) as m:
        # data = xmltodict.unparse(start, pretty=True)
        # print(data)
        response = m.rpc(xmltodict.unparse(start)).data_xml
        response = m.rpc(xmltodict.unparse(stop)).data_xml
        response = m.rpc(xmltodict.unparse(delete)).data_xml

        with open('h.txt', 'w') as f:
            f.write(response)
  ```
  
  failes with
  ```
  Traceback (most recent call last):
  File "Hu_ping.py", line 115, in <module>
    response = m.rpc(xmltodict.unparse(start)).data_xml
  File "/usr/local/lib/python3.8/dist-packages/ncclient/manager.py", line 268, in _missing
    sub_ele(root, arg)
  File "/usr/local/lib/python3.8/dist-packages/ncclient/xml_.py", line 237, in <lambda>
    sub_ele = lambda parent, tag, attrs={}, **extra: etree.SubElement(parent, qualify(tag, parent_ns(parent)), attrs, **extra)
  File "src/lxml/etree.pyx", line 3136, in lxml.etree.SubElement
  File "src/lxml/apihelpers.pxi", line 179, in lxml.etree._makeSubElement
  File "src/lxml/apihelpers.pxi", line 1734, in lxml.etree._tagValidOrRaise
ValueError: Invalid tag name '<?xml version="1.0" encoding="utf-8"?>\n<execute-action xmlns="http://www.huawei.com/netconf/capability/base/1.0"><action><dgntl xmlns="http://www.huawei.com/netconf/vrp" content-version="1.0" format-version="1.0"><ipv6><startIpPing><testName>ipv6_ping</testName><destAddr>2a02:6b8:b010:e01e::31</destAddr><vrfName>CLOUD</vrfName></startIpPing></ipv6></dgntl></action></execute-action>'
```

If you uncomment this two lines:
```
        # data = xmltodict.unparse(start, pretty=True)
        # print(data)
```
you'll get absolutely valid XML just like the one I used for manual interaction.

Could you pls help me with this one? Thank you.

**Comment by fredgan** [comment]
Hi @horseinthesky,
For your first question, you can use the `add()` method in class `Capabilities` to add your `client_capabilities`.
For example:
```
def demo_connect(host, port, user, password):
    return manager.connect(host=host,
                           port=port,
                           username=user,
                           password=password,
                           hostkey_verify = False,
                           device_params={'name': "huaweiyang"},
                           allow_agent = False,
                           look_for_keys = False)
def test_get(host, port, user, password):
    with demo_connect(host, port=port, user=user, password=password) as m:
        print("-------------------------------")
        m.client_capabilities.add('http://www.huawei.com/netconf/capability/action/1.0')
        for cap in m.client_capabilities:
            print(cap)
if __name__ == '__main__':
    test_get(host, port, username, password)
```

**Comment by horseinthesky** [comment]
@fredgan 
Hello.
Thank you but it doesn't work like this.
After we entered `with` block it established the connection with capabilities mentioned in `HuaweiyangDeviceHandler` [here](https://github.com/ncclient/ncclient/blob/75329ac5201fa23f1ac1cf6338c198d268b63d79/ncclient/devices/huaweiyang.py#L34).

So this code change nothing and my hello looks like this:
```
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><capabilities><capability>urn:ietf:params:netconf:base:1.0</capability><capability>urn:ietf:params:netconf:base:1.1</capability></capabilities></hello>]]>]]>
```

**Comment by einarnn** [comment]
@horseinthesky, what you can do is either:

- subclass the class [`HuaweiyangDeviceHandler`](https://github.com/ncclient/ncclient/blob/master/ncclient/devices/huaweiyang.py#L18) and override the `get_capabilities` method
- create an entirely new device handler

...and, instead of `device_params={'name': "huaweiyang"}`, pass in `device_params={'handler': NewDeviceHandlerClazz}`. This will cause ncclient to instantiate your specific device handler, which can have the correct capabilities defined.

**Comment by einarnn** [comment]
@horseinthesky, as to your other issue with:

```
response = m.rpc(xmltodict.unparse(start)).data_xml
```

...and other lines, the `rpc` method expects either an `lxml.etree.Element` (which can be arbitrarily complex) **or** a single xml tag (see https://github.com/ncclient/ncclient/blob/master/ncclient/operations/rpc.py#L482-L490).

What will work is:

```
from lxml import etree

rpc_input = etree.fromstring(xmltodict.unparse(start))
response = m.rpc(xmltodict.unparse(start)).data_xml
```

Lots of conversion!! ;-)

Cheers,

Einar

**Comment by einarnn** [comment]
@horseinthesky, please let me know if these suggestions work for you and I will close off this issue!

**Comment by horseinthesky** [comment]
@einarnn I'll check it out after getting back from New Year's holidays in Russia. Thank you.

**Comment by horseinthesky** [comment]
@einarnn 
Class inheritance to setup capabilities works great. Thank you.

But I still can't get it work with XML.
```
data = xmltodict.unparse(start)
rpc_start = etree.fromstring(data)
response = m.rpc(rpc_start).data_xml              
```
Fails with
```
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.
```
on etree line.

If I encode it
```
rpc_start = etree.fromstring(data.encode('utf-8'))
```
I still get Invalid tag name but this time it is different
```
Traceback (most recent call last):
  File "Hu_ping.py", line 158, in <module>
    response = m.rpc(rpc_start).data_xml
  File "/usr/local/lib/python3.8/dist-packages/ncclient/manager.py", line 268, in _missing
    sub_ele(root, arg)
  File "/usr/local/lib/python3.8/dist-packages/ncclient/xml_.py", line 237, in <lambda>
    sub_ele = lambda parent, tag, attrs={}, **extra: etree.SubElement(parent, qualify(tag, parent_ns(parent)), attrs, **extra)
  File "src/lxml/etree.pyx", line 3136, in lxml.etree.SubElement
  File "src/lxml/apihelpers.pxi", line 179, in lxml.etree._makeSubElement
  File "src/lxml/apihelpers.pxi", line 1734, in lxml.etree._tagValidOrRaise
ValueError: Invalid tag name '<Element {http://www.huawei.com/netconf/capability/base/1.0}execute-action at 0x7f09c9764040>'
```

**Comment by einarnn** [comment]
@horseinthesky, which version of ncclient do you actually have installed? IIRC, the generic RPC you are using requires the latest version that is not yet in PyPi. You can install this thus:

```
pip install -U git+https://github.com/ncclient/ncclient.git
```

Sorry for not noticing this sooner!

With 0.6.7 or 0.6.9:

```
$  cd /Users/einarnn/scratch ; /usr/bin/env /Users/einarnn/.virtualenvs/ncc/bin/python /Users/einarnn/.vscode/extensions/ms-python.python-2020.12.424452561/pythonFiles/lib/python/debugpy/launcher 51085 -- /Users/einarnn/scratch/hu_ping.py 
Traceback (most recent call last):
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/einarnn/.vscode/extensions/ms-python.python-2020.12.424452561/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/Users/einarnn/.vscode/extensions/ms-python.python-2020.12.424452561/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/Users/einarnn/.vscode/extensions/ms-python.python-2020.12.424452561/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/einarnn/scratch/hu_ping.py", line 85, in <module>
    response = m.rpc(rpc_input).data_xml
  File "/Users/einarnn/.virtualenvs/ncc/lib/python3.8/site-packages/ncclient/manager.py", line 273, in _missing
    sub_ele(root, arg)
  File "/Users/einarnn/.virtualenvs/ncc/lib/python3.8/site-packages/ncclient/xml_.py", line 231, in <lambda>
    sub_ele = lambda parent, tag, attrs={}, **extra: etree.SubElement(parent, qualify(tag), attrs, **extra)
  File "src/lxml/etree.pyx", line 3136, in lxml.etree.SubElement
  File "src/lxml/apihelpers.pxi", line 179, in lxml.etree._makeSubElement
  File "src/lxml/apihelpers.pxi", line 1734, in lxml.etree._tagValidOrRaise
ValueError: Invalid tag name '<Element {http://www.huawei.com/netconf/capability/base/1.0}execute-action at 0x10b764f00>'
```

And with the latest version:

```
$  cd /Users/einarnn/scratch ; /usr/bin/env /Users/einarnn/.virtualenvs/ncc/bin/python /Users/einarnn/.vscode/extensions/ms-python.python-2020.12.424452561/pythonFiles/lib/python/debugpy/launcher 51178 -- /Users/einarnn/scratch/hu_ping.py 
Traceback (most recent call last):
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/einarnn/.vscode/extensions/ms-python.python-2020.12.424452561/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/Users/einarnn/.vscode/extensions/ms-python.python-2020.12.424452561/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/Users/einarnn/.vscode/extensions/ms-python.python-2020.12.424452561/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/einarnn/scratch/hu_ping.py", line 85, in <module>
    response = m.rpc(rpc_input).data_xml
  File "/Users/einarnn/.virtualenvs/ncc/lib/python3.8/site-packages/ncclient/manager.py", line 287, in rpc
    return operations.GenericRPC(self._session,
  File "/Users/einarnn/.virtualenvs/ncc/lib/python3.8/site-packages/ncclient/operations/rpc.py", line 506, in request
    return self._request(node)
  File "/Users/einarnn/.virtualenvs/ncc/lib/python3.8/site-packages/ncclient/operations/rpc.py", line 367, in _request
    raise self._reply.error
ncclient.operations.rpc.RPCError: {'type': 'protocol', 'tag': 'unknown-namespace', 'app_tag': None, 'severity': 'error', 'info': '<?xml version="1.0" encoding="UTF-8"?><error-info xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0"><bad-element>execute-action</bad-element>\n<bad-namespace>http://www.huawei.com/netconf/capability/base/1.0</bad-namespace>\n</error-info>\n', 'path': '\n    /rpc\n  ', 'message': None}
```

**Comment by einarnn** [comment]
Please reopen if this doesn't address your issue!

**Comment by horseinthesky** [comment]
@einarnn The issue is related to ncclient==0.6.9.

With `ncclient==0.6.9+54.g6093ef3` it does work! When to expect this in PyPi?

And I want to ask about:
```
data = xmltodict.unparse(start, full_document=False)
start_rpc = etree.fromstring(data)
m.rpc(start_rpc)
```

You said that
```
 the rpc method expects either an lxml.etree.Element (which can be arbitrarily complex) or a single xml tag
 ```
 Does `single XML tag` mean it cannot be nested? This is why I need to explicitly transform it to etree.Element? Will it be fixed? I mean why such limitation is needed?
 
 Thank you.

**Comment by dmulyalin** [comment]
Think it was working before with simple xml text, as per example here https://github.com/ncclient/ncclient/blob/master/examples/juniper/execute-rpc-string.py, but that example does not seems valid anymore.

@horseinthesky and @einarnn - tried to search for commit `54.g6093ef3` code to have a look on the fix, but was not able to find it, any hints on where it is?

**Comment by dmulyalin** [comment]
For whoever might find this thread, workaround for ncclient==0.6.10 to send RPC from string:

```
from ncclient import operations, manager
from lxml import etree

rpc_string = """
<get>
  <filter type="subtree">
    <netconf-state xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring">
    <schemas/>
    </netconf-state>
  </filter>
</get>
"""

rpc_elem = etree.fromstring(rpc_string)

xrm = manager.connect(host="10.223.89.70", port=830, username="cisco", hostkey_verify=False, device_params={'name':'iosxr'}, password="cisco")

result = xrm.execute(operations.GenericRPC, rpc_elem)
```

**Comment by Menotomy** [comment]
@dmulyalin 
I had this same ValueError when going from 0.6.7 to 0.6.10. However, I'm wondering if this is an lxml thing, as that's the last issue I see in a traceback. 

In addition to taking an XML string and using etree.fromstring() as you suggested, for a simple Juniper RPC, using new_ele() from ncclient.xml_ also works. Example here:  https://github.com/ncclient/ncclient/blob/master/examples/juniper/execute-rpc.py

It seems like lxml now wants the XML string converted to a tree beforehand, either using what you showed or the new_ele() method. Using just a string worked with lxml 3.x, but in the most recent 4.6.4 it does not. Unfortunately I can't "downgrade" back to the older lxml version to test this. 

For another example, this no longer works (unless you use new_ele() for etree.fromstring()):
https://github.com/ncclient/ncclient/blob/master/examples/juniper/execute-rpc-string.py

**Comment by siddhithakur** [comment]
Getting Invalid Tag_name error for exec_command( ) While executing the command "user-name guest-user-name"

Example:
Device(config)# user-name guest
does this method provide support for "iosxe" device

So is there any specific format to give this command in the exec_command() method

**Comment by einarnn** [comment]
@siddhithakur, no, the `exec_command` operation is only available on NX-OS devices, See:

https://github.com/ncclient/ncclient/blob/master/ncclient/devices/nexus.py#L43
