### ISSUE TITLE
ncclient.operations.errors.OperationError: Unknown 'message-id'

### ISSUE THREAD

**Issue by stvnkem** [ncclient/ncclient#466]
Hello Dears,

I am trying to execute an action via NC. Could you please, help me to create a valid RPC message? I took the example from Huawei doc where the author used Ncclient. BTW do I need to set a unique MSG ID or can it be the same for all calls?

This is the trace:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/ncclient/operations/rpc.py", line 239, in callback
    rpc = self._id2rpc[id]  # the corresponding rpc
KeyError: '1001'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "execute_action_test.py", line 39, in <module>
    print(test_action(**netconf_params))
  File "execute_action_test.py", line 34, in test_action
    return m._session.send(rpc)
  File "/usr/local/lib/python3.6/site-packages/ncclient/manager.py", line 212, in __exit__
    self.close_session()
  File "/usr/local/lib/python3.6/site-packages/ncclient/manager.py", line 231, in execute
    huge_tree=self._huge_tree).request(*args, **kwds)
  File "/usr/local/lib/python3.6/site-packages/ncclient/operations/session.py", line 28, in request
    return self._request(new_ele("close-session"))
  File "/usr/local/lib/python3.6/site-packages/ncclient/operations/rpc.py", line 349, in _request
    raise self._error
  File "/usr/local/lib/python3.6/site-packages/ncclient/transport/ssh.py", line 488, in run
    self.parser.parse(data)
  File "/usr/local/lib/python3.6/site-packages/ncclient/transport/parser.py", line 116, in parse
    self._parse11()
  File "/usr/local/lib/python3.6/site-packages/ncclient/transport/parser.py", line 205, in _parse11
    self._session._dispatch_message(message)
  File "/usr/local/lib/python3.6/site-packages/ncclient/transport/ssh.py", line 128, in _dispatch_message
    return super(SSHSession, self)._dispatch_message(raw)
  File "/usr/local/lib/python3.6/site-packages/ncclient/transport/session.py", line 79, in _dispatch_message
    l.callback(root, raw) # no try-except; fail loudly if you must!
  File "/usr/local/lib/python3.6/site-packages/ncclient/operations/rpc.py", line 243, in callback
    raise OperationError("Unknown 'message-id': %s" % id)
ncclient.operations.errors.OperationError: Unknown 'message-id': 1001
```

And this is the code:

```
from ncclient import manager
ACTION = '''<?xml version="1.0" encoding="UTF-8"?>
  <rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="{}">
    <execute-action xmlns="http://www.huawei.com/netconf/capability/base/1.0">
      <action>
        <acl xmlns="http://www.huawei.com/netconf/vrp" content-version="1.0" format-version="1.0">
          <aclResetCount>
            <aclNumOrName>2111</aclNumOrName>
          </aclResetCount>
        </acl>
      </action>
    </execute-action>
  </rpc>'''


def test_action(hostname, port, username, password):
    #Fill the device information and establish a NETCONF session
    with manager.connect(host=hostname,
                           port=port,
                           username=username,
                           password=password,
                           hostkey_verify=False,
                           device_params={'name': "huawei"},
                           allow_agent=False,
                           look_for_keys=False,
                         timeout=5) as m:

        #Set the message-id for the rpc
        msgId = 1001
        rpc = ACTION.format(msgId)
        #Send RPC
        return m._session.send(rpc)


if __name__ == '__main__':
    netconf_params = {'hostname': 'asd', 'port': '22', 'username': 'asd', 'password': 'asd'}
    print(test_action(**netconf_params))

```

**Comment by stvnkem** [comment]
Hello Dears,

I think this is a bug. I did some debug on the device and the message ID that ncclient is referring to is wrong.
I think it is expecting/using the initial RPC request's message-id in the closure.

This is the initial call with `message-id="999"` Maybe the RPC messages are out of order..?

```
Jan 15 2021 22:11:40.279+01:00 hostname %%01NETCONF/7/NCA_DEBUG_LOG_GENERIC(d):CID=0x8097043b;<?xml version="1.0" encoding="UTF-8"?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="999">
  <copy-config>
    <target>
      <startup/>
    </target>
    <source>
      <running/>
    </source>
  </copy-config>
</rpc>


Jan 15 2021 22:11:40.379+01:00 hostname %%01NETCONF/7/NCA_DEBUG_LOG_GENERIC(d):CID=0x8097043b;<?xml version="1.0" encoding="UTF-8"?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:fb50e5a0-6637-4b88-bf30-eaae8bdd3a18">
  <close-session/>
</rpc>


2021-01-15 22:11:41.231+01:00 hostname %%01CONFIGURATION/6/hwcfgmaneventlog(t):CID=0x80cb000c-OID=1.3.6.1.4.1.2011.6.10.2.1;Configuration file was changed. (LogIndex=1, SrcCmd=3, SrcData=2, DestData=4, TerUser="_SYSTEM_", SrcAddr=, ConfigChangeId=443, LogTime=81902516, CfgBaselineTime="2021-01-06 09:23:52")

Jan 15 2021 22:11:41.742+01:00 hostname %%01NETCONF/7/NCA_DEBUG_LOG_GENERIC(d):CID=0x8097043b;
#137
<?xml version="1.0" encoding="UTF-8"?>
<rpc-reply message-id="999" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <ok/>
</rpc-reply>

##


Jan 15 2021 22:11:41.744+01:00 hostname %%01NETCONF/7/NCA_DEBUG_LOG_GENERIC(d):CID=0x8097043b;
#179
<?xml version="1.0" encoding="UTF-8"?>
<rpc-reply message-id="urn:uuid:fb50e5a0-6637-4b88-bf30-eaae8bdd3a18" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <ok/>
</rpc-reply>

##
```

The configuration gets saved though.

Trace:
```
CRITICAL :: 2021-01-15 22:11:41,749 :: 1302 :: Thread-1 ::  def_log_exceptions :: Unhandled exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/ncclient/operations/rpc.py", line 239, in callback
    rpc = self._id2rpc[id]  # the corresponding rpc
KeyError: '999'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/networking.py", line 1286, in run
    run_old(*args, **kwargs)
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "execute_action.py", line 116, in netconf_session
    connect(**netconf_params)
  File "execute_action.py", line 92, in connect
    print(res)
  File "/usr/local/lib/python3.6/site-packages/ncclient/manager.py", line 212, in __exit__
    self.close_session()
  File "/usr/local/lib/python3.6/site-packages/ncclient/manager.py", line 231, in execute
    huge_tree=self._huge_tree).request(*args, **kwds)
  File "/usr/local/lib/python3.6/site-packages/ncclient/operations/session.py", line 28, in request
    return self._request(new_ele("close-session"))
  File "/usr/local/lib/python3.6/site-packages/ncclient/operations/rpc.py", line 349, in _request
    raise self._error
  File "/usr/local/lib/python3.6/site-packages/ncclient/transport/ssh.py", line 488, in run
    self.parser.parse(data)
  File "/usr/local/lib/python3.6/site-packages/ncclient/transport/parser.py", line 116, in parse
    self._parse11()
  File "/usr/local/lib/python3.6/site-packages/ncclient/transport/parser.py", line 205, in _parse11
    self._session._dispatch_message(message)
  File "/usr/local/lib/python3.6/site-packages/ncclient/transport/ssh.py", line 128, in _dispatch_message
    return super(SSHSession, self)._dispatch_message(raw)
  File "/usr/local/lib/python3.6/site-packages/ncclient/transport/session.py", line 79, in _dispatch_message
    l.callback(root, raw) # no try-except; fail loudly if you must!
  File "/usr/local/lib/python3.6/site-packages/ncclient/operations/rpc.py", line 243, in callback
    raise OperationError("Unknown 'message-id': %s" % id)
ncclient.operations.errors.OperationError: Unknown 'message-id': 999
```
