### ISSUE TITLE
Improvement: Huawei Schema to support commit description

### ISSUE THREAD

**Issue by stvnkem** [ncclient/ncclient#474]
Hello,

I would suggest to add the last 2 lines to `huawei.py` so the commit description feature can be used afterwards.

```
    def get_capabilities(self):
        # Just need to replace a single value in the default capabilities
        c = super(HuaweiDeviceHandler, self).get_capabilities()
        c.append('http://www.huawei.com/netconf/capability/execute-cli/1.0')
        c.append('http://www.huawei.com/netconf/capability/action/1.0')
        c.append('http://www.huawei.com/netconf/capability/active/1.0')
        c.append('http://www.huawei.com/netconf/capability/discard-commit/1.0')
        c.append('http://www.huawei.com/netconf/capability/exchange/1.0')
        **c.append('http://www.huawei.com/netconf/capability/commit-description/1.0')
        c.append('http://www.huawei.com/netconf/capability/update/1.0')**

```

The call should look like:

```
<rpc message-id="101" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <commit>
    <description xmlns="http://www.huawei.com/netconf/capability/base/1.0">
      This is the description!!!
    </description>
    <update-candidate xmlns="http://www.huawei.com/netconf/capability/base/1.0"/>
  </commit>
</rpc>
```

Reply message:

```
<rpc-reply message-id="101" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"> 
  <ok/>
</rpc-reply>
```

I will test what happens when commit takes a long time. Based on my experience, the `session.send()` function always returns none, therefore it may be difficult to use the function this way.

AFAIK it is not supported natively

**Comment by stvnkem** [comment]
By the way, I got the following error after manipulating the capabilities function. I am not sure if I can fix it by myself.

```
Traceback (most recent call last):
  File "test_commitdesc.py", line 202, in <module>
    netconf_session(hostname)
  File "test_commitdesc.py", line 158, in netconf_session
    connect(**netconf_params)
  File "test_commitdesc.py", line 136, in connect
    conn._(commit_desc)
  File "/usr/local/lib/python3.6/site-packages/ncclient/manager.py", line 265, in _missing
    root = new_ele(m)
  File "/usr/local/lib/python3.6/site-packages/ncclient/xml_.py", line 233, in <lambda>
    new_ele = lambda tag, attrs={}, **extra: etree.Element(qualify(tag), attrs, **extra)
  File "src/lxml/etree.pyx", line 3022, in lxml.etree.Element
  File "src/lxml/apihelpers.pxi", line 101, in lxml.etree._makeElement
  File "src/lxml/apihelpers.pxi", line 1734, in lxml.etree._tagValidOrRaise
ValueError: Invalid tag name '-'
```

**Comment by einarnn** [comment]
Please submit a PR with tested code that has your suggested update, thanks!
