### ISSUE TITLE
'Authentication Failed' error when running example snippet

### ISSUE THREAD

**Issue by cpranava** [ncclient/ncclient#492]
I am getting the following error when I am running the following example snippet:
```
Traceback (most recent call last):
  File "ncchpetest.py", line 3, in <module>
    with manager.connect(host=<ip>, port=830, username=<username>, password=<password>, look_for_keys=False) as m:
  File "/root/hpep3/lib64/python3.6/site-packages/ncclient/manager.py", line 169, in connect
    return connect_ssh(*args, **kwds)
  File "/root/hpep3/lib64/python3.6/site-packages/ncclient/manager.py", line 136, in connect_ssh
    session.connect(*args, **kwds)
  File "/root/hpep3/lib64/python3.6/site-packages/ncclient/transport/ssh.py", line 361, in connect
    self._auth(username, password, key_filenames, allow_agent, look_for_keys)
  File "/root/hpep3/lib64/python3.6/site-packages/ncclient/transport/ssh.py", line 466, in _auth
    raise AuthenticationError(repr(saved_exception))
ncclient.transport.errors.AuthenticationError: AuthenticationException('Authentication failed.',)
```

Snippet:
```
from ncclient import manager

with manager.connect(host=<ip>, port=830, username=<username>, password=<password>, look_for_keys=False) as m:
    c = m.get_config(source='running').data_xml
    with open("%s.xml" % host, 'w') as f:
        f.write(c)
```

Switch Model: HPE 5945
Python version: 3.6
Client version: CentOS 7

I am able to get the YANG configuration using the following command:
ssh -p 830 username@IP -s netconf

**Comment by Menotomy** [comment]
I realize this is about 20 days old. In addition to `look_for_keys=False` can you also add `hostkey_verify=False`? I ran into similar issue with a Cisco OS, I needed both.

**Comment by einarnn** [comment]
No further traffic on this issue, assuming it is resolved! 👍
