### ISSUE TITLE
UnicodeDecodeError | Cisco IOS-XE WLC ver 17.3.3 | Python 3 ncclient ver > 0.6.1

### ISSUE THREAD

**Issue by rb3123** [ncclient/ncclient#503]
I am running a simple example to get operational status of all WAP from a new controller
```from ncclient import manager
dev_manager = manager.connect(host=ipaddress_wlc,
                              port=830,
                              username=u,
                              password=p,
                              hostkey_verify=False,
                              )
data = dev_manager.get(('subtree','''<access-point-oper-data xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-wireless-access-point-oper"/>'''))
```
I am receiving following error.

_Traceback (most recent call last):
  File "ospath/nc_unicode_testing/testing.py", line 10, in <module>
    data = dev_manager.get(('subtree','''<access-point-oper-data xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-wireless-access-point-oper"/>'''))
  File "ospath\nc_unicode_testing\venv\lib\site-packages\ncclient\manager.py", line 226, in execute
    return cls(self._session,
  File "ospath\nc_unicode_testing\venv\lib\site-packages\ncclient\operations\retrieve.py", line 91, in request
    return self._request(node)
  File "ospath\nc_unicode_testing\venv\lib\site-packages\ncclient\operations\rpc.py", line 349, in _request
    raise self._error
  File "ospath\nc_unicode_testing\venv\lib\site-packages\ncclient\transport\ssh.py", line 488, in run
    self.parser.parse(data)
  File "ospath\nc_unicode_testing\venv\lib\site-packages\ncclient\transport\parser.py", line 116, in parse
    self._parse11()
  File "ospath\nc_unicode_testing\venv\lib\site-packages\ncclient\transport\parser.py", line 178, in _parse11
    re_result = RE_NC11_DELIM.match(data[start:].decode('utf-8'))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xac in position 65: invalid start byte_

Do we have a known solution?

**Comment by rb3123** [comment]
BTW I have tried ncclient version 0.6.0 to 0.6.12 with same error

**Comment by JimWorks** [comment]
I have the same

**Comment by JimWorks** [comment]
edit the source code , like this decode('UTF-8') ===>>> decode('UTF-8', errors='ignore')

**Comment by rb3123** [comment]
didn't help me :(. I made changes on 2 lines in parser.py and another line in xml_.py

> lxml.etree.XMLSyntaxError: PCDATA invalid Char value 2, line 2, column 694653

**Comment by einarnn** [comment]
This is a defect with the underlying device ncclient is talking to. That device is returning unsupported characters. Suggest following up with Cisco and reporting a defect to Cisco.

Closing this issue.
