### ISSUE TITLE
lxml.etree.XMLSyntaxError: xmlns:  not a valid URI 

### ISSUE THREAD

**Issue by bnikhilgh** [ncclient/ncclient#544]
Hi I get this error while trying to configure a cisco ios-xr router.  Please let me know if there is any workaround for this issue. 

**Error message:-** 
=================================================================================
lxml.etree.XMLSyntaxError: xmlns: ' http://cisco.com/ns/yang/Cisco-IOS-XR-ipv4-io-cfg' is not a valid URI

**Code:-**
================================================================================
`from ncclient import manager

cisco_manager = manager.connect(host= host, port=22, username=user, password=pass, hostkey_verify=False, device_params={'name': 'iosxr'}, timeout = 5000, allow_agent=False, look_for_keys=False)

config_interface = """ ......."""    Payload is in the attached text file
[config_interface.txt](https://github.com/ncclient/ncclient/files/9154727/config_interface.txt)

data = cisco_manager.edit_config (config_interface, target='candidate')
cisco_manager.commit()
`

**Logs after executing script:-**
`=================================================================================`

PS C:\Users\nbanda\Documents\Python Projects\PY\ncclient> python.exe .\main_iosxr_working.py
Traceback (most recent call last):
  File "C:\Users\nbanda\Documents\Python Projects\PY\ncclient\main_iosxr_working.py", line 146, in <module>
    data = cisco_manager.edit_config (config_interface, target='candidate')
  File "C:\Users\nbanda\AppData\Local\Programs\Python\Python310\lib\site-packages\ncclient\manager.py", line 246, in execute
    return cls(self._session,
  File "C:\Users\nbanda\AppData\Local\Programs\Python\Python310\lib\site-packages\ncclient\operations\edit.py", line 65, in request
    node.append(validated_element(config, ("config", qualify("config"))))
  File "C:\Users\nbanda\AppData\Local\Programs\Python\Python310\lib\site-packages\ncclient\xml_.py", line 150, in validated_element
    ele = to_ele(x)
  File "C:\Users\nbanda\AppData\Local\Programs\Python\Python310\lib\site-packages\ncclient\xml_.py", line 129, in to_ele
    return x if etree.iselement(x) else etree.fromstring(x.encode('UTF-8'), parser=_get_parser(huge_tree))
  File "src\lxml\etree.pyx", line 3254, in lxml.etree.fromstring
  File "src\lxml\parser.pxi", line 1913, in lxml.etree._parseMemoryDocument
  File "src\lxml\parser.pxi", line 1800, in lxml.etree._parseDoc
  File "src\lxml\parser.pxi", line 1141, in lxml.etree._BaseParser._parseDoc
  File "src\lxml\parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src\lxml\parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src\lxml\parser.pxi", line 654, in lxml.etree._raiseParseError
  File "<string>", line 7
**lxml.etree.XMLSyntaxError: xmlns: ' http://cisco.com/ns/yang/Cisco-IOS-XR-ipv4-io-cfg' is not a valid URI, line 7, column 82**

**Comment by einarnn** [comment]
@bnikhilgh 

This seems like a fairly simple typo. You have leading spaces in your `xmlns` declarations as reported by `lxml` library:

```
lxml.etree.XMLSyntaxError: xmlns: ' http://cisco.com/ns/yang/Cisco-IOS-XR-ipv4-io-cfg' is not a valid URI, line 7, column 82
                                   ^
```

That is invalid input that `lxml` is reporting as a space character is not valud in a URI. It would have to be escaped as an entity to be embedded in the URI, but then the URI would be rejected by IOS XR.

Resolution is to remove the leading spaces as both `lxml` and IOS XR will validate the input you provide and will not understand that you didn't mean to have the leading spaces.
