### ISSUE TITLE
issue with the edit_config

### ISSUE THREAD

**Issue by alireza11048** [ncclient/ncclient#546]
Hi,
I'm trying to edit a config on a netconf server using the ncclient edit_config command, but I got the '''ncclient.operations.rpc.RPCError: Unknown XML prefix "" ''' error. this is my yang model:
```
module secure_egw {
    namespace "urn:sysrepo:secure_egw";
    prefix seg;

    revision 2018-01-19 {
        description "Initial revision.";
    }

    container add_string_filter {
        description "string filters which can be applied to different sections.";

        leaf regex {
            type string;
            //mandatory true;
            description "the regex which will be applied";
        }

        leaf desc {
            type string;
            description "the description about the filter";
        }

        leaf target {
            description "Parameter determining which part of the mail to perform the operation.";
            type enumeration {
                enum email_title {
                    description "apply the filter to the title.";
                }
                enum email_body {
                    description
                        "apply the filter to the body";
                }
            }
            //mandatory true;
        }
    }

    container get_string_filters
    {
        config false;
        
        list string_filter
        {
            key filter-id;

            leaf filter-id {
                type uint32;
                //mandatory true;
                description "key of the tree";
            }

            leaf regex {
                type string;
                //mandatory true;
                description "the regex which will be applied";
            }

            leaf desc {
                type string;
                description "the description about the filter";
            }

            leaf target {
                description "Parameter determining which part of the mail to perform the operation.";
                type enumeration {
                    enum email_title {
                        description "apply the filter to the title.";
                    }
                    enum email_body {
                        description
                            "apply the filter to the body";
                    }
                }
                //mandatory true;
            }
        }
    }
}
```
and these are the commands which are used in Python:
```
>>> m = manager.connect(host=ip, port="830", username=user, password=pass, hostkey_verify=False)
>>> m.connected
True
>>> conf1 = '''<add_string_filter xmlns="urn:sysrepo:secure_egw"></add_string_filter>'''
>>> m.get_config(source="running", filter=("subtree", conf1)) 
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:ca10c6a7-e0cf-4b09-ada2-b7f8e3201e54"><data><add_string_filter xmlns="urn:sysrepo:secure_egw"><regex>seppp</regex><desc>filtering</desc><target>email_title</target></add_string_filter></data></rpc-reply>
>>> snippet='''<config><add_string_filter xmlns="urn:sysrepo:secure_egw"><regex>saeppp</regex><desc>filtering</desc><target>email_title</target></add_string_filter></config>'''
>>> m.edit_config(target='candidate', config=snippet)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/ncclient/manager.py", line 246, in execute
    return cls(self._session,
  File "/usr/local/lib/python3.8/dist-packages/ncclient/operations/edit.py", line 76, in request
    return self._request(node)
  File "/usr/local/lib/python3.8/dist-packages/ncclient/operations/rpc.py", line 375, in _request
    raise self._reply.error
ncclient.operations.rpc.RPCError: Unknown XML prefix "".
```
could anyone give me an idea to solve the problem?

P.S:
in the netopeer-cli, i can easily change the configuration using the below xml:
```
<add_string_filter xmlns="urn:sysrepo:secure_egw">
        <regex>bsj</regex>
        <desc>filtering</desc>
        <target>email_title</target>
</add_string_filter>
```
Edit:
i also want to add the below log from the netconf server wihch may help to find the problem:
```
[INF]: NP: Session 1: thread 3 event new RPC.
[DBG]: LN: Session 1: Received message:
<?xml version="1.0" encoding="UTF-8"?><nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:d80cdb55-fecc-4645-880a-4244e9968912"><nc:edit-config><nc:target><nc:running/></nc:target><config><add_string_filter xmlns="urn:sysrepo:secure_egw"><regex>addadd</regex><desc>filtering</desc><target>email_title</target></add_string_filter></config></nc:edit-config></nc:rpc>

[ERR]: LY: Unknown XML prefix "". (Schema location /ietf-netconf:edit-config, data location /ietf-netconf:edit-config, line number 1.)
[DBG]: LN: Session 1: Sending message:

#333


[DBG]: LN: Session 1: Sending message:
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:d80cdb55-fecc-4645-880a-4244e9968912"><rpc-error><error-type>application</error-type><error-tag>operation-failed</error-tag><error-severity>error</error-severity><error-message xml:lang="en">Unknown XML prefix "".</error-message></rpc-error></rpc-reply>

[DBG]: LN: Session 1: Sending message:

```

**Comment by einarnn** [comment]
@alireza11048

Suggest you try changing:

```
snippet='''<config><add_string_filter xmlns="urn:sysrepo:secure_egw"><regex>saeppp</regex><desc>filtering</desc><target>email_title</target></add_string_filter></config>'''
```

To:

```
snippet='''<config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <add_string_filter xmlns="urn:sysrepo:secure_egw">
    <regex>saeppp</regex>
    <desc>filtering</desc>
    <target>email_title</target>
  </add_string_filter>
</config>'''
```

As you can see, the change is to add the `netconf:base:1.0` namespace to the `<config>` element.

**Comment by alireza11048** [comment]
thanks for your reply,
my problem was solved just by changing config to nc:config

**Comment by einarnn** [comment]
> thanks for your reply, my problem was solved just by changing config to nc:config

That will also work, but depends on how ncclient is formulating its message. That is an implementation detail that may change over time, and if, for example, ncclient changed `nc` to `ncx` in how it declares namespaces, the fix you have adopted would break.

We don't have such a plan in mind, but just FYI you are now dependent on an implementation detail!

;ch
