### ISSUE TITLE
ncclient's public key authentication exception handling is too generic

### ISSUE THREAD

**Issue by daemonkeeper** [ncclient/ncclient#551]
I've noticed the ncclient SSH public key authentication handling is too generic so that it hides errors and confuses the users with misleading error messages.

Here's an example

```python
In [15]: from ncclient import manager
In [17]: manager.connect(host="10.20.1.10", timeout=30, username="...", key_filename="...", hostkey_verify=False, sock_fd=s.fileno())
Unknown exception: q must be exactly 160, 224, or 256 bits long
Traceback (most recent call last):
  File "/home/arno/.local/lib/python3.9/site-packages/paramiko/transport.py", line 2171, in run
    handler(self.auth_handler, m)
  File "/home/arno/.local/lib/python3.9/site-packages/paramiko/auth_handler.py", line 377, in _parse_service_accept
    sig = self.private_key.sign_ssh_data(blob, algorithm)
  File "/home/arno/.local/lib/python3.9/site-packages/paramiko/dsskey.py", line 109, in sign_ssh_data
    key = dsa.DSAPrivateNumbers(
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 250, in private_key
    return backend.load_dsa_private_numbers(self)
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 853, in load_dsa_private_numbers
    dsa._check_dsa_private_numbers(numbers)
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 147, in _check_dsa_private_numbers
    _check_dsa_parameters(parameters)
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/primitives/asymmetric/dsa.py", line 139, in _check_dsa_parameters
    raise ValueError("q must be exactly 160, 224, or 256 bits long")
ValueError: q must be exactly 160, 224, or 256 bits long

---------------------------------------------------------------------------
AuthenticationError                       Traceback (most recent call last)
<ipython-input-17-b8aae9f50503> in <module>
----> 1 manager.connect(host="10.20.1.10", timeout=30, username="atoell", key_filename="/home/arno/.ssh/id_rsa", hostkey_verify=False, sock_fd=s.fileno())

~/.local/lib/python3.9/site-packages/ncclient/manager.py in connect(*args, **kwds)
    174             return connect_ioproc(*args, **kwds)
    175         else:
--> 176             return connect_ssh(*args, **kwds)
    177 
    178 def call_home(*args, **kwds):

~/.local/lib/python3.9/site-packages/ncclient/manager.py in connect_ssh(*args, **kwds)
    141 
    142     try:
--> 143        session.connect(*args, **kwds)
    144     except Exception as ex:
    145         if session.transport:

~/.local/lib/python3.9/site-packages/ncclient/transport/ssh.py in connect(self, host, port, timeout, unknown_host_cb, username, password, key_filename, allow_agent, hostkey_verify, hostkey_b64, look_for_keys, ssh_config, sock_fd, bind_addr, sock, keepalive, environment)
    362             key_filenames = key_filename
    363 
--> 364         self._auth(username, password, key_filenames, allow_agent, look_for_keys)
    365 
    366         self._connected = True      # there was no error authenticating

~/.local/lib/python3.9/site-packages/ncclient/transport/ssh.py in _auth(self, username, password, key_filenames, allow_agent, look_for_keys)
    479         if saved_exception is not None:
    480             # need pep-3134 to do this right
--> 481             raise AuthenticationError(repr(saved_exception))
    482 
    483         raise AuthenticationError("No authentication methods available")

AuthenticationError: SSHException('No existing session')
```

The problem is, the ``_auth()`` function does not distinguish between authentication errors, and usage errors.

Seeing this exception one might think there would be something wrong with the key, but no this is simply the exception risen by Paramiko when trying to load a RSA key as a DSA key, i.e., it is triggered here

```
            for cls in (paramiko.RSAKey, paramiko.DSSKey, paramiko.ECDSAKey, paramiko.Ed25519Key):
                try:
                    key = cls.from_private_key_file(key_filename, password)
                    self.logger.debug("Trying key %s from %s",
                                      hexlify(key.get_fingerprint()),
                                      key_filename)
                    self._transport.auth_publickey(username, key)
                    return
                except Exception as e:
                   # print function is my addition
                    print("EXC", type(e), e)
                    saved_exception = e
                    self.logger.debug(e)
```

Your code simply iterates through various keys, and whatever looks like a key and tries to authenticate with it to the target device. If not, you show the last exception that you caught. However, that is not at all indicative to the actual issue. Notice the print function I added to your code. For me it prints

```
EXC <class 'paramiko.ssh_exception.AuthenticationException'> Authentication failed.
EXC <class 'ValueError'> q must be exactly 160, 224, or 256 bits long
EXC <class 'paramiko.ssh_exception.SSHException'> 'utf-8' codec can't decode byte 0xc1 in position 1: invalid start byte
EXC <class 'paramiko.ssh_exception.SSHException'> Invalid key
```

I'd argue some of these exceptions are more indicative to the actual problem using key authentication than others. I think you should raise paramiko.ssh_exception.AuthenticationException, but not the DSA Key Loading Exception, which only happens to be shown because the actual authentication failed. 

I suggest you change the three generic authentication exceptions into something like

```
            for cls in (paramiko.RSAKey, paramiko.DSSKey, paramiko.ECDSAKey, paramiko.Ed25519Key):
                try:
                    key = cls.from_private_key_file(key_filename, password)
                    self.logger.debug("Trying key %s from %s",
                                      hexlify(key.get_fingerprint()),
                                      key_filename)
                    self._transport.auth_publickey(username, key)
                    return
                except paramiko.ssh_exception.AuthenticationException as e:
                    raise AuthenticationError from e
                except (paramiko.ssh_exception.SSHException, ValueError) as e:
                    saved_exception = e
                    self.logger.debug(e)
```

**Comment by einarnn** [comment]
@daemonkeeper, sorry for slow response. Would you care to propose a PR with such a change?

**Comment by iwanb** [comment]
Somewhat related, this change: https://github.com/ncclient/ncclient/commit/c246b2ff438456294e2a672120a4a40a140f363d

introduced the use of `paramiko.PKey.from_path`, which is only available in Paramiko 3.2: https://docs.paramiko.org/en/latest/api/keys.html?highlight=from_path#paramiko.pkey.PKey.from_path

This also gets caught in the generic exception handling, giving a generic `AuthenticationError`, hiding the real problem.

Could the minimum paramiko version be updated to 3.2 to reflect that change? https://github.com/ncclient/ncclient/blob/cdf54a49159d8192ae6d6410fad207d3489a9015/requirements.txt#L1

**Comment by einarnn** [comment]
@iwanb , Paramiko version updated via #627.
