### ISSUE TITLE
Node "startup" not found as a child of "target" node when modify startup datastore 

### ISSUE THREAD

**Issue by kookFG** [ncclient/ncclient#583]
I send the message like bellow:
<config
    xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
    <mplane-info
        xmlns="urn:o-ran:mplane-interfaces:1.0">
        <searchable-mplane-access-vlans-info>
            <vlan-range>
                <lowest-vlan-id>3000</lowest-vlan-id>
                <highest-vlan-id>3005</highest-vlan-id>
            </vlan-range>
        </searchable-mplane-access-vlans-info>
    </mplane-info>
</config>

but rpc-reply message error:
Traceback (most recent call last):
  File "de.py", line 49, in <module>
    rpc_reply_msg = conn.edit_config(target="startup", config=tree)
  File "/usr/local/python3/lib/python3.8/site-packages/ncclient/manager.py", line 246, in execute
    return cls(self._session,
  File "/usr/local/python3/lib/python3.8/site-packages/ncclient/operations/edit.py", line 76, in request
    return self._request(node)
  File "/usr/local/python3/lib/python3.8/site-packages/ncclient/operations/rpc.py", line 375, in _request
    raise self._reply.error
ncclient.operations.rpc.RPCError: Node "startup" not found as a child of "target" node.

Can the great God take a look？ thanks.

**Comment by einarnn** [comment]
@kookFG can you enable enough logging to see the XML reply from the device? The exception above is generated after the reply from the device has been parsed and is indicative of some form of XML parsing error.
