### ISSUE TITLE
ncclient > 0.6.13 is not compatible with Python 2.7

### ISSUE THREAD

**Issue by egoodwin-viasat** [ncclient/ncclient#599]
The setup.py indicates that ncclient is compatible with Python 2.7, but this is no longer the case:

```
$ python --version
Python 2.7.5
$ pip install --index-url=https://pypi.org/simple/ ncclient
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Looking in indexes: https://pypi.org/simple/
Collecting ncclient
  Using cached ncclient-0.6.16.tar.gz (112 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/vagrant/testenv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-YW2Dyr/ncclient/setup.py'"'"'; __file__='"'"'/tmp/pip-install-YW2Dyr/ncclient/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-RYn9EZ
         cwd: /tmp/pip-install-YW2Dyr/ncclient/
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-YW2Dyr/ncclient/setup.py", line 23, in <module>
        import versioneer
      File "versioneer.py", line 418
        LONG_VERSION_PY: Dict[str, str] = {}
                       ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

The culprit appears to be https://github.com/ncclient/ncclient/commit/e003f7674c48c8981433cf8ddae3b886a7f8f50d, which updated versioneer.py to a version that is not Python 2 compatible (using type hints, among other things probably).

Unfortunately this means that if you haven't pinned your ncclient version to `<=0.6.13` that you'll now run into build failures. setup.py should be updated to remove 2.7 compatibility so that future versions won't get incorrectly pulled in to Python 2.7 environments.

**Comment by a-detiste** [comment]
> setup.py should be updated to remove 2.7 compatibility

agreed, can provide a PR

**Comment by egoodwin-viasat** [comment]
> agreed, can provide a PR

How's that? ^

**Comment by a-detiste** [comment]
https://github.com/ncclient/ncclient/pull/607

**Comment by einarnn** [comment]
#607 now merged.
