### ISSUE TITLE
cannot import name 'AF_UNIX' from 'socket'  windows 10

### ISSUE THREAD

**Issue by dongjiadd** [ncclient/ncclient#602]
from ncclient import manager

Traceback (most recent call last):
  File "C:\Users\vgame\PycharmProjects\pythonProject\main.py", line 2, in <module>
    from ncclient import manager
  File "C:\Users\vgame\PycharmProjects\pythonProject\venv\lib\site-packages\ncclient\manager.py", line 21, in <module>
    from ncclient import operations
  File "C:\Users\vgame\PycharmProjects\pythonProject\venv\lib\site-packages\ncclient\operations\__init__.py", line 16, in <module>
    from ncclient.operations.rpc import RPC, RPCReply, RPCError, RaiseMode, GenericRPC
  File "C:\Users\vgame\PycharmProjects\pythonProject\venv\lib\site-packages\ncclient\operations\rpc.py", line 20, in <module>
    from ncclient.transport import SessionListener
  File "C:\Users\vgame\PycharmProjects\pythonProject\venv\lib\site-packages\ncclient\transport\__init__.py", line 20, in <module>
    from ncclient.transport.unixSocket import UnixSocketSession
  File "C:\Users\vgame\PycharmProjects\pythonProject\venv\lib\site-packages\ncclient\transport\unixSocket.py", line 18, in <module>
    from socket import AF_UNIX, SOCK_STREAM
ImportError: cannot import name 'AF_UNIX' from 'socket' (C:\Python\Python39\lib\socket.py)

**Comment by dongjiadd** [comment]
win 10  / win11

**Comment by dongjiadd** [comment]
> from ncclient import manager
> 
> Traceback (most recent call last): File "C:\Users\vgame\PycharmProjects\pythonProject\main.py", line 2, in from ncclient import manager File "C:\Users\vgame\PycharmProjects\pythonProject\venv\lib\site-packages\ncclient\manager.py", line 21, in from ncclient import operations File "C:\Users\vgame\PycharmProjects\pythonProject\venv\lib\site-packages\ncclient\operations__init__.py", line 16, in from ncclient.operations.rpc import RPC, RPCReply, RPCError, RaiseMode, GenericRPC File "C:\Users\vgame\PycharmProjects\pythonProject\venv\lib\site-packages\ncclient\operations\rpc.py", line 20, in from ncclient.transport import SessionListener File "C:\Users\vgame\PycharmProjects\pythonProject\venv\lib\site-packages\ncclient\transport__init__.py", line 20, in from ncclient.transport.unixSocket import UnixSocketSession File "C:\Users\vgame\PycharmProjects\pythonProject\venv\lib\site-packages\ncclient\transport\unixSocket.py", line 18, in from socket import AF_UNIX, SOCK_STREAM ImportError: cannot import name 'AF_UNIX' from 'socket' (C:\Python\Python39\lib\socket.py)

win 10 /win 11   python 3.9     error

**Comment by einarnn** [comment]
Should be addressed in #609.
