### ISSUE TITLE
Regression: Cannot import `connect()` on Windows 10 - Python 3.11-3.13

### ISSUE THREAD

**Issue by jrebiffe** [ncclient/ncclient#603]
When importing `connect()`, the new ncclient 0.6.16 tries to import `AF_UNIX` on Windows 10, raising an `ImportError`. Forcing pip to install ncclient 0.6.15 resolved the issue.

Tested today, on Python 3.11.9, 3.12.7 and 3.13.0. All on Windows 10 Pro.

```python
Microsoft Windows [version 10.0.19044.2846]
(c) Microsoft Corporation. Tous droits réservés.

C:\Users\PC_MW>
C:\Users\PC_MW>python -X dev
Python 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> from ncclient.manager import connect
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\PC_MW\AppData\Local\Programs\Python\Python311\Lib\site-packages\ncclient\manager.py", line 21, in <module>
    from ncclient import operations
  File "C:\Users\PC_MW\AppData\Local\Programs\Python\Python311\Lib\site-packages\ncclient\operations\__init__.py", line 16, in <module>
    from ncclient.operations.rpc import RPC, RPCReply, RPCError, RaiseMode, GenericRPC
  File "C:\Users\PC_MW\AppData\Local\Programs\Python\Python311\Lib\site-packages\ncclient\operations\rpc.py", line 20, in <module>
    from ncclient.transport import SessionListener
  File "C:\Users\PC_MW\AppData\Local\Programs\Python\Python311\Lib\site-packages\ncclient\transport\__init__.py", line 20, in <module>
    from ncclient.transport.unixSocket import UnixSocketSession
  File "C:\Users\PC_MW\AppData\Local\Programs\Python\Python311\Lib\site-packages\ncclient\transport\unixSocket.py", line 18, in <module>
    from socket import AF_UNIX, SOCK_STREAM
ImportError: cannot import name 'AF_UNIX' from 'socket' (C:\Users\PC_MW\AppData\Local\Programs\Python\Python311\Lib\socket.py)
>>>
```

It also impact on [RobotFramework's NcclientLibrary](https://github.com/vkosuri/robotframework-ncclient) and prevented Robot's Testsuite execution due to import on line 3 [from ncclient import manager](https://github.com/vkosuri/robotframework-ncclient/blob/master/src/NcclientLibrary/NcclientKeywords.py#L3).

**Comment by einarnn** [comment]
The addition of AF_UNIX support was not properly dealt with for Windows platforms. Will take a look.

**Comment by dan-gut1** [comment]
I'm experiencing the same issue

**Comment by keymou** [comment]
Upgrading to 0.6.16 caused this issue, but i downgrading to 0.6.15 resolved it.

**Comment by CZXczx666** [comment]
感谢楼上大哥 这什么破包他妈的

**Comment by markcoolpig** [comment]
Worked on my windows platform after replaced transport\__init__.py as follow:
`"Transport layer"
import os
from ncclient.transport.session import Session, SessionListener, NetconfBase
from ncclient.transport.ssh import SSHSession
from ncclient.transport.tls import TLSSession
from ncclient.transport.errors import *
if os.name == 'nt':
    __all__ = [
    'Session',
    'SessionListener',
    'SSHSession',
    'TLSSession',
    # 'UnixSocketSession',
    'TransportError',
    'AuthenticationError',
    'SessionCloseError',
    'NetconfBase',
    'SSHError',
    'SSHUnknownHostError'

]
else:
    from ncclient.transport.unixSocket import UnixSocketSession
    __all__.append('UnixSocketSession')`

**Comment by einarnn** [comment]
@markcoolpig, would you be open to raising a PR?

**Comment by einarnn** [comment]
Resolved in https://pypi.org/project/ncclient/0.6.17/ by commit #609.
