### ISSUE TITLE
something go wrong with nexus 5672

### ISSUE THREAD

**Issue by davidsome** [ncclient/ncclient#96]
Hi Leopoul
when I use ncclient's ExecCommand
such as show running config, show port-channel summary
it goes wrong in a very small chance.
where goes wrong?
Thanks.

    Traceback (most recent call last):
      File "libs/netconflib.py", line 336, in <module>
    print a.show_port_channel_summary()
      File "libs/netconflib.py", line 210, in show_port_channel_summary
    return m.exec_command(["show port-channel summary"]).xml
      File "/usr/local/lib/python2.7/dist-packages/ncclient-0.4.5-py2.7.egg/ncclient/manager.py", line 209, in __exit__
    self.close_session()
      File "/usr/local/lib/python2.7/dist-packages/ncclient-0.4.5-py2.7.egg/ncclient/manager.py", line 157, in wrapper
    return self.execute(op_cls, *args, **kwds)
      File "/usr/local/lib/python2.7/dist-packages/ncclient-0.4.5-py2.7.egg/ncclient/manager.py", line 227, in execute
    raise_mode=self._raise_mode).request(*args, **kwds)
      File "/usr/local/lib/python2.7/dist-packages/ncclient-0.4.5-py2.7.egg/ncclient/operations/session.py", line 28, in request
    return self._request(new_ele("close-session"))
      File "/usr/local/lib/python2.7/dist-packages/ncclient-0.4.5-py2.7.egg/ncclient/operations/rpc.py", line 325, in _request
    raise self._error
    ncclient.transport.errors.SessionCloseError: Unexpected session close

**Comment by leopoul** [comment]
Could you test with latest version (0.4.7)? Requirement for lxml has changed and may be related to your issue

Thnx
Leonidas

**Comment by davidsome** [comment]
thx I will try it
