### ISSUE TITLE
Getting "Invalid tag value" when trying for RPC calls

### ISSUE THREAD

**Issue by SatyaBetu** [ncclient/ncclient#99]
Hi,

I am new to ncclient and trying to do RPC call and  getting "invalid tag value".

Not sure what i missed here.Any help much would be appreciated.

Note: Using the latest ncclient (0.4.6) version.
>>> sample = """
... <stop-guest  xmlns="urn:vyatta.com:mgmt:vyatta-virtualization:1">
...    <name>Sample1</name>
... </stop-guest>
... """
>>>
>>> result = m.rpc(sample)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/ncclient/manager.py", line 259, in _missing
    sub_ele(root, arg)
  File "/usr/local/lib/python2.7/dist-packages/ncclient/xml_.py", line 187, in <lambda>
    sub_ele = lambda parent, tag, attrs={}, **extra: etree.SubElement(parent, qualify(tag), attrs, **extra)
  File "lxml.etree.pyx", line 2997, in lxml.etree.SubElement (src/lxml/lxml.etree.c:69491)
  File "apihelpers.pxi", line 188, in lxml.etree._makeSubElement (src/lxml/lxml.etree.c:15681)
  File "apihelpers.pxi", line 1571, in lxml.etree._tagValidOrRaise (src/lxml/lxml.etree.c:29181)
ValueError: Invalid tag name u'\n<stop-guest  xmlns="urn:vyatta.com:mgmt:vyatta-virtualization:1">\n   <name>Sample1</name>\n</stop-guest>\n'
>>>

**Comment by vishvardhanreddy** [comment]
Bumping this again, as I am having the same issue.

**Comment by leopoul** [comment]
Could you provide the part of code you are running?

**Comment by leopoul** [comment]
Closing as no response received
